### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] mWeb - Subscription-The Add payment card button still present after adding a card

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** albertodege+admin1@gmail.com
**Issue reported by:** Applause - Intrernal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51594
## Action Performed:
1. Log into an account that has the free trial expired and doesn't have a payment card
2. Navigate to Concierge/Expensify chat where they're being asked to add a payment card
3. Click add card button
4. Add the card, go back to the same chat and verify the button no longer shows up

## Expected Result:
The Add Payment Card button is not displayed after adding a card

## Actual Result:
The Add Payment Card button still present after adding a card

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a94625bf-765d-425f-8671-6dc8ce7ca0c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857406846468547297</li>
        <li>Upwork Job ID: 1857406846468547297</li>
        <li>Last Price Increase: 2024-11-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The add payment card button still shows after successfully adding a payment card.

### What is the root cause of that problem?
The add payment card button shows as long as `doesUserHavePaymentCardAdded` is false.
https://github.com/Expensify/App/blob/a6f1348d08a441f4f9b48a8ef05e5e95c96b53d7/src/pages/home/report/ReportActionItem.tsx#L401-L407

`doesUserHavePaymentCardAdded` checks for the `userBillingFundID` onyx data.
https://github.com/Expensify/App/blob/a6f1348d08a441f4f9b48a8ef05e5e95c96b53d7/src/libs/SubscriptionUtils.ts#L430-L432

However, the `actionableMenuItems` `useMemo` doesn't depend on `userBillingFundID`, so it won't be recalculated and the add button still shows.
https://github.com/Expensify/App/blob/a6f1348d08a441f4f9b48a8ef05e5e95c96b53d7/src/pages/home/report/ReportActionItem.tsx#L400
### What changes do you think we should make in order to solve the problem?

Subscribe to `NVP_BILLING_FUND_ID` in `ReportActionItem` and use the value in `actionableMenuItems` and it it as the `useMemo` deps.

```
const actionableItemButtons: ActionableItem[] = useMemo(() => {
    if (ReportActionsUtils.isActionableAddPaymentCard(action) && userBillingFundID === undefined && shouldRenderAddPaymentCard()) {
```

**Comment by hungvu193** [comment]
I'll review on Monday

**Comment by hungvu193** [comment]
Yes, `nvp_expensify_billingFundID` had value but we forgot to add it to our dependencies list.
@bernhardoj 's [proposal here ](https://github.com/Expensify/App/issues/52564#issuecomment-2478148847)looks good to me!

https://github.com/user-attachments/assets/163c7476-d048-41e3-bee4-fd0342c7f7bf

🎀 👀 🎀  C+ reviewed!

**Comment by hungvu193** [comment]
@AndrewGable This is waiting for your decision. Ty

**Comment by bernhardoj** [comment]
PR is ready

cc: @hungvu193

**Comment by bfitzexpensify** [comment]
@hungvu193 please complete the BZ checklist and I'll post the payment summary for the C+ work

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by hungvu193** [comment]
Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/51594/files#r1881299334

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not a critical one, no need to create slack convo.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.



## Regression Test Proposal
### Precondition:
Your account hasn't had a card added before. You can check this by going to Concierge, checking the messages. If there's a `Add payment card` button under the message section, that means you didn't add a card yet.
### Test:


1. Log into an account that has the free trial expired and doesn't have a payment card
2. Navigate to Concierge/Expensify chat where they're being asked to add a payment card
3. Press add payment card button
4. Add the card, go back to the same chat, and verify the button no longer shows up

Do we agree 👍 or 👎 ?

**Comment by bfitzexpensify** [comment]
Thanks! 

Payment summary: @hungvu193 owed $250 via NewDot manual request for C+ work

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
