### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Web - Search - Text in search field does not move to the end by default to show text cursor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+w8@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report with really long name (invoice chat with user that has email as display name).
3. Click on the search icon on the top right.
4. Click Search in.

## Expected Result:
The text in the search field will move to the end to show the text cursor

## Actual Result:
The text in the search field does not move to the end. The text cursor is hidden and user has to scroll to the right to see the text cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/6b21c058-3a96-46c0-8dec-658745d0b2c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859033501841956761</li>
        <li>Upwork Job ID: 1859033501841956761</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 105007725</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by jliexpensify** [comment]
@lanitochka17 can you clarify what you mean exactly by this:

>Open a report with really long name

Are you saying that any report with a long report title will cause this issue? Do you have any idea of a character limit that will cause this issue?

Or are you referring to just long emails?

**Comment by jliexpensify** [comment]
Waiting on @lanitochka17

**Comment by lanitochka17** [comment]
@jliexpensify I think not only long emails but also reports.

**Comment by jliexpensify** [comment]
@lanitochka17 can you retest on v64-0? I can't reproduce this one consistently

**Comment by lanitochka17** [comment]
Issue is still reproduce

https://github.com/user-attachments/assets/a3d0ebcb-01e4-40b9-96b5-28676b99106c

**Comment by jliexpensify** [comment]
I think this is a #retain issue, since it deals with an annoyance for our current customers.

**Comment by mananjadhav** [comment]
Looks like @daledah's proposal would work. But I want to confirm if we really want it to be fixed.

🎀 👀 🎀 C+ reviewed.

**Comment by dangrous** [comment]
Yeah I think this is worth fixing, especially since people keep reporting it ^ haha.

Go for it, @daledah!

**Comment by jliexpensify** [comment]
Payment Summary

- C: @daledah $250 (to be paid via Upworks)
- C+: @mananjadhav $250 (to be paid via ND)

[Upwork job](https://www.upwork.com/jobs/~021859033501841956761)

Waiting on checklist @mananjadhav

**Comment by mananjadhav** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: NA. It's en edge case that is never considered. 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: NA

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


Regression Test Proposal Template

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Have a report with a really long name.

### Test:


1.  Open a report with really long name (invoice chat with user that has email as display name).
2. Click on the search icon on the top right.
3. Click Search in .... (report name)
4. Verify that the cursor is moved to the end.

Do we agree 👍 or 👎

**Comment by jliexpensify** [comment]
Paid and job closed, @mananjadhav [here is the payment summary.](https://github.com/Expensify/App/issues/52599#issuecomment-2526386202)

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
