### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] No RBR on Subscription row in the LHN in settings if the free trial has expired

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation** (hyperlinked to channel name): [Expensify bugs](https://applause-ts.slack.com/archives/C049HHMV9SM/p1731578046121969)

## Action Performed:

1. Open an account who free trial has expired
2. Go to settings > Subscription

## Expected Result:
RBR should also be on the Subscription row in the LHN
## Actual Result:
Observe that there is a RBR on the Page but not on the settings option
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![Screenshot 2024-11-14 at 3 24 16 PM (1)](https://github.com/user-attachments/assets/9b9b9ad0-a8bc-45ce-a8f4-91d29799a359)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858434959504168009</li>
        <li>Upwork Job ID: 1858434959504168009</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 104948042</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by hungvu193** [comment]
Thanks for the proposals, everyone. @daledah 's proposal here is [straightforward](https://github.com/Expensify/App/issues/52598#issuecomment-2477342129).

🎀 👀 🎀  C+ reviewed.

**Comment by hungvu193** [comment]
Hey @twilight2294,
I think your explanation makes sense. However during the proposals review process, here's what I thought:
- `getBillingStatus` also used the [`subscriptionStatus`](https://github.com/Expensify/App/blob/bd6c90d8493baf70d61937188c94815650f18988/src/pages/settings/Subscription/CardSection/utils.ts#L27) from `SubscriptionUtils.getSubscriptionStatus();`.
- `hasSubscriptionRedDotError` return `getSubscriptionStatus()?.isError ?? false;` which is the error for the whole `Subscription` page not only for one specific case and it was also intentional of the Author who implemented [failed billing scenarios banner feature](https://github.com/Expensify/App/pull/44072).
- `getBillingStatus` retrieves billing details, while `hasSubscriptionRedDotError` indicates the current subscription status, including billing status.

Overall, I'm still aligned with my decision above, we should update the `hasSubscriptionRedDotError` logic instead of `getBillingStatus`.

**Comment by hungvu193** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by hungvu193** [comment]
Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/44072/files#r1875328860

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

### Test:

1. Open an account with free trial expired
2. Go to settings > Subscription
3. Verify that: RBR is displayed on LHN

Do we agree 👍 or 👎

**Comment by zanyrenney** [comment]
### **payment summary**

@hungvu193 requires payment through NewDot Manual Requests - please request $250 on ND
@daledah requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104948042) (Contributor) - paid via upwork
@allgandalf requires payment (Needs manual offer from BZ)

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193

**Comment by zanyrenney** [comment]
@allgandalf invited you for the bug bounty here- https://www.upwork.com/jobs/~021867267566328938332

**Comment by zanyrenney** [comment]
Paid @allgandalf $50 via upwork too!
