### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Track expense - Options are still present in thread details after the expense is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track an expense
4. Go to transaction thread
5. Send a message
6. Click on the report header
7. Click Delete expense
8. Delete the expense
9. Click on the thread in the main chat to return to the thread
10. Click report header

## Expected Result:
Track expense options should not be displayed in thread after the expense is deleted

## Actual Result:
Track expense options is still displayed in thread after the expense is deleted.
The options lead to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2321b5d1-0d37-4cb9-ba54-e1d1faec036c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858671461676585752</li>
        <li>Upwork Job ID: 1858671461676585752</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104973306</li>
<li>twilight2294 | Contributor | 104973308</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Track expense - Options are still present in thread details after the expense is deleted
### What is the root cause of that problem?
The track expense option is displayed if a report is a track expense report.

https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/pages/ReportDetailsPage.tsx#L378

`isTrackExpenseReport` is `true` if the parent report action is track expense action and the parent report is the selfDM.
https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/libs/ReportUtils.ts#L1651

After we delete a track expense, the parent report action still has `type` as `track` in `originalMessage` then the track expense option still appears in the report detail page

![Uploading Screenshot 2024-11-15 at 23.21.58.png…]()

### What changes do you think we should make in order to solve the problem?
Return false in `isTrackExpenseReport` function if the parent report action is deleted action

```
return (
    !isEmptyObject(parentReportAction) &&
    selfDMReportID === report.parentReportID &&
    ReportActionsUtils.isTrackExpenseAction(parentReportAction) &&
    !ReportActionsUtils.isDeletedAction(parentReportAction)
);
```
https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/libs/ReportUtils.ts#L1651

Or we can do this in `isTrackExpenseAction` function

### What alternative solutions did you explore? (Optional)
Or after we delete the track expense, we should remove the `type` in `originalMessage` of parent report action or change `type` to the according type.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Track expense - Options are still present in thread details after the expense is deleted
### What is the root cause of that problem?
The track expense option is displayed if a report is a track expense report.

https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/pages/ReportDetailsPage.tsx#L378

`isTrackExpenseReport` is `true` if the parent report action is track expense action and the parent report is the selfDM.
https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/libs/ReportUtils.ts#L1651

After we delete a track expense, the parent report action still has `type` as `track` in `originalMessage` then the track expense option still appears in the report detail page


### What changes do you think we should make in order to solve the problem?
Return false in `isTrackExpenseReport` function if the parent report action is deleted action

```
return (
    !isEmptyObject(parentReportAction) &&
    selfDMReportID === report.parentReportID &&
    ReportActionsUtils.isTrackExpenseAction(parentReportAction) &&
    !ReportActionsUtils.isDeletedAction(parentReportAction)
);
```
https://github.com/Expensify/App/blob/88713ab03860438f99e0621c22f20de4ffecf27c/src/libs/ReportUtils.ts#L1651

Or we can do this in `isTrackExpenseAction` function

### What alternative solutions did you explore? (Optional)
Or after we delete the track expense, we should remove the `type` in `originalMessage` of parent report action or change `type` to the according type.

**Comment by alexpensify** [comment]
@ikevin127 when you get a chance, please review these proposals and identify whether one will fix the issue. Thank you!

**Comment by ikevin127** [comment]
@twilight2294's [proposal](https://github.com/Expensify/App/issues/52628#issuecomment-2479348636) looks good to me. The RCA is correct and the proposed solution fixes the issue.

The reason I'm for the first solution and not for the 2nd proposal's solution is because `ReportUtils.isTrackExpenseReport(report)` is used in other parts of the app to determine whether an expense report is of type `track`.

Adding a check which determines whether the track expense's parent report action was deleted would bring about regressions in those instances where the extra check is not needed.

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@ikevin127 I don't think we should consider a report as a track expense report if the parent report action is deleted. 

1. All instances that we're using `isTrackExpenseReport` always require the parent report is not deleted
2. It should be the same when we delete an expense/iou report. When we delete an expense/iou report, even the report preview action changes to add comment action and the type of expense/iou report also changes to `chat`.

3. For example `isSingleTransactionView` shouldn't be true if the track expense is deleted. `isSingleTransactionView` is used to display the header as `MoneyRequestHeader` which doesn't make sense in this case the track expense is deleted.

https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/pages/home/ReportScreen.tsx#L261

**Comment by ikevin127** [comment]
@nkdengineer I understand where your proposal is coming from but in this case, based on the issue and its expected result I think adding the check where the first proposal suggested is a simple fix that targets the expected result directly and keeps things within the scope of the issue.

My goal with this review is to keep it within the scope of the issue and not change code which would affect other parts of the app in unknown ways.

If @carlosmiceli considers we should extend the scope of the issue, go with your solution and extend the testing because of all other places where the check is used - then I don't have anything against that.

##
 
@twilight2294 There's no need to reinforce what the reviewer (me, in this case) already decided on, or thumbs down the other contributor's comments as that doesn't bring about anything constructive and the discussion can go down some paths which might not be ideal.

Speaking from experience, most of the times it doesn't help when a contributor becomes hostile or defensive towards another.

Let's keep things cordial and await CME's final decision 🙏

**Comment by carlosmiceli** [comment]
I followed your recommendations, @ikevin127

@mallenexpensify, just [fyi](https://github.com/Expensify/App/issues/52628#issuecomment-2484753106).

**Comment by ikevin127** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment]
cc @alexpensify for visibility

**Comment by alexpensify** [comment]
Payouts due: 2024-11-29

- [ ] Contributor: $250 @twilight2294 
- [ ] Reviewer: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~021858671461676585752). The payment process has been completed here via Upwork.

**Comment by alexpensify** [comment]
@mallenexpensify - I followed up in the B0 Slack room since the template is off in TE, not sure if there are others.
