### ISSUE TITLE
[Payment 2024-12-20] [$250] Search - App crashes when clicking on search icon while app is loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh051101@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Trigger app loading state by going to Troubleshoot > Clear cache and restart > Reset and refresh.
4. Click on search icon on the top right.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when clicking on search icon while app is loading.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[1511_1.txt](https://github.com/user-attachments/files/17778691/1511_1.txt)

https://github.com/user-attachments/assets/69bf093f-66f5-45ee-a38d-3a795064dc0a
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858741837244395820</li>
        <li>Upwork Job ID: 1858741837244395820</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 105177573</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - App crashes when clicking on search icon while app is loading

### What is the root cause of that problem?
The `personalDetailsForParticipants` is null while loading 
https://github.com/Expensify/App/blob/09f6db79f5516e54053344e92962b0a2f0abb1d9/src/components/Search/SearchRouter/SearchRouter.tsx#L126
### What changes do you think we should make in order to solve the problem?

We should use
```
            Object.values(personalDetailsForParticipants ?? {})

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - App crashes when clicking on search icon while app is loading

### What is the root cause of that problem?
The `personalDetailsForParticipants` is null/undefined immediately after clearing cache so it cannot be converted to object here 
https://github.com/Expensify/App/blob/09f6db79f5516e54053344e92962b0a2f0abb1d9/src/components/Search/SearchRouter/SearchRouter.tsx#L126
### What changes do you think we should make in order to solve the problem?

We should use
```
            Object.values(personalDetailsForParticipants ?? {})

```
or we can use a backup empty object  [here](https://github.com/FitseTLT/App/blob/09f6db79f5516e54053344e92962b0a2f0abb1d9/src/components/Search/SearchRouter/SearchRouter.tsx#L122) like this 
https://github.com/Expensify/App/blob/09f6db79f5516e54053344e92962b0a2f0abb1d9/src/pages/RoomMembersPage.tsx#L59
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when clicking on search icon while app is loading
### What is the root cause of that problem?
After we clear the cache, `personalDetailsForParticipants` become `undefined`

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/Search/SearchRouter/SearchRouter.tsx#L122

Then the app crashes here when we open the search page

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/Search/SearchRouter/SearchRouter.tsx#L126-L129

But if the `personalDetailsForParticipants` to be `undefined` why no ts error when we use `Object.values(personalDetailsForParticipants)` here?

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/Search/SearchRouter/SearchRouter.tsx#L126-L129

The problem from here, `usePersonalDetails` is a hook context that is created from `createOnyxContext`

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/OnyxProvider.tsx#L9

The return value of this hook is cast as `NonNullable<OnyxValue<TOnyxKey>>`, then there's no waring when we use like this `Object.values(personalDetailsForParticipants)`


https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/createOnyxContext.tsx#L36

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/createOnyxContext.tsx#L90

### What changes do you think we should make in order to solve the problem?
To avoid the same case can happen in the feature, we can return the type here as `OnyxValue<TOnyxKey>` here

https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/createOnyxContext.tsx#L36

and remove the cast type here
https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/createOnyxContext.tsx#L90

After that, we can see all waring places via ts error or lint error that possible cause the app crashes when we use the value from the createOnyxContext hook and fix all places.


or if the value here is `undefined`, we can return a non null value based on the type of `OnyxValue<TOnyxKey>`. For example, return empty object if this type is an object, return empty array if the type is array,...
https://github.com/Expensify/App/blob/a54f91352150f409e51de185feeb06f6a9f5f618/src/components/createOnyxContext.tsx#L90

### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ef14c33b-653e-4fda-adb8-d988dc9464f5">

Repro'd.

**Comment by nkdengineer** [comment]
@alitoshmatov Can you review the proposals?

**Comment by alitoshmatov** [comment]
@FitseTLT Thank you for your proposal, Your RCA is correct and solution is solving the issue.

**Comment by alitoshmatov** [comment]
@nkdengineer Thank you for detailed RCA, I think you are right we should fix typing here to prevent all similar cases from occurring.

**Comment by alitoshmatov** [comment]
I think we can go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/52633#issuecomment-2479496928). Which addresses the root cause, and fixes the wrong typing which didn't not cover this edge case

C+ reviewed 🎀 👀 🎀

**Comment by nkdengineer** [comment]
@deetergp Please help to take a look when you have a chance.

**Comment by alitoshmatov** [comment]
Waiting for @deetergp

**Comment by nkdengineer** [comment]
The PR is almost done, will open in a few hours.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by strepanier03** [comment]
### Payment Summary

HOLD FOR 2024-12-20

- [ ] $250 @alitoshmatov via New Expensify
- [ ] $250 @nkdengineer via Upwork

**Comment by strepanier03** [comment]
I'll remove the hold from the payment summary tomorrow.

**Comment by strepanier03** [comment]
@nkdengineer - I've paid and closed your contract in Upwork, thank you!

@alitoshmatov - The payment summary is [here](https://github.com/Expensify/App/issues/52633#issuecomment-2555341483) and you're welcome to request payment, thank you as well. 

Have a lovely new year!

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
