### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Web - Header - Approve button appears briefly when it shouldn't

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+2101@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. As an admin, create a new workspace and add User A along with another user.
3. Go to the more features and enable workflow and rules
4. Navigate to the "Workflows" and add an approval workflow where User A is assigned as both the submitter and approver.
5. Go to the "Rules" section and enable "Prevent Self Approval."
6. Log in as User A, go to the workspace chat, and create an expense.
7. Open the expense preview and observe that the submit button is disabled.
8. Switch to the admin account and go to the "Workflows" section to change the approver from User A to the other user.
9. Return to User A's account, observe that the submit button is now enabled, and click on it.

## Expected Result:
When clicking the submit button, the approve button should not appear at any point.

## Actual Result:
When clicking the submit button, the approve button briefly appears.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ba5b35ea-be79-43ce-965d-906abd350313
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858267603397515787</li>
        <li>Upwork Job ID: 1858267603397515787</li>
        <li>Last Price Increase: 2024-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105001353</li>
<li>daledah | Contributor | 105001356</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by jliexpensify** [comment]
I can reproduce this one, I think it'll be a #quality issue?

**Comment by DylanDylann** [comment]
@daledah What do you think if we always set the first approver ID to managerID when submitting a report? Another question why do we need to revert the managerID in the failureData?

**Comment by DylanDylann** [comment]
@NJ-2020 Thanks for your contribution with detailed RCA. I notice that you suggest 4 solutions with a brief and sketchy explanation for each one. I think we should only propose solutions that you think are the best and give more detail about that.

@daledah's [proposal](https://github.com/Expensify/App/issues/52669#issuecomment-2482095090) looks good to me

🎀 👀 🎀 C+ Reviewed

**Comment by DylanDylann** [comment]
@daledah Could you give an ETA?

**Comment by jliexpensify** [comment]
Payment Summary

- C: @daledah $250 (to be paid via Upworks)
- C+: @DylanDylann $250 (to be paid via Upworks) - waiting on checklist

[Upwork job](https://www.upwork.com/jobs/~021858267603397515787)

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by jliexpensify** [comment]
Paid and job closed!
