### ISSUE TITLE
[HOLD for payment 2024-12-12] [$250] Invoice - "Approve" button shows up for the invoice receiver under "Pay"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause  - Internal Team

## Action Performed:
1. Admin: Navigate to https://staging.new.expensify.com/
2. Admin: Log in with a new Gmail account
3. Admin: Create a workspace
4. Admin: Navigate to Workspace settings - More features
5. Admin: Enable "Workflows" and "Invoices"
6. Admin: Navigate to Workspace settings - Workflows
7. Admin: Enable "Add approvals"
8. Admin: Navigate to Workspace settings - Members
9. Admin: Add a new Gmail account as a member
10. Admin: Navigate to the LHN
11. Admin: Navigate to FAB - Send invoice
12. Admin: Send an invoice to the workspace member with any amount, company name and URL
13. Member: Log in
14. Member: Navigate to the invoice room
15. Member: Click on the "Pay" button on the invoice preview
16. Member: Click on "Approve"

## Expected Result:
"Approve" button shouldn't be visible

## Actual Result:
"Approve" button shows up for the invoice receiver under "Pay". Nothing happens when the button is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4a4a9d86-cda7-4348-b517-6cbfcb20c263

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861529804786671047</li>
        <li>Upwork Job ID: 1861529804786671047</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approver button is shown in the SettlementButton dropdown
### What is the root cause of that problem?
This line is causing the issue:
https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/libs/actions/IOU.ts#L7123

because in this case the `managerID === userAccountID` is true.
### What changes do you think we should make in order to solve the problem?
1. I think `ouReport?.managerID `, should be same as the admins's account id, so considering this it seems like a BE issue.

2. Another option is that we could ass ` policy.role === CONST.POLICY.ROLE.ADMIN;`, in the above condition
if this true then show the approve button the dropdown(not sure here, because we may still want to show the approve button for another workflow approver which could not be the admin)

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approver button is shown in the SettlementButton dropdown for "user", which is not the admin
### What is the root cause of that problem?
This line is causing the issue:
https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/libs/actions/IOU.ts#L7123

because in this case the `managerID === userAccountID` is true.
### What changes do you think we should make in order to solve the problem?
1. I think `ouReport?.managerID `, should be same as the admins's account id, so considering this it seems like a BE issue.

2. Another option is that we could use ` policy.role === CONST.POLICY.ROLE.ADMIN;`, in the above condition
if this true then show the approve button the dropdown(not sure here, because we may still want to show the approve button for another workflow approver which could not be the admin)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approve button shows for invoice report.

### What is the root cause of that problem?
This started to happen after https://github.com/Expensify/App/pull/47926. Previously, we check the chat report whether it's a policy expense chat or not. If it's a policy expense chat, then it must be an expense report. But the PR decide to not check the chat report anymore.

> The IOU.canApproveIOU method relies on the parent report chat to determine if the report can be approved or not. This is a problem because approvers of expense reports might not necessarily have access to the parent report, or the parent report might not be loaded in local Onyx state, which leads to a bug whereas the approver can't see the approve button.
>
> Luckily we know all the information we need to show the button from the expense report and the policy of the report which the user should have locally.

The issue with that is we assume that the report passed to `canApproveIOU` is always an expense report. If we see the comment, we only want to show approve if it's an expense report, but we don't check for that.
https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/libs/actions/IOU.ts#L6726-L6731

### What changes do you think we should make in order to solve the problem?

Check for expense report and return false if it's not an expense report.
```
if (!ReportUtils.isExpenseReport(iouReport) || !isPaidGroupPolicy) {
    return false;
}
```

**Comment by abekkala** [comment]
reviewed this one once more. adding external

**Comment by brunovjk** [comment]
Thank you all for the proposals. @Shahidullah-Muffakir, but I don’t think your RCA is accurate in this case.
 **I'm leaning toward @bernhardoj’s** [**proposal**](https://github.com/Expensify/App/issues/52667#issuecomment-2481005645) because it provides a more robust safeguard by validating report types and addressing potential edge cases beyond just invoices. However, before proceeding to assign @bernhardoj, I’d like to clarify one point regarding @NJ-2020’s [proposal](https://github.com/Expensify/App/issues/52667#issuecomment-2480931918).

NJ-2020 mentioned: *"When the admin sends the invoice to the member, the BE returns `managerID` equal to the member's account ID."* This behavior seems to be expected based on the current logic, but can we confirm if this is intentional?

🎀👀🎀 C+ reviewed

**Comment by blimpich** [comment]
Does it return the `managerID` always? Or only when "add approvals" is on? Or only when the users are members on the same workspace?

**Comment by brunovjk** [comment]
> Does it return the `managerID` always? Or only when "add approvals" is on? Or only when the users are members on the same workspace?

In my tests it seems so. However, I can reproduce the issue only when approvals is enabled and the member belongs to the workspace:

https://github.com/user-attachments/assets/633f86b9-4fda-4bfd-a288-950e43b9a22a

**Comment by brunovjk** [comment]
@blimpich apologies for the delay. I tested 4 scenarios:  
- **Both workspace members** (Admin and Member) with **Add Approval On**  
- **Both members** with **Add Approval Off**  
- **Non-workspace member** (Admin only) with **Add Approval On**  
- **Non-member** with **Add Approval Off**  

In the admin log, the backend `sendInvoice` call always returns `managerID` equal to `receiverAccountID`. However, on the member's device, the approval button only appears in the dropdown when **Both workspace members** have **Add Approval On**:  

https://github.com/user-attachments/assets/0eedaf84-d82d-4284-a37b-68bd1352660d  

I also noticed another bug where the values are `0.00`. I'll check if it’s already been reported.

**Comment by brunovjk** [comment]
Hi @blimpich, I think we correctly assigns `managerID` to `receiverAccountID` during `sendInvoice`. The issue seems to be in the `canApproveIOU` function, missing a check to exclude invoice reports after `// Only expense reports can be approved`. @NJ-2020 [mentioned first](https://github.com/Expensify/App/issues/52667#issuecomment-2480931918), but I'm leaning towards @bernhardoj's [proposal](https://github.com/Expensify/App/issues/52667#issuecomment-2481005645). Could you weigh in? Thanks!

**Comment by blimpich** [comment]
Thank you @brunovjk! Sorry for my slow response, was OOO for part of last week. I think based off the investigations in your comment [here](https://github.com/Expensify/App/issues/52667#issuecomment-2507649510) we can say that it is intentional that the `managerID` is equal to the `recieverAccountID`.

And I agree, I think @bernhardoj's proposal is the most ideal. Lets do it! 🚀

**Comment by blimpich** [comment]
@bernhardoj are you able to get a PR up for this soon?

Also @abekkala it looks like there was an [issue in the upwork automation](https://github.com/Expensify/App/issues/52667#issuecomment-2512368516), just FYI.

**Comment by bernhardoj** [comment]
PR is ready

cc: @brunovjk

**Comment by abekkala** [comment]
> Also @abekkala it looks like there was an https://github.com/Expensify/App/issues/52667#issuecomment-2512368516, just FYI.

When we get to the payment stage I'll manually send offers - thanks!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR DEC 12

- Fix: @bernhardoj [$250, if no regressions] Payment via NewDot
- PR Review: @brunovjk [$250, if no regressions]  [Offer](https://www.upwork.com/nx/wm/offer/105226583)

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause - Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/47926/files#r1879932231

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

### Prerequisite: (as admin)
1. Go to Workspace settings - More features
2. Enable "Workflows" and "Invoices"
3. Go to Workspace settings - Workflows
4. Enable "Add approvals"
5. Go to Workspace settings - Members
6. Add the 2nd user as the new member
7. Go to the LHN
8. Open FAB - Send invoice to the new member

### Step: (as member)
1. Open the invoice report
2. Press the pay button
3. Verify there is no Approve option

Do we agree 👍 or 👎

**Comment by abekkala** [comment]
@brunovjk payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR DEC 12
- Fix: @bernhardoj [$250, if no regressions] Payment via NewDot
- PR Review: @brunovjk [$250, if no regressions] [paid]
