### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] "Terms of Service" and "Privacy Policy" is briefly shown before magic code is requested

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Navigate to Settings - About - "Terms of Service" or "Privacy"

## Expected Result:
I should be logged into OD, "Terms of Service" and "Privacy Policy" should be visible without asking for magic code. Or the magic code modal should be visible without showing the "Terms of Service" and "Privacy Policy"

## Actual Result:
"Terms of Service" and "Privacy Policy" is briefly shown before magic code is requested

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/68e966bd-a62a-4396-8cd3-f9128c5e69f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858637388498137276</li>
        <li>Upwork Job ID: 1858637388498137276</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Magic code is request if user click on "Terms of Service" or "Privacy Policy" in About page
### What is the root cause of that problem?
this is causing the issue:
https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/pages/settings/AboutPage/AboutPage.tsx#L169
and this:
https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/pages/settings/AboutPage/AboutPage.tsx#L176
### What changes do you think we should make in order to solve the problem?
I think we can simply change it to the following, because the Terms of Service and Privacy Policy pages are publicly available user can simply open it by the URL: 
`https://www.expensify.com/terms`

change those two lines to:
`                              onPress={() => Link.openExternalLink(CONST.TERMS_URL)}
`and:
`                            onPress={() => Link.openExternalLink(CONST.PRIVACY_URL)}
`

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Terms of Service" and "Privacy Policy" is briefly shown before magic code is requested

### What is the root cause of that problem?
By default, `openLink` function is called when we click on a `TextLink`

https://github.com/Expensify/App/blob/d5e7a5abde0dfc52312a15feba776f3ef2f0be49/src/components/TextLink.tsx#L43

In this function, `openOldDotLink` is called if the `href` is an `internalExpensifyPath`. Then, we will open an OD link with `authenToken`, but maybe it doesn't work as expected in OD now. And a magic code page is opened with another account.

https://github.com/Expensify/App/blob/d5e7a5abde0dfc52312a15feba776f3ef2f0be49/src/libs/actions/Link.ts#L187-L190
### What changes do you think we should make in order to solve the problem?
I think the search teams and privacy can be a public URL so we shouldn't call with `openOldDotLink`. To fix for all places that we're using term and privacy url, we can create a new const `OLD_DOT_PUBLIC_URLS` which will contain all public old dot URL

```
const OLD_DOT_PUBLIC_URLS: string[] = [CONST.TERMS_URL, CONST.PRIVACY_URL];
```

then here we will not call `openOldDotLink` if it is a public URL. So it can simply open a new tab with the `href` [here](https://github.com/Expensify/App/blob/d5e7a5abde0dfc52312a15feba776f3ef2f0be49/src/libs/actions/Link.ts#L192)

```
const isPublicOldDotURL = OLD_DOT_PUBLIC_URLS.includes(href);
if (internalExpensifyPath && !isAttachment && !isPublicOldDotURL) {
    openOldDotLink(internalExpensifyPath);
    return;
}
```
https://github.com/Expensify/App/blob/d5e7a5abde0dfc52312a15feba776f3ef2f0be49/src/libs/actions/Link.ts#L187-L190

### What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment]
Not overdue, Melvin

**Comment by ikevin127** [comment]
This issue should be `Internal` for two reasons:
1. `External` contributors don't have access to the OD / BE repos which is needed to debug this and find the root cause.
2. The issue's root cause seems to be OD / BE related since the ND / FE logic which handles the [`openOldDotLink`](https://github.com/Expensify/App/blob/baa1b2fecb5deda177888ae4f83312c708f741d4/src/libs/actions/Link.ts#L72-L88) works as expected, meaning it generates the `shortLivedAuthToken` and passes the data to the link correctly which if OD / BE would work as expected -> would automatically login the user and display the "Terms of Service" and "Privacy Policy" pages right away without displaying any additional login step hence redirecting away from the target pages.

##

Seems like both proposals are suggesting simply navigating to the "Terms of Service" and "Privacy Policy" pages as they are public, removing the auto-login logic. This can be an alternative until the OD / BE issue is fixed but ultimately I think that solution is a workaround which defeats the purpose of the existing auto-login logic (which is the root cause of our issue and should be fixed because it doesn't work as expected).

**Comment by nkdengineer** [comment]
@rayane-djouah 

- I think you should add C+ review comment to assign internal to take a look.


- term URL and privacy URL are used in many places so I think we should fix them for all cases. What do you think about my [proposal](https://github.com/Expensify/App/issues/52666#issuecomment-2482242233) if we're looking for a temporary fix

**Comment by MitchExpensify** [comment]
> I think you should add C+ review comment to assign internal to take a look.

Let's do this to get an internal engineer's opinion!

**Comment by MitchExpensify** [comment]
Hi @marcochavezf , can you help us move along here as internal assignee?

**Comment by marcochavezf** [comment]
Sure, I will check it out today

**Comment by MitchExpensify** [comment]
Have you had a chance to check this out @marcochavezf ?

**Comment by marcochavezf** [comment]
This is an edge case for unvalidated accounts trying to log in from NewDot to OldDot. Given the ROI of this flow and the potential security risk, I think it's acceptable to open the public link for now or close it out

**Comment by nkdengineer** [comment]
> I think it's acceptable to open the public link for now or close it out

> term URL and privacy URL are used in many places so I think we should fix them for all cases. What do you think about my https://github.com/Expensify/App/issues/52666#issuecomment-2482242233 if we're looking for a temporary fix

@rayane-djouah Please help to review the proposal again.

**Comment by Shahidullah-Muffakir** [comment]
@rayane-djouah @MitchExpensify @marcochavezf,
Nothing has changed in terms of the expected behavior or the content of the other proposal. Since my solution was already selected initially https://github.com/Expensify/App/issues/52666#issuecomment-2489613805, I find it unfair to switch to another without a solid justification.

I strongly believe that my solution is more effective, as it is straightforward and aligns with existing implementations in other parts of the app for similar purposes.

Could we revisit this decision?

**Comment by nkdengineer** [comment]
@marcochavezf Please help to check this [comment](https://github.com/Expensify/App/issues/52666#issuecomment-2518651766).

**Comment by marcochavezf** [comment]
I agree with @rayane-djouah analysis in the last comment. @Shahidullah-Muffakir @nkdengineer  onward and upward 🚀

**Comment by bfitzexpensify** [comment]
Payment complete to @nkdengineer
