### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Tag rules - Approver field in tag editor shows user email instead of user name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+khcategory18@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click on the existing approval workflow under Add approvals.
4. Note that Approver field shows user name.
5. Go to workspace settings > Tags.
6. Click on any tag.
7. Click Approver.
8. Select a user with custom name.

## Expected Result:
Approver field in tag editor will show user name.

## Actual Result:
Approver field in tag editor shows user email instead of user name.

In Category editor, Approver field shows user name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/36707c93-fe19-4452-a0ec-e8eec0b54c9d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858313853614949592</li>
        <li>Upwork Job ID: 1858313853614949592</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 104985198</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tag rules - Approver field in tag editor shows user email instead of user name
### What is the root cause of that problem?
We display this display name --> email in `CategorySettingsPage`

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/categories/CategorySettingsPage.tsx#L79-L83

But we only display the text returns from `getTagApproverRule` function which is the user email
https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/tags/TagSettingsPage.tsx#L107

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/tags/TagSettingsPage.tsx#L183
### What changes do you think we should make in order to solve the problem?
In `TagSettingsPage`, we should do the same way [here](https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/categories/CategorySettingsPage.tsx#L79-L83) to display the tag approver display name first


https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/tags/TagSettingsPage.tsx#L107

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/tags/TagSettingsPage.tsx#L183
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mkzie2** [comment]
### Updated [proposal](https://github.com/Expensify/App/issues/52678#issuecomment-2481415267).

- Add an edge case.

**Comment by mkzie2** [comment]
@eh2077 Could you please check again

1. This implementation isn't correct, it doesn't fallback to the approver email if the display name is empty or undefined

```
const approver = PersonalDetailsUtils.getPersonalDetailByEmail(tagApprover)?.displayName;
```

> I notice that we need to use || because approverDetails?.displayName can be an empty string if the user doesn't have a custom display name. And we need to fix the same in CategorySettingsPage

2. If we use the same way with `CategorySettingsPage`, we need to use `||` instead of `??` because `displayName` can be an empty string.

**Comment by eh2077** [comment]
@mkzie2 Thanks for your comment. I voted for @etCoderDysto 's proposal because I think the initial version of their proposal is clear to fix this straightforward issue.

> If we use the same way with CategorySettingsPage, we need to use || instead of ?? because displayName can be an empty string.

I appreciated your discussion on this though I believe this won't be an issue for most use cases because we're not allowed to save empty display name.

**Comment by mkzie2** [comment]
> I appreciated your discussion on this though I believe this won't be an issue for most use cases because we're not allowed to save empty display name.

The user can skip the onboarding if it's a new account that is invited to a WS or an existing user creates an expense with this user before the new user login the first time.

**Comment by kadiealexander** [comment]
Payments due:

- [ ] Contributor: @etCoderDysto paid $250 via Upwork ([automatic offer](https://www.upwork.com/nx/wm/offer/104985198))
- [ ] Reviewer: @eh2077 owed $250 via manual request

**Comment by kadiealexander** [comment]
@eh2077 please don't forget the checklist!

**Comment by eh2077** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by eh2077** [comment]
Requested payment in NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @eh2077
