### ISSUE TITLE
[HOLD for payment 2024-12-05] [$125]  Xero - Selected Xero bank account is not highlighted with a green checkmark

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52699]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5220818
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/5220818
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting.
3. Connect to Xero.
4. After connecting to Xero, click Export.
5. Click Xero bank account.

## Expected Result:
The selected Xero bank account should be highlighted with a green checkmark.

## Actual Result:
The selected Xero bank account is not highlighted with a green checkmark.
It is only highlighted after manually selecting it.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6f2b9613-002b-4e7f-aed5-6a009a2b1d32
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858554918265952310</li>
        <li>Upwork Job ID: 1858554918265952310</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 105021706</li>
<li>twilight2294 | Contributor | 105021707</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment]
This one feels like a super easy change so I'm going to set the price to $125. If there are additional fields where this is happening, or if it is actually more complex than I realize, let me know and we can consider increasing the price.

**Comment by ahmedGaber93** [comment]
reviewing today

**Comment by ahmedGaber93** [comment]
I faced a troubleshot while reproducing, How can I add a bank account in Xero? Can any one help?

 ![Screenshot 2024-11-22 at 3 00 33 AM](https://github.com/user-attachments/assets/3f307c00-0ec4-4433-8bd3-21d857bb6144)

**Comment by ahmedGaber93** [comment]
@twilight2294's [proposal](https://github.com/Expensify/App/issues/52699#issuecomment-2483631521) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by FitseTLT** [comment]
@ahmedGaber93 Can u please take a look again? The problem doesn't have anything related with using `??` or `||` we are already using `??` to give fallback in the Configuration page to show the default bank account
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx#L26
This is because the selectedAccount either doesn't exist or it is non-empty string and we should also be consistent with it. You are being mislead by the contributor into applying unnecessary safety. The bug is only related to not giving the first bank account as a fallback here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/workspace/accounting/xero/export/XeroBankAccountSelectPage.tsx#L31
The default bank account is visible in the menu item because we give the first bank account as a fallback here (note: using `??`) 
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx#L26
But when the user opens the page we haven't given the same first bank account as fallback in XeroBankAccountSelectPage so it is not selected.
So we should give the same fallback in both cases in the same way. The ` selectedAccount?.name` cannot just be an empty string we know we set it to some non-empty string value or it is not set in which case we give a fallback. Please re-review. Thx!
cc @justinpersaud

**Comment by ahmedGaber93** [comment]
@FitseTLT Thanks for the feedback, I tested your proposal well, and it doesn't fix the issue.

<details>
<summary>see the test video here</summary>


https://github.com/user-attachments/assets/bff9fdd1-0f56-4ec9-8429-ce9cbb2b836a



</details>

there is a different between type of `config?.export?.nonReimbursableAccount` and type of `selectedAccount`
`config?.export?.nonReimbursableAccount` is come from BE as string, and in this issue case it comes with empty string `""` and nullish check `??` only checks for null and undefined
`selectedAccount` type should be `object | undefined` (see line 25)

https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx#L25-L26

Another point I was thinking about it before choose the second proposal, is this small different between two proposal is worth to choose the second proposal over the first proposal that have the first root cause?

I think here it is a small different, but it is important, and it should be worth If we take into consideration the issue is a straight forward with simple RCA, and the Actual Result in OP line 2 can easily lead to what the fix should be.

**Comment by FitseTLT** [comment]
@ahmedGaber93 Got it! Thx 👍

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @twilight2294 $125, paid via Upwork
Contributor+: @ahmedGaber93 $125, I will complete payment once the BZ checklist is done

**Comment by ahmedGaber93** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/46898/files#r1871855560

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

This is a minor change, and I think no regression test required.

**Comment by ahmedGaber93** [comment]
@sakluger Checklist have been completed, and I will get paid via NewDot.

**Comment by sakluger** [comment]
@ahmedGaber93 thanks! Also, thanks for clarifying that you're paid now via NewDot. I withdrew the Upwork offer and updated the payment summary above.

FYI, you should no longer get automated Upwork offers sent to you - if that continues to happen, please let us know so we can make sure you're set up correctly in our system.

**Comment by ahmedGaber93** [comment]
Requested in ND
