### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Held expense - Empty message with reply appears after paying the unheld amount for second time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh051115@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B.
3. [User B] Hold the first expense.
4. [User B] Click Pay button and pay the unheld amount.
5. [User A] Submit another expense to User B.
6. [User B] Go to the expense report.
7. [User B] Click Pay button and pay the unheld amount.
8. [User B] Note that the held expense is marked as paid when it should be moved to another report.
9. [User B] Refresh the expense report.
10. [User B] Note that there is an empty message with reply which opens the held expense when clicked.

## Expected Result:
In Step 8, the held expense should move to another report when only the pending amount is paid.
In Step 10, after refreshing the page, there should not be an empty message in the expense report.

## Actual Result:
In Step 8, the held expense does not move to another report when only the pending amount is paid. The expense preview is marked as paid when only the unheld amount is paid.

In Step 10, after refreshing the page, there is an empty message in the expense report, which opens the held expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/30edbfda-f5d2-4387-907c-77893225d3d2

![Bug6668237_1731920941852!bandicam_2024-11-18_17-01-57-378](https://github.com/user-attachments/assets/0e4f4e56-a2e4-446a-8789-a0d1de26eba2)  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859730399211188082</li>
        <li>Upwork Job ID: 1859730399211188082</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105075616</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The hold report action isn't removed from the paid expense chat and becomes empty when revisiting the report.

### What is the root cause of that problem?
When we pay the expense report with held expense, it will optimistically remove the held expense and move it to the new optimistic expense report. 
https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/libs/actions/IOU.ts#L6309-L6331

But the issue started to happen when we did it again the second time. It's because when we optimistically add the held expense to a new expense report, we set the pending action to add (as shown above). But we don't clear it when the request is successful. So, the pending action is always true and when we optimistically delete it, it will still be shown because a pending action is always shown.

https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/libs/ReportActionsUtils.ts#L676-L679

It becomes an empty message when we reopen it because the BE response changes the action to ADDCOMMENT instead of IOU.

### What changes do you think we should make in order to solve the problem?

We need to clear the pending action when the request is successful.
```
const successAddHoldReportActions = {};

holdReportActions.forEach((holdReportAction) => {

const reportActionID = rand64();
addHoldReportActions[reportActionID] = {
    ...
    pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
};

successAddHoldReportActions[reportActionID] = {
    pendingAction: null,
};
```

We might need to do it for the optimistic report preview too because it also adds a pending action when created optimistically.
https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/libs/actions/IOU.ts#L6295-L6302

We can do the same with other optimistic data that I missed.

**Comment by johncschuster** [comment]
@DylanDylann please review the proposal above!

**Comment by johncschuster** [comment]
Bump!

**Comment by DylanDylann** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/52696#issuecomment-2484645211) looks good to me

Note for the PR phase: we need to find out all pendingAction fields and make sure it is reset in successData

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment]
There is currently a bug where the pay button doesn't show if there are held expenses. It's reported on the issue that causes it [here](https://github.com/Expensify/App/issues/50479#issuecomment-2499693630)

**Comment by bernhardoj** [comment]
PR is ready

cc: @DylanDylann

**Comment by johncschuster** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @bernhardoj due $250 via NewDot
Contributor+: @DylanDylann paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/105075616)

Upwork job [here](https://www.upwork.com/jobs/~021859730399211188082)! Please apply

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by johncschuster** [comment]
Payment has been issued through Upwork. Thanks, everyone, for your contributions!

**Comment by johncschuster** [comment]
Oh wait, I jumped the gun. @DylanDylann, can you please post the regression test steps if applicable?

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>
