### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Remove pinned SelfDM for new users with  "introSelected": "newDotManageTeam"

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#52830]
Proposal: Remove pinned SelfDM for new users with  "introSelected": "newDotManageTeam" ([slack](https://expensify.slack.com/archives/C07HPDRELLD/p1732054860246919))

Background: We pinned the SelfDM to all user's cases, thinking it might give them a place to make notes and try submitting an expense to themselves before someone else. I think we left the SelfDM pinned for all users by default to see if it causes issues while seeing if some people might use it as intended. But I don’t think we’ve really seen that.

Problem: The SelfDM adds noise and confusion to users looking to get their team set up

Solution: Remove SelfDM from being pinned for users with this introSelection so they don’t see it unless they track an expense.

Below is what the LHN looks like today. We would not pin or show the SelfDM going forward. 
![image](https://github.com/user-attachments/assets/e0001cb7-d780-463c-8dd7-f5dc67a50695)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860980169165781817</li>
        <li>Upwork Job ID: 1860980169165781817</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove pinned SelfDM for new users with "introSelected": "newDotManageTeam"

### What is the root cause of that problem?
We don't update the selfDM to unpinned after the onboarding is complete and backend also doesn't update it.

### What changes do you think we should make in order to solve the problem?
In `prepareOnboardingOptimisticData`, we need to update selfDM to unpin in `optimisticData` and reset it in `failureData` if the `engagementChoice` is `newDotManageTeam`

```
const selfDMReportID = ReportUtils.findSelfDMReportID();
const selfDMReport = ReportConnection.getReport(selfDMReportID ?? '-1');

if (engagementChoice === CONST.ONBOARDING_CHOICES.MANAGE_TEAM) {
    optimisticData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${selfDMReportID}`,
        value: {
            isPinned: false
        }
    })

    failureData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${selfDMReportID}`,
        value: {
            isPinned: selfDMReport?.isPinned
        }
    })
}
```

https://github.com/Expensify/App/blob/ba655634cc568818761dddceeae97b3b4ef48d38/src/libs/actions/Report.ts#L3474

We need to always do this in `prepareOnboardingOptimisticData` because we also have another case `completeOnboarding` here with `onboardingPurpose` is `newDotManageTeam` [here](https://github.com/Expensify/App/blob/ba655634cc568818761dddceeae97b3b4ef48d38/src/libs/actions/IOU.ts#L7428-L7430). This is the case that the new user is invited to a workspace before the first time login. In this case, the normal onboarding flow is skipped and the first time the user selects a payment method, the onboarding is completed in `completePaymentOnboarding`

https://github.com/Expensify/App/blob/ba655634cc568818761dddceeae97b3b4ef48d38/src/libs/actions/IOU.ts#L7415

### What alternative solutions did you explore? (Optional)
We can unpin the selfDM by default from backend side and then update it to pinned if we select an `onboardingPurpose` isn't `newDotManageTeam`.

**Comment by suneox** [comment]
Thank you for all the proposals.

We have a different solution from @twilight2294 [proposal](https://github.com/Expensify/App/issues/52830#issuecomment-2497532184), which only handle use case complete `OnboardingAccounting` by adding a new prop. However, there are several other use cases, such as updating `onboardingPurpose` when completing `OnboardingPersonalDetails` or `PaymentOnboarding` at KYCWall.

@nkdengineer [proposal](https://github.com/Expensify/App/issues/52830#issuecomment-2498181972) identifies these additional use cases and suggests always retrieving the value from `prepareOnboardingOptimisticData` instead of passing props. Additionally, this proposal also handles reverting the value in `failureData`, which is LGTM.

Overall, we can proceed with @nkdengineer [proposal](https://github.com/Expensify/App/issues/52830#issuecomment-2498181972).

🎀 👀 🎀 C+ reviewed

**Comment by danielrvidal** [comment]
Thank you team! Looking forward to the PRs!

**Comment by MonilBhavsar** [comment]
Looks good to me.
Once we have App draft up. I'll test backend PR and submit it for review

**Comment by danielrvidal** [comment]
@mallenexpensify something didn't work with the roles. Do you mind fixing?

**Comment by mallenexpensify** [comment]
hmm... not sure what's going on here, only guess is that `Bug` (nor `NewFeature`)  wasn't added so that messed up automation.   @puneetlath , I snagged this from you as BZ so i can monitor in case the "❌ There was an error making the offer to" is larger than just this one issue.

**Comment by MonilBhavsar** [comment]
Both PR's are in review now

**Comment by MonilBhavsar** [comment]
Yes, App PR will fix this issue

**Comment by trjExpensify** [comment]
Great stuff, thanks for confirming!

**Comment by flaviadefaria** [comment]
Hey team, migrated users are still having the self-DM pinned when this change should also have accounted for them. Do we need to update the logic?

**Comment by suneox** [comment]
> Hey team, migrated users are still having the self-DM pinned when this change should also have accounted for them. Do we need to update the logic?

I think we can incorporate the update logic into issue #53405.

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: *Improvement*

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [x] 2z. Other: *All enviroment*

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: *This is an improvement, so we don’t have an offending PR.*

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
    *N/A: It isn't an impactful bug*

**Comment by mallenexpensify** [comment]
Contributor: @nkdengineer owed $250 via Upwork
Contributor+: @suneox owed $250 via Upwork. 

Please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021860980169165781817

**Comment by suneox** [comment]
Thank you! I’ve accepted an offer.

**Comment by nkdengineer** [comment]
@mallenexpensify TY, I applied to that job

**Comment by mallenexpensify** [comment]
Contributor: @nkdengineer owed $250 via Upwork
Contributor+: @suneox paid $250 via Upwork. 

@nkdengineer Please accept the job and reply here once you have?
[upwork.com/jobs/~021860980169165781817](https://www.upwork.com/jobs/~021860980169165781817)

**Comment by nkdengineer** [comment]
@mallenexpensify Done!

**Comment by mallenexpensify** [comment]
@nkdengineer paid, payment breakdown updated above. 

I [created a testcase](https://github.com/Expensify/Expensify/issues/453893) and provided the reasoning below.  We'll see what QA wants to do, if anything
> This one's a lil weird, I'm unsure if we _need_ a test case for it but.. if this feature stops working correctly, we'd like to know. IF there's not a test case then someone would have to report. ¯\_(ツ)_/¯
