### ISSUE TITLE
[Hold] [$125] Proposal: Update workspace chats beginning of chat history to reference "You" rather than your email. 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#52833]
Problem: Users are confused by workspace chats because we refer to their email rather than saying "You", which doesn't make much sense to them. 

You can see the text below: This is where Danrvidal+test111912@gmail.com will submit expenses to [Danrvidal+test111912@gmail.com](mailto:Danrvidal+test111912@gmail.com)’s Workspace. Just use the + button.
![image](https://github.com/user-attachments/assets/48c2b360-26a5-407b-985e-99a5cd121016)

Solution: If the user looking at the workspace chat is themselves, refer to them as **you**. 

So the text will be: 
> This is where **you** will submit expenses to [Danrvidal+test111912@gmail.com](mailto:Danrvidal+test111912@gmail.com)’s Workspace. Just use the + button.

All other users will still see the same thing. 

<details><summary>Issue Owner</summary>Current Issue Owner: @danielrvidal</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update workspace chats beginning of chat history to reference "You" rather than your email

### What is the root cause of that problem?
We always display the owner display name of policy expense chat

https://github.com/Expensify/App/blob/410d4cefe3b58d59a6ec068d11e79875767fe738/src/libs/SidebarUtils.ts#L551

https://github.com/Expensify/App/blob/410d4cefe3b58d59a6ec068d11e79875767fe738/src/components/ReportWelcomeText.tsx#L115
### What changes do you think we should make in order to solve the problem?
Display as `you` if the owner accountID is the current user

```
report?.ownerAccountID === currentUserAccountID ? Localize.translateLocal('common.you') : ReportUtils.getDisplayNameForParticipant(report?.ownerAccountID)
```

https://github.com/Expensify/App/blob/410d4cefe3b58d59a6ec068d11e79875767fe738/src/libs/SidebarUtils.ts#L551

```
report?.ownerAccountID === currentUserAccountID ? translate('common.you') : ReportUtils.getDisplayNameForParticipant(report?.ownerAccountID)
```
https://github.com/Expensify/App/blob/410d4cefe3b58d59a6ec068d11e79875767fe738/src/components/ReportWelcomeText.tsx#L115
### What alternative solutions did you explore? (Optional)

**Comment by danielrvidal** [comment]
Sorry team, I'm going to put this on hold. We're still having some discussion that came in after I put this up.

**Comment by danielrvidal** [comment]
We're still discussing internally in this thread for our own reference: https://expensify.slack.com/archives/C07HPDRELLD/p1732561681389569?thread_ts=1732068639.488019&cid=C07HPDRELLD

**Comment by danielrvidal** [comment]
Closing this one for now given the conversation. Sorry for the confusion.
