### ISSUE TITLE
[HOLD for payment 2024-12-12] [$250] Support-Logged-In Agents Can Appear to Delete Workspaces in NewDot Without Actual Deletion or Error Message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction(No access to supportal)
**Reproducible in production?:** Needs Reproduction(No access to supportal)
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @RachCHopkins 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1732045916838179)

## Action Performed:
1. Login in to a newdot account as support agent
2. Delete a workspace

## Expected Result:
When a support agent attempts to delete a customer's workspace in NewDot while support-logged-in:
1.The UI should display an appropriate error message, similar to OldDot, indicating that the deletion is not allowed.
2.The workspace should remain visible and unchanged in the UI.
3.The UI should not give any misleading indication that the workspace has been successfully deleted.

## Actual Result:
The UI appears to allow the deletion, showing no error message.
Even after refreshing, the workspace seems to be deleted from the NewDot 
Upon returning to the main Supportal page, the workspace is still present, confirming it was not actually deleted.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/2faee817-41d7-4636-ac0a-ba5a26fb96ac

![2024-11-20_08-43-14](https://github.com/user-attachments/assets/3553c25e-dbb8-4db1-ab1e-ac583e24f812)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860949442956139975</li>
        <li>Upwork Job ID: 1860949442956139975</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 105128268</li>
<li>twilight2294 | Contributor | 105128269</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by RachCHopkins** [comment]
@MitchExpensify I'm happy to manage this one, but would you mind confirming that you can repro from your own NewDot supportal?

**Comment by MitchExpensify** [comment]
> @MitchExpensify I'm happy to manage this one, but would you mind confirming that you can repro from your own NewDot supportal?

Confirmed I can reproduce

**Comment by Beamanator** [comment]
I'm happy to manually test myself but I'll also get the adhoc build created for others to test 👍

**Comment by Beamanator** [comment]
Hope?!?! 🤣 🤣

**Comment by Beamanator** [comment]
PR passed QA! 🚀

**Comment by MitchExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
cc on the BZ steps above @allgandalf

**Comment by Beamanator** [comment]
Mmmmm true, I don't think supportal is available for applause so they can't really manually test that, right @MitchExpensify ?

**Comment by MitchExpensify** [comment]
That is true; I'm not sure how, or if, QA tests any Supportal centric bugs today. Maybe @mallenexpensify can help give us a bit of guidance on the BZ steps here 🙏

**Comment by RachCHopkins** [comment]
@Beamanator is it cool if I pay people even without this figured out?

**Comment by mallenexpensify** [comment]
Contributor: @twilight2294 paid $250 via Upwork
Contributor+: @allgandalf paid $250 via Upwork

Didn't wanna hold up payments over the weekend.  

Let's leave this open through next week to see if we can figure out how we want to address Supportal issues (which... maybe we can just kick the can down the road til we see if we have many? I really don't know, kinda spitballing late on a Friday)

**Comment by Beamanator** [comment]
Thanks for paying out! Hmm yeah good call, maybe we can bring this up to the main people responsible for implementing supportal in NewDot recently?

**Comment by RachCHopkins** [comment]
All paid out, waiting on QA steps.

**Comment by RachCHopkins** [comment]
Still waiting on QA steps.

**Comment by Beamanator** [comment]
Just to be clear, we're not waiting on me, right? 😅

**Comment by mallenexpensify** [comment]
I'm unsure of what QA steps would/should be for supportal related issues.  Also unsure of who would/should come up with those.    If we don't view the steps as a near-term priority, we can likely close this.... right?

**Comment by Beamanator** [comment]
Trueeee if QA doesn't actually test supportal stuff, it doesn't really make sense to need QA steps, does it? 🤣

**Comment by mallenexpensify** [comment]
Did a quick search in the #qa Slack room and didn't see much about Supportal, so I'm going to close for now.  Comment/reopen if needed.
