### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Tags - State filed is not auto populated.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: upload dependent tags in old dot as admin

[Dependent.-.Multi.Level.tags.NEW.1.csv](https://github.com/user-attachments/files/17844150/Dependent.-.Multi.Level.tags.NEW.1.csv)

1. Go to https://staging.new.expensify.com/
2. Login as employee
3. Open employee workspace chat
4. Tap plus icon - create expense
5. Enter an amount and tap next

## Expected Result:
State field must be auto populated.

## Actual Result:
State filed is not auto populated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/914046c6-8bc8-4fb5-8091-7e45b133c5e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859625825867558770</li>
        <li>Upwork Job ID: 1859625825867558770</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 105029640</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
State filed is not auto populated.

### What is the root cause of that problem?
The transaction and transactionDraft are getting from `useOnyx`. The data can be not available at the first render in `IOURequestStepConfirmation`


https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/iou/request/step/withFullTransactionOrNotFound.tsx#L57-L58

It leads `transaction` prop is `undefined` at the first time `IOURequestStepConfirmation` is rendered
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L642

And this `useEffect` call `setMoneyRequestTag` with `transactionID` is `-1` [here](https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/components/MoneyRequestConfirmationList.tsx#L206)
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/components/MoneyRequestConfirmationList.tsx#L696-L697
### What changes do you think we should make in order to solve the problem?
We have some options to resolve this bug
1. Introduce `transactionID` prop in  `MoneyRequestConfirmationList` and pass `transactionID={transactionID}` from `IOURequestStepConfirmation` to `MoneyRequestConfirmationList` and remove this [line](https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/components/MoneyRequestConfirmationList.tsx#L206). We used `transactionID` from route param in `IOURequestStepConfirmation` so I think it makes sense if we also use this in `IOURequestStepConfirmation`

https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L642

2. In this HOC, return the loading screen if the onyx value is loading. Or we can pass isLoadingTransactionValue prop from `withFullTransactionOrNotFound` to the component. And we can pass this to `MoneyRequestConfirmationList` through `IOURequestStepConfirmation`

https://github.com/Expensify/App/blob/3611198a932189628b23128f9f6888e200605298/src/pages/iou/request/step/withFullTransactionOrNotFound.tsx#L47

Then we can return early in this useEffect if `isLoadingTransactionValue` is `true` and run this again after `isLoadingTransactionValue` is changed to `false`
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/components/MoneyRequestConfirmationList.tsx#L696-L697

We should do the same for the auto-populated category
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
I'm not sure I see the bug here. Why must the state be auto populated? is this coming from a regression test? cc @garrettmknight

**Comment by mkzie2** [comment]
@s77rt If you reload the confirmation page, you can see it's auto-populated. It should be populated if the tag is required and the `enabledTags` has only one

**Comment by s77rt** [comment]
@mkzie2 Thanks for the proposal. Your RCA makes sense but for fixing this I think we should fix the `useEffect` dependencies as the easiest solution.  There is already a comment that we shouldn't add `transaction` as it will cause the selection multiple times but we can add `transactionID`. Please test and let me know if that would work.

**Comment by mkzie2** [comment]
> There is already a comment that we shouldn't add transaction as it will cause the selection multiple times but we can add transactionID

@s77rt I just tested this solution and it works well.

**Comment by s77rt** [comment]
@mkzie2 Thank you! Let's go with that.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/52879#issuecomment-2491714854)

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/41152#discussion_r1864956976

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    Bug requires regression test: No, I think this is coming from testrail already but couldn't find the exact steps, found [C2778098](https://expensify.testrail.io/index.php?/cases/view/2778098) and [C2990390](https://expensify.testrail.io/index.php?/cases/view/2990390) 

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @mkzie2 $250 paid via upwork
- Contributor+: @s77rt $250 via upwork


@s77rt go ahead and request when you're ready.

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
