### ISSUE TITLE
[$250] mWeb - Expensify Classic - Survey page is not shown while switching to expensify classic

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52352
**Issue reported by:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login expensifail account
3. Tap settings - switch to expensify classic
4. Tap take me to expensify classic

## Expected Result:
Survey page must be shown while switching to expensify classic.

## Actual Result:
Tapping take me to expensify expensify classic user briefly taken to settings page before navigating to expensify classic. Then survey page is not shown while switching to expensify classic.

Note : Before you go page is displayed only for new unvalidated gmail account and it is missing on all other accounts.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2817225c-f252-4cb8-8f7d-6096c8b54f03

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859991189955688630</li>
        <li>Upwork Job ID: 1859991189955688630</li>
        <li>Last Price Increase: 2024-11-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

I think after https://github.com/Expensify/App/pull/52526. This is the expected behavior. Survey page should only show for accounts that were redirected from OD to ND before.

But I see one problem here is this:

> Tapping take me to Expensify classic user briefly taken to settings page before navigating to Expensify classic.

### What is the root cause of that problem?

It's due to the order of executions here:

https://github.com/Expensify/App/blob/1fb29896f8cae754e19e1bd2481c7fa4c78f7396/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L89-L93

`dismissModal` is called before `openOldDotLink`.

### What changes do you think we should make in order to solve the problem?


We should move `openOldDotLink` before `dismissModal`.
