### ISSUE TITLE
[HOLD for payment 2024-12-07] [HOLD for payment 2024-12-05] [HOLD for payment 2024-12-03] [$250] [CRITICAL] Multiple workspaces get created when someone either refreshes the page, or drops off and returns later. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:**Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation** : [#convert thread](https://expensify.slack.com/archives/C07HPDRELLD/p1732191134903139?thread_ts=1732114307.465849&cid=C07HPDRELLD)

## Action Performed:
1. Sign-up on expensify.com
2. Choose the “1-9” option on the home page (signUpQualifier: vsb)
3. Get redirected to new.expensify.com
4. Observe a workspace is created
5. Don’t complete the onboarding modal steps (hasCompletedGuidedSetupFlow: false)
6. Refresh the page
7. Observe another workspace is created
8. Type in [expensify.com](http://expensify.com/) in the browser URL and click enter
9. Get redirected to [new.expensify.com](http://new.expensify.com/) (classicRedirect.dismissed: false)
10. Another workspace is created

## Expected Result:
If we’ve created a workspace for the new sign-up already, don’t create another one when they refresh or return. 

## Actual Result:
We create a workspace every time they refresh or get redirected to NewDot and haven’t completed the onboarding modal steps yet.

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

**Refreshing the page**

https://github.com/user-attachments/assets/2587d4c0-7191-4ab6-847b-960ca1c30785

**Returning to expensify.com**

https://github.com/user-attachments/assets/9525a801-2360-46d3-b663-512c919403da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859580489556912069</li>
        <li>Upwork Job ID: 1859580489556912069</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 105120851</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mountiny** [comment]
@nkdengineer This is coming from your PR here https://github.com/Expensify/App/pull/51839/files

We should not be creating the workspace on each mount forever. Only if there is no **group** policy the user is admin of yet

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multiple workspaces get created when someone either refreshes the page, or drops off and returns later.

### What is the root cause of that problem?
We are already returning early in case there is onboarding policy id set but on refresh the useOnyx will not make the data available and the effect runs too early 
https://github.com/Expensify/App/blob/2d2555b173b47c0bce0b1c16b275f1f98639664c/src/pages/OnboardingAccounting/BaseOnboardingAccounting.tsx#L61-L62
### What changes do you think we should make in order to solve the problem?

We should first check that onBoarding Policy ID data is loaded not loading
https://github.com/Expensify/App/blob/2d2555b173b47c0bce0b1c16b275f1f98639664c/src/pages/OnboardingAccounting/BaseOnboardingAccounting.tsx#L48
```
    const [onboardingPolicyID, onboardingPolicyIDResults] = useOnyx(ONYXKEYS.ONBOARDING_POLICY_ID);

```
```
if (!isVsb || !!onboardingPolicyID || isLoadingOnyxValue(onboardingPolicyIDResults)) {
            return;
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
@jayeshmangwani I see the offending PR is just on the fence of the 1 week regression period and it was paid out. I think its fair if you will review this PR as part of regression still. Let us know if that sounds fine with you

@FitseTLT I think your solution makes sense, you also need to add the `isLoading` to the useEffect dependency but sounds good.

**Comment by FitseTLT** [comment]
> @jayeshmangwani I see the offending PR is just on the fence of the 1 week regression period and it was paid out. I think its fair if you will review this PR as part of regression still. Let us know if that sounds fine with you
> 
> @FitseTLT I think your solution makes sense, you also need to add the `isLoading` to the useEffect dependency but sounds good.

Yep I only missed it when commenting the proposal 👍

**Comment by myspace20** [comment]
@trjExpensify I requested to become a contributor through email, but I have not received feedback for a few days. Is there another way to do this?

**Comment by jayeshmangwani** [comment]
> @jayeshmangwani I see the offending PR is just on the fence of the 1 week regression period and it was paid out. I think its fair if you will review this PR as part of regression still. Let us know if that sounds fine with you

Yes, I am definitely fine with it. We missed the case during testing

**Comment by jayeshmangwani** [comment]
@mountiny, @FitseTLT 's [Suggestion](https://github.com/Expensify/App/issues/52894#issuecomment-2491045711) looks good to me here. Should I raise a PR quickly, or will @FitseTLT do it?

**Comment by FitseTLT** [comment]
@jayeshmangwani I am already preparing 👍

**Comment by jayeshmangwani** [comment]
Cool, please do it

**Comment by myspace20** [comment]
Contributor details
Your Expensify account email: rogersatsi98@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016c50704f37520a88

**Comment by nkdengineer** [comment]
> We should not be creating the workspace on each mount forever. Only if there is no group policy the user is admin of yet

I already did it but missed the refresh case. The reason is `useOnyx` return the `onboardingPolicyID` is `undefined` at the first time if we don't have cache data.

**Comment by FitseTLT** [comment]
[PR](https://github.com/Expensify/App/pull/52899) ready for review 👍

**Comment by trjExpensify** [comment]
Yep, sounds good!

**Comment by trjExpensify** [comment]
Slack access is still restricted, you will be notified when that's resolved, but there's no timeline I can give you on it. 

Regardless, gaining access to Slack isn't a requirement to start putting proposals forward on issues labelled `Help wanted`. Have you looked at the issues available as I mentioned [here](https://github.com/Expensify/App/issues/52894#issuecomment-2491136642).

**Comment by myspace20** [comment]
@trjExpensify Thanks I will do just that.

**Comment by jayeshmangwani** [comment]
I am finishing the checklist now. Also, @trjExpensify there is no payment due for me here, as the issue was coming from the PR where I was the C+

**Comment by jayeshmangwani** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/51839#issuecomment-2520096398

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

**For the regression test, I would say the testing steps will be sufficient here.**

### Regression Test Proposal

1. Sign up on `expensify.com`.
2. Choose the “1-9” option on the home page (signUpQualifier: vsb).
3. Get redirected to new.expensify.com.
4. Observe that a workspace is created.
5. Do not complete the onboarding modal steps (hasCompletedGuidedSetupFlow: false).
6. Refresh the page on web or close and re-open the app on native.
7. Verify that another workspace is not created.

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment]
> I am finishing the checklist now. Also, @trjExpensify there is no payment due for me here, as the issue was coming from the PR where I was the C+

Ah okay, so just payment to @ishpaul777 and @FitseTLT. Is that correct?

**Comment by jayeshmangwani** [comment]
> Is that correct?

Yes

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @ishpaul777 for the C+ review (can you [accept the offer](https://www.upwork.com/nx/wm/offer/105120851), please!
- $250 to @FitseTLT for the fix (offer sent!)

**Comment by FitseTLT** [comment]
@trjExpensify accepted

**Comment by trjExpensify** [comment]
Paid you!

**Comment by trjExpensify** [comment]
> Thanks! Accepted offer!

Paid, closing!
