### ISSUE TITLE
[HOLD for payment 2024-12-05] [Company cards] Handle company cars page reloading when changing feeds

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52909]
When changing the feed in the list or when closing the feed settings, the company card list is showing spinner incorrectly https://expensify.slack.com/archives/C06ML6X0W9L/p1732197668569719?thread_ts=1732108983.281759&cid=C06ML6X0W9L

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by joekaufmanexpensify** [comment]
@mountiny we already have https://github.com/Expensify/App/issues/52818#issuecomment-2488546640 , which is the same, no?

**Comment by waterim** [comment]
Hey, Im Artem from Callstack and would like to help with this one

**Comment by waterim** [comment]
@mountiny @joekaufmanexpensify 
The reason why we have a loader in the company cards and we dont have in expensify cards is here:
1. This is ExpensifyCards:  `const isLoading = !isOffline && (!cardSettings || (cardSettings.isLoading && !cardsList));`
And here (cardSettings.isLoading && !cardsList) this part will always return **false**, even when **cardSettings.isLoading is true,** because when **cardsList** is empty, it will return empty Object: "{}", thats why true && false returns false all the time(imo doesnt make any sense), it means that this full expression will be always false when property **cardSettings** exists.
2. In CompanyCards we had the same behaviour previously`const isLoading = !cardFeeds || !!(cardFeeds.isLoading && !companyCards);`
But after this [discussion](https://github.com/Expensify/App/pull/51360/files#r1840763693) we decided that it doesn't make sense to do this check for company cards as it will always return **false** as in the **expensifyCardsPage** (and it makes sense), but in this situation it makes sense also to remove this check in ExpensifyCards too, but in this situation it will add loader to expensifyCards too or just to cut off those expressions and isLoading will look like this: 
CompanyCards: `const isLoading = !isOffline && !cardFeeds`
ExpensifyCards:  `const isLoading = !isOffline && !cardSettings`

**Comment by joekaufmanexpensify** [comment]
Got it. Does that mean we will change this for company cards further, or leave as is?

**Comment by mountiny** [comment]
Lets try this and see how it feels `const isLoading = !isOffline && !cardFeeds`
