### ISSUE TITLE
[HOLD for payment 2024-12-05] Cleanup GTM errors

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#52922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C05F77PJ91V/p1732209099852979?thread_ts=1729526299.202909&cid=C05F77PJ91V

## Action Performed:

1. Sign into https://new.expensify.com/
2. View logs and network requests

## Expected Result:
No errors related to thirdPartyScripts or GTM

## Actual Result:
Following errors get logged

```
Refused to execute script from 'https://new.expensify.com/r/thirdPartyScripts.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

```
CSP error for analytics.google.com
```
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/4a9138ba-ae70-47eb-a976-275bbd59c229)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by arosiclair** [comment]
The path for [thirdPartyScripts.js](https://github.com/Expensify/App/blob/main/web/thirdPartyScripts.js) resolved incorrectly if you loaded NewDot on a report page like r/123456 (resolved to https://new.expensify.com/r/thirdPartyScripts.js). We're fixing that in the PR.

The CSP issue is for the [Google Tag Manager Preview Mode](https://developers.google.com/tag-platform/security/guides/csp#preview_mode) so won't be reproducible outside of that. I'll update our CSP to allow it.

**Comment by arosiclair** [comment]
Not done yet

**Comment by johncschuster** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @allroundexperts due $250 via NewDot

**Comment by johncschuster** [comment]
@allroundexperts does this require any sort of regression test?

**Comment by allroundexperts** [comment]
I don't think so.

**Comment by johncschuster** [comment]
Great! In that case, we're good to close this one out. Please go ahead and request payment in ND. Thank you!

[Payment Summary](https://github.com/Expensify/App/issues/52922#issuecomment-2517649106)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
