### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] BUG: "Members" section of #admins room doesn't have room name near the top like other rooms

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52933]
## Details
Coming from [this convo](https://expensify.slack.com/archives/C03TME82F/p1732145463282739), I noticed that when you go into any #admins room and click into the `Members` section, near the top it doesn't show the room name:

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/920ac329-cb3a-4283-b95a-40645359e2f7">

In any other room, it does:

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/40d5713e-f320-4010-913e-2300afc1fed4">

cc @Expensify/design 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859707716941961146</li>
        <li>Upwork Job ID: 1859707716941961146</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 105068916</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BUG: "Members" section of #admins room doesn't have room name near the top like other rooms

### What is the root cause of that problem?
We haven't given the report name as subtitle to HeaderWithBackButton
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/ReportParticipantsPage.tsx#L368

### What changes do you think we should make in order to solve the problem?

We can give the report name as the subtitle for default rooms
```
                    subtitle={ReportUtils.isDefaultRoom(report) ? ReportUtils.getReportName(report) : undefined}
```
### What alternative solutions did you explore? (Optional)
We can optionally apply it to admin rooms only if we want

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BUG: "Members" section of #admins room doesn't have room name near the top like other rooms

### What is the root cause of that problem?
We haven't given the report name as subtitle to HeaderWithBackButton
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/ReportParticipantsPage.tsx#L368

### What changes do you think we should make in order to solve the problem?

We can give the report name as the subtitle for default rooms
```
                    subtitle={ReportUtils.isDefaultRoom(report) ? ReportUtils.getReportName(report) : undefined}
```
### What alternative solutions did you explore? (Optional)
We can optionally apply it to `isAdminRoom` only if we want (or even isAnnounceRoom)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-21 21:15:47 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BUG: "Members" section of #admins room doesn't have room name near the top like other rooms

### What is the root cause of that problem?
We haven't given the report name as subtitle to HeaderWithBackButton
https://github.com/Expensify/App/blob/e9e18573960d492a29b2563237024f0dc3c37f85/src/pages/ReportParticipantsPage.tsx#L368

### What changes do you think we should make in order to solve the problem?

We can give the report name as the subtitle for default rooms
```
                    subtitle={ReportUtils.isDefaultRoom(report) ? StringUtils.lineBreaksToSpaces(ReportUtils.getReportName(report)) : undefined}
```

### What alternative solutions did you explore? (Optional)
We can optionally apply it to `isAdminRoom` only if we want (or even isAnnounceRoom) or may be isGroupChat case too but for other case as iou reports expense reports etc... we surely don't want to show the names

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Members" section of #admins room doesn't have room name near the top like other rooms

### What is the root cause of that problem?
For the chat room, the member page is in `RoomMembersPage` and we have a `subtitle` in the header is the room name here 

https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/pages/RoomMembersPage.tsx#L356

For other reports, the member page is in `ReportParticipantsPage` and we don't pass `subtitle` prop to `HeaderWithBackButton` then no report name section is displayed

https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/pages/ReportParticipantsPage.tsx#L367
### What changes do you think we should make in order to solve the problem?
The default room exists for all workspaces so I think we can display the subtitle with the workspace name, it's more useful for the user to know 

1. We can get the additional detail like [here](https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/pages/ReportDetailsPage.tsx#L277) and because we only want to display it for the default room of the workspace, we can only get the case `in ${chatRoomSubtitle}`
```
const chatRoomSubtitle = useMemo(() => ReportUtils.getChatRoomSubtitle(report), [report, policy]);
const additionalRoomDetails = `${translate('threads.in')} ${chatRoomSubtitle}`;

```

2. Pass `subtitle` prop here
```
subtitle={ReportUtils.isDefaultRoom(report) ? `${StringUtils.lineBreaksToSpaces(ReportUtils.getReportName(report))} ${additionalRoomDetails}` : ''}
```
https://github.com/Expensify/App/blob/686b8b45ca606453e4b8a5f11e2a16e75dd0b15d/src/pages/ReportParticipantsPage.tsx#L367

Optional: We can do the same for the chat room member page in `RoomMembersPage`
### What alternative solutions did you explore? (Optional)

We can apply the main solution for only special reports that we want like admin, announce.

Or we can also apply the main solution for other reports like group chat, ... but we will only display the report name in this case

### Result

<img width="1512" alt="Screenshot 2024-11-22 at 12 06 45" src="https://github.com/user-attachments/assets/13ed95f6-29d8-423f-9e3e-10aee4732ab2">

**Comment by mkzie2** [comment]
@dubielzyk-expensify What do you think about my result above?

**Comment by shawnborton** [comment]
That looks pretty good to me 👍 I think the idea is here we want to be consistent and apply it everywhere, not just certain rooms.

**Comment by jamesdeanexpensify** [comment]
If it follows the pattern of all the other rooms, I think it would exclude the workspace name, right?

**Comment by FitseTLT** [comment]
> If it follows the pattern of all the other rooms, I think it would exclude the workspace name, right?

Yes

**Comment by dannymcclain** [comment]
>I think whatever we do, we should try to be consistent. So I think I would opt to just just show the name of the room as it would be shown in the LHN

Same. I'm down to start with showing it exactly as it shows in the LHN. And if we find that that's not enough, we can adjust further.

**Comment by FitseTLT** [comment]
@jamesdeanexpensify @shawnborton please check out the result the reviewer has shown above. I think there is a misunderstanding the purpose of the original OP was to make default rooms consistent with other user created policy rooms. Wasn't it? not for all iou reports and so on.

**Comment by dubielzyk-expensify** [comment]
Agree with the people above. I'm not sure I'd bring it to IOUs, but other than that the above looks good to me. Happy to lean on what others think here if we also think we should have it on IOUs. I don't think it's a big deal if we do, then at least it's consistent across the board

**Comment by shawnborton** [comment]
Yeah, I think I lean on just always using it everywhere for the sake of consistency. I don't feel strongly though, but I think I would lean that direction instead of making exceptions for certain room types.

**Comment by OfstadC** [comment]
@dukenv0307 Please complete checklist before payment date. Thank you 😃

**Comment by OfstadC** [comment]
## Payment Summary

- @Krishna2323 [paid](https://www.upwork.com/nx/wm/workroom/39083820/overview)  $250 via Upwork 
- @dukenv0307 due $250 via manual NewDot Request

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
