### ISSUE TITLE
[$250] Rooms - Room name can be changed by non admin users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Let User A Create a new room where User B is a member
2. Using User B click on the room avatar on top
3. Go to settings
4. Click on room names
5. Change the name and click the save button

## Expected Result:
Non-admin users can't change room names

## Actual Result:
Non-admin users can change room names

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/24f954fc-0918-46b3-befd-981dfe349394

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860022450051722625</li>
        <li>Upwork Job ID: 1860022450051722625</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rooms - Room name can be changed by non admin users

### What is the root cause of that problem?
We are not disabling non-admins in user created policy rooms here
https://github.com/Expensify/App/blob/2b312769d1bb8b621b30a11be26fddcbd4b9c738/src/libs/ReportUtils.ts#L7328-L7338
### What changes do you think we should make in order to solve the problem?

We should add
```
function shouldDisableRename(report: OnyxEntry<Report>): boolean {
    if (isUserCreatedPolicyRoom(report)) {
        const isAdmin = isPolicyAdmin(report?.policyID);
        return !isAdmin;
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/52965#issuecomment-2494059217) to add same fix for group chat too although the current issue is related to rooms only 👍

**Comment by zanyrenney** [comment]
adding @allgandalf please review the proposal above.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Non-admin users can change room names

### What is the root cause of that problem?
We do not disable the other users (except the creator of the room) to rename the created room

https://github.com/Expensify/App/blob/2b312769d1bb8b621b30a11be26fddcbd4b9c738/src/libs/ReportUtils.ts#L7328-L7338
### What changes do you think we should make in order to solve the problem?
The admin user here isn't the admin of the policy, this is the creator of the room.

So for the user-created room, we should return false if the user isn't the admin of the room. We can use `isGroupChatAdmin` function to do that

We should add a case after this [line](https://github.com/Expensify/App/blob/2b312769d1bb8b621b30a11be26fddcbd4b9c738/src/libs/ReportUtils.ts#L7343). 

```
if (isUserCreatedPolicyRoom(report)) {
    return !isGroupChatAdmin(report, currentUserAccountID);
}
```

> Note: We should not add the check inside the first condition because some reports like expense report still can rename and this report doesn't have role in participant.

We can do the same for the group chat report if we want only the group chat admin to rename it.

Optional: We can also rename `isGroupChatAdmin` function because this can also check for the created policy room.
### What alternative solutions did you explore? (Optional)

**Comment by Mrkhd** [comment]
### Proposal
### Problem Statement
Non-admin users can currently modify room names in workspaces, which violates our permission hierarchy and workspace management principles.
### Root Cause
The RoomNamePage component lacks proper permission validation, allowing any user to:
Access the room name edit page
Submit room name changes through the form
Bypass intended workspace admin controls
### Solution
Implement proper permission checks at both UI and submission layers, ensuring only workspace admins can modify room names.
### 1. New Permission Utility
Created dedicated permission utilities in RoomPermissionUtils.ts:
typescript

```
export function canModifyRoomSettings(report: OnyxEntry<Report>, policies: OnyxCollection<Policy>): boolean {
    if (!report || !policies) {
        return false;
    }
    const policyID = report.policyID;
    if (!policyID) {
        return false;
    }
    return ReportUtils.isPolicyAdmin(policyID, policies);
}

export function shouldDisableRoomNameChange(report: OnyxEntry<Report>, policies: OnyxCollection<Policy>): boolean {
    if (!report) {
        return true;
    }
    if (ReportUtils.isDefaultRoom(report)) {
        return true;
    }
    return !canRenameRoom(report, policies);
}
```
### 2. UI Permission Gate
Added permission check in RoomNamePage.tsx to prevent unauthorized access:
typescript

```
<FullPageNotFoundView shouldShow={shouldDisableRoomNameChange(report, reports)}>
    <HeaderWithBackButton
        title={translate('newRoomPage.roomName')}
        onBackButtonPress={goBack}
    />
    {/* ... */}
</FullPageNotFoundView>
```
### 3. Submit Handler Protection
Added validation in form submission to prevent API calls from unauthorized users:
typescript

```
const submit = useCallback(
    (values: FormOnyxValues<typeof ONYXKEYS.FORMS.ROOM_NAME_FORM>) => {
        if (!report || report.isPolicyUpdating || shouldDisableRoomNameChange(report, reports)) {
            return;
        }
        ReportActions.updatePolicyRoomName(report, values.roomName.trim());
        Navigation.goBack();
    },
    [report, reports],
);

```

**Comment by Mrkhd** [comment]
Contributor details
Your Expensify account email: khdstudy@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e24df757c99d5875

**Comment by FitseTLT** [comment]
@allgandalf If it helps you, to save your time wasted on analysing time edit histories, there is a more important point that my proposal only contains that is :
We need to make the check in `shouldDisableRename` because we also want to show not found page in room name page here if the user is not an admin
https://github.com/Expensify/App/blob/2b312769d1bb8b621b30a11be26fddcbd4b9c738/src/pages/settings/Report/RoomNamePage.tsx#L95
👍

**Comment by zanyrenney** [comment]
@allgandalf can you re-review and let us know which proposal to move ahead with now please?

**Comment by mkzie2** [comment]
@allgandalf I don't think the selected proposal is the correct behavior for the user-created room. For example:

1. User A is the admin and invites user B as a member
2. User B creates the room in user A's workspace
3. In this case, the member of this room is only member B by default. And the user can edit the room name should be user B not user A. If we do the selected proposal, user B can't edit the room name although he is the creator of the room and is the only member of the room.

**Comment by FitseTLT** [comment]
@allgandalf FYI On the above [case](https://github.com/Expensify/App/issues/52965#issuecomment-2511037747) we can handle it as an edge case (where the creator of a room is not an admin) and give a fallback of isGroupChatAdmin, i.e.
```
function shouldDisableRename(report: OnyxEntry<Report>): boolean {
    if (isUserCreatedPolicyRoom(report)) {
        const isAdmin = isPolicyAdmin(report?.policyID, allPolicies);
        return !isAdmin && !isGroupChatAdmin(report, currentUserAccountID);
    }
```
Having `!isGroupChatAdmin` alone like suggested by the contributor BTW will allow only creator of a room to edit the room name because the `report.participants` will only be populated with role admin for the creator of the room. For instance, if a room is created by a non-admin of a policy and admin is invited to the room, participants list of the room will look like
```
"participants": {
            "16368738": {// creator of the room which is a non-admin member of a workspace
                  "notificationPreference": "daily",
                  "role": "admin"
            },
            "18489726": {// admin of the policy
                  "notificationPreference": "daily"
            }
      },
```
the policy admin's role is not populated in `participants` list at all 👍

**Comment by rafecolton** [comment]
Are we sure this is a bug? It not immediately obvious to me what the behavior _should_ be, and clearly from the discussion there are edge cases. I kinda think this warrants a bigger discussion on room permissions, but I'm also not sure if it's worth solving right now (or if perhaps we've already made the decision somewhere). @zanyrenney what do you think?

**Comment by zanyrenney** [comment]
@rafecolton just catching up on this one!

**Comment by zanyrenney** [comment]
> Are we sure this is a bug? It not immediately obvious to me what the behavior should be, and clearly from the discussion there are edge cases. I kinda think this warrants a bigger discussion on room permissions, but I'm also not sure if it's worth solving right now (or if perhaps we've already made the decision somewhere). @zanyrenney what do you think? 

I believe the variety of proposals, each offering different solutions shows the point made by Rafe above is kind of true. I don’t think this is a core issue that needs immediate attention, so I will consider this closed for now. We can reopen it later when we decide to focus more on the chat or group feature.

**Comment by FitseTLT** [comment]
@zanyrenney @rafecolton @allgandalf Duplicate issue is created [here](https://github.com/Expensify/App/issues/59585) if we have any decision changes let's reopen this and proceed we already had an accepted proposal and was only waiting for my assignment Thx

**Comment by rafecolton** [comment]
Thanks, closed the other issue
