### ISSUE TITLE
[$500] "Receipt scan incomplete" error message when attaching a receipt to an existing expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation** (hyperlinked to channel name): [Expensify - quality](https://expensify.slack.com/archives/C05LX9D6E07/p1732307224213329)

## Action Performed:
1. Create an expense (cash expense or card expense) without a receipt
2. Add a receipt to the expense
## Expected Result:
Receipt is smartscanned and added to the expense without error message
## Actual Result:
"Receipt scan incomplete. Please verify details manually." error message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![Snip - (5) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/5de900e5-eca0-4031-af74-bf28eea209fb)

![2024-11-21_15-00-52](https://github.com/user-attachments/assets/9fe54583-7dc2-4288-9c4c-f1f00a22924a)

![2024-11-21_15-00-32](https://github.com/user-attachments/assets/f2fba9b0-e2cd-46ef-aa11-837fbb937810)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860100249643089842</li>
        <li>Upwork Job ID: 1860100249643089842</li>
        <li>Last Price Increase: 2024-11-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by mallenexpensify** [comment]
@jamesdeanexpensify can you provide more details?
1. Was the expense created via the big green, floating action button or by click `+` in a chat in a workspace chat?
2. When creating the expense, did you add $15 first, then add the receipt after?

**Comment by jamesdeanexpensify** [comment]
Oh, that screenshot at the top wasn't me. In my case:

1. I had a card transaction that already existed in my account
2. I clicked into it and then clicked into the receipt placeholder image
3. I clicked the overflow menu (three vertical dots) in the upper-right corner
4. I clicked "Replace"
5. And then I uploaded the receipt
6. Shortly after, I saw the error message

**Comment by jamesdeanexpensify** [comment]
I'm going to recreate this scenario in an hour or so because I have a reliable repro. I'll record it when I do. It's based off a charge that Jon will make to my Expensify Card after he runs a usability test (happening in 15 mins, lasts an hour), which is how I noticed it in the first place.

**Comment by mallenexpensify** [comment]
I was able to reproduce, I think my steps were

1. Click FAB > Create Expense > enter amount > select workspace > add merchant name > submit
2. Click on the newly created expense > click receipt > click ⛰️ icon to upload image > select file
3. Wait for 10 seconds then refresh page
4. Observe `Receipt scan incomplete. Please verify details manually.` error. 

@jamesdeanexpensify , for the expected behaviour, what data were you expecting to be added or updated from the receipt?   

@nkuoch , you got accidentally removed so I added you back

**Comment by jamesdeanexpensify** [comment]
Hmm...I guess I was just expecting that when I added the image, it would kick off the SmartScan process. But from what I gathered from [this thread](https://expensify.slack.com/archives/C07CACYRTJS/p1732230351085569), it doesn't even do that.

**Comment by mallenexpensify** [comment]
Unsure if this can be external but added the label (and made price $500) in case it can.  @jayeshmangwani , can you attempt reproduction and provide feedback?

**Comment by jamesdeanexpensify** [comment]
Does this help? Jon didn't end up having his usability test so I just bought some Starbucks on my Expensify Card: 

https://github.com/user-attachments/assets/015afd1d-e99b-4a4d-9d05-bd6690a3de90

**Comment by jayeshmangwani** [comment]
@mallenexpensify, I was able to reproduce this issue. The cause of the warning is that, upon refreshing, we are calling `OpenReport`, which is returning `receiptNotSmartScanned` violations for this specific report.

We may assign the internal engineer to investigate why the backend is returning an error for this report.
<details>
  <summary>Response:</summary>
  
  
  ```js
 {
    "onyxMethod": "mergecollection",
    "key": "transactionViolations_",
    "value": {
        "transactionViolations_5457231590312282407": [
            {
                "type": "warning",
                "name": "duplicatedTransaction",
                "data": {
                    "tooltip": "List the potential duplicate transactions and merge, delete, or ignore them.",
                    "duplicates": [
                        "146784852880515781"
                    ]
                },
                "showInReview": true
            },
            {
                "type": "notice",
                "name": "receiptNotSmartScanned",
                "data": null,
                "showInReview": true
            }
        ],
        "transactionViolations_146784852880515781": [
            {
                "type": "warning",
                "name": "duplicatedTransaction",
                "data": {
                    "tooltip": "List the potential duplicate transactions and merge, delete, or ignore them.",
                    "duplicates": [
                        "5457231590312282407"
                    ]
                },
                "showInReview": true
            },
            {
                "type": "notice",
                "name": "receiptNotSmartScanned",
                "data": null,
                "showInReview": true
            }
        ]
    }
}
  ```
</details>

**Comment by Mrkhd** [comment]
**### Proposal**
**### Problem Statement**
When adding a receipt to an existing expense (cash or card expense), users encounter an error message "Receipt scan incomplete. Please verify details manually" even though they just started the receipt scanning process.

**### Root Cause Analysis**
The hasMissingSmartscanFields function in TransactionUtils/index.ts performs validation checks too early in the receipt scanning workflow. Specifically:

When a receipt is first added to an expense, it enters the SCANREADY state
The function immediately checks for missing required fields through areRequiredFieldsEmpty
Since the receipt scanning hasn't completed yet, required fields are naturally empty
This triggers the validation error prematurely
Proposed Solution
Modify the hasMissingSmartscanFields function to skip validation when a receipt is in the SCANREADY state:

```
function hasMissingSmartscanFields(transaction: OnyxInputOrEntry<Transaction>): boolean {
    // Skip validation for receipts that were just added (in SCANREADY state)
    if (transaction?.receipt?.state === CONST.RECEIPT_STATE.SCANREADY) {
        return false;
    }
    return !!(transaction && !isDistanceRequest(transaction) && !isReceiptBeingScanned(transaction) && areRequiredFieldsEmpty(transaction));
}

```
### **This change will:**

First check the receipt's state
If it's SCANREADY (just added), bypass validation
Only perform validation checks after the initial scan completes
Maintain proper validation for completed scans
Impact
Users won't see premature validation errors when adding receipts
The scanning process will feel more natural and less error-prone
Proper validation still occurs after scanning completes
No negative impact on existing validation logic for completed scans

**Comment by Mrkhd** [comment]
@MelvinBot check proposal

**Comment by jayeshmangwani** [comment]
Thanks for the proposal @Mrkhd , but don’t you think that instead of preventing the error message from being shown on the frontend in `hasMissingSmartscanFields`,  we should fix the backend to avoid sending the `receiptNotSmartScanned ` violation in the first place?

**Comment by Mrkhd** [comment]
sorry @jayeshmangwani , you are right, after analyzing the code once again, i have got another solutin.

I've designed a new approach to handle receipt scanning that solves the validation timing issues we've been seeing. The core idea is to treat receipt scanning as a proper state machine, where each receipt moves through well-defined states during its lifecycle.

When a user first uploads a receipt, it starts in a PENDING state. This is just a temporary state while we prepare the receipt for scanning. Once ready, it moves to SCANREADY - this is where we know we have a valid image that's ready to be processed. During the actual scanning process, it moves to SCANNING state, and this is where we prevent any validation from happening. This solves our original problem of premature validation during the scanning process.

After scanning completes, the receipt moves to either SCANCOMPLETE or SCANFAILED. Only in these final states do we allow validation to occur. This means we won't get those annoying "receiptNotSmartScanned" violations while the receipt is still being processed.

The really nice thing about this approach is that it's impossible for validation to happen at the wrong time - the state machine simply won't allow it. Each state transition is explicitly defined and validated, so we can't accidentally end up in a weird state where validation happens too early.

I've also added metadata tracking to each receipt - things like how many times we've attempted to scan it and when the last scan happened. This will be super helpful for debugging issues and understanding what's happening when things go wrong.

The implementation is pretty straightforward - we've got a singleton ReceiptStateManager that handles all state transitions and validation checks. When you want to validate a receipt, instead of directly checking fields, you first ask the state manager "hey, should I validate this receipt?" It checks the current state and only gives you the green light if the receipt is in a final state.

This is much more robust than our previous approach where we were just checking if the receipt was in SCANREADY state. Now we have a complete picture of where each receipt is in its lifecycle, and we can make smart decisions about validation timing.

What's cool is that this also sets us up for better error handling and retry logic. If a scan fails, we can easily move the receipt back to SCANREADY state and try again, all while maintaining a clear history of what's happened.

**Comment by klajdipaja** [comment]
I looked at this a little bit too and I agree with @jayeshmangwani.
It seems like for some reason the backend is not running the smart scanning even though it's the same invoice. The transaction that we get on openReport when the expense is created has a SCANCOMPLETED state on the receipt but after I change the receipt it now has OPEN as state. 
 
In `replaceReceipt` API command we are not sending the state of the receipt which for money request we set as `SCANREADY`. Could that have anything to do with it?

**Comment by mallenexpensify** [comment]
@nkuoch 👀 please on @jayeshmangwani [post above](https://github.com/Expensify/App/issues/52983#issuecomment-2495378606)

**Comment by nkuoch** [comment]
cc @rlinoz and @pecanoro as seems like https://github.com/Expensify/Auth/pull/12012 was missing some logic?

**Comment by rlinoz** [comment]
I think we are still using PHP to calcualte violations, aren't we? https://github.com/Expensify/Web-Expensify/blob/c0a6fa72f2f654565aba443cef52bc317a77decb/lib/ReportUtils.php#L898

**Comment by pecanoro** [comment]
Yeah, violations are coming from PHP still

**Comment by nkuoch** [comment]
Ok, so coming from https://expensify.slack.com/archives/C05LX9D6E07/p1732307224213329, the bug is actually:

> Attaching a receipt to an existing expense in New Expensify doesn't trigger SmartScan Everywhere

Looking...

**Comment by mallenexpensify** [comment]
Yes @nkuoch , sorry, I should have summarized that for you before
