### ISSUE TITLE
Replace receipt - Scan feature does not work after replacing a receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5255733
**Email or phone of affected tester (no customers):** aatweq+1901@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the URL: https://staging.new.expensify.com/
2. Loggin
3. Go to a WS
4. Click on the compose box '+' button inside the chat.
5. Submit a scan expense
6. Wait until the scan is finished
7. Click on the thumbnail of the receipt
8. Click on the tree dots at top right corner
9. Replace the receipt to one with clear and valid data

## Expected Result:
After the receipt is replaced, the scan feature should work replacing: Amount, Merchant, and so on.

## Actual Result:
When the receipt is replaced, the scanning feature does not work and an error message is displayed.
Error Message - "Receipt scan incomplete. Please verify details manually:"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ca99b764-da4f-4091-a6e9-7f9ba183808f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
As I am reviewing this, I see that the tester purposely selected a receipt that was "blurry/incomplete" based on the file name. 

However, once they uploaded that receipt, they manually entered the total amount. When you upload another receipt, it is not going to SmartScan properly because you'e manually entered the total and now what you've entered does not match what is on the new receipt. And even if it does, it is going to focus on the manual override instead, which is why it is asking you to continue manually entering details. 

This is not a bug, but as the system is designed 👍
