### ISSUE TITLE
Workspaces - The user automatically becomes an approver after being re-invited to the workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5257074&group_by=cases:section_id&group_order=asc&group_id=229065
**Issue reported by:** Applause Internal Team

## Action Performed:
Workspace has an approver set up that is not the admin of the workspace.
1. Navigate to http://staging.new.expensify.com/
2. As the workspace admin, navigate to members
3. Click on the member that is the approver
4. Click on Remove
5. Navigate to the workflows, verify the approver is deleted.
6. Navigate to members
7. Invite the same user
8. Navigate to workflows

## Expected Result:
After re-inviting the user who was an approver, the admin must set up the approver again.

## Actual Result:
After removing an approver and then re-inviting that user, the user automatically becomes an approver.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/392cc0ba-a88f-49e9-96ee-810b068f4e23

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
### Problem
When `user B` is set as the `submitsTo `(approver) for` user A `and is subsequently removed from the workspace, the `submitsTo` relationship of `user A `is not updated to reflect this change. This means that **user A's** `submitsTo` field still references` user B`, even though `user B` no longer exists in the workspace.

When `user B` is re-invited to the workspace, the app recognizes the existing `submitsTo` relationship for `user A `and reassigns `user B `as the `approver` automatically. This occurs because we don't clear or update the `submitsTo` field of user A when an approver is deleted.

### Proposed Solution:

When a member (e.g., user B) is deleted from the workspace, the BE should automatically remove or nullify any relationships that reference the deleted member. Specifically:

If the deleted member is set as `submitsTo` (approver) for other users (e.g., user A), the submitsTo field for those users should be cleared or set to null to prevent stale or invalid relationships.

**Comment by me-ZaidAli** [comment]
This is a backend issue since `fowardedTo` property for parent approver isn't updated when the child member is deleted.

**Comment by stephanieelliott** [comment]
This seems like it is working as intended now? There is an error message that prevents you from removing someone who is set as an approver -- you must remove them from the workflow first. As you are forced to manually remove them from the workspace, they are not set as approver again once re-invited. 

I think we don't need to do anything here

https://github.com/user-attachments/assets/18edbdbe-9225-48d6-8a51-3eafa4f5d8d2
