### ISSUE TITLE
[HOLD for payment 2024-12-05] [HOLD for payment 2024-12-03]  "You don't have the permission to take the requested action" when opening public room thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause Internal Team
 

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a public room.
3. Send a message to the public room.
4. Right click on the message > Reply in thread.
5. Send a reply.
6. Return to the main chat.
7. Copy the link to the public room.
8. Navigate to the link anonymously (logged out).
9. Click FAB.
10. Click on the tour link (important).
11. Return to the public room (still anonymous).
12. Click on the reply to open the thread.

## Expected Result:
The thread will open without error message.

## Actual Result:
"You don't have the permission to take the requested action" appears briefly when opening public room thread anonymously.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6674874_1732462751747!Screenshot_2024-11-24_at_23 36 32" src="https://github.com/user-attachments/assets/e952b93b-3cf7-4c78-81d0-1789a2c83749">

https://github.com/user-attachments/assets/b57128e7-80c0-446f-be6a-761c5115942b

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by RachCHopkins** [comment]
Can repro - exactly as described.

**Comment by mountiny** [comment]
Assigning @c3024 as the author of the offending PR, @daledah if your solution is used, we are going to pay you $50 for your help 🙌

**Comment by mountiny** [comment]
Fix being CPed

**Comment by mountiny** [comment]
$50 to @daledah once done as their solution was used

**Comment by RachCHopkins** [comment]
[Offer](https://www.upwork.com/nx/wm/offer/105087260) sent to you @daledah !

**Comment by RachCHopkins** [comment]
@c3024 can you complete the checklist please?

**Comment by c3024** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: Author of the original PR authored the fix PR too.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No discussion was started because this is too specific a case and could not be identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again. 

No regression test is proposed because this was identified during staging.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
