### ISSUE TITLE
Android - Workspace - Workspaces list opened in background when navigating to WS share link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5256782&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):**  ibellicotest+36@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Workspaces" and open any workspace from the list.
4. Tap on "Profile" and select "Share"
5. Tap on "Copy URL"
6. Return to "Inbox" and open any chat.
7. Paste the workspaces URL on compose box and send it.
8. Tap on the sent URL.
9. Verify that you are redirected to the workspace details page
10. Tap on the arrow on the top left corner.
11. Verify you are navigated to chat again and not to workspaces list page.

## Expected Result:
When navigating to a workspace URL, and navigating back, the user should return to chat instead of landing on workspaces list page.

## Actual Result:
When navigating to a workspace URL, workspaces list tab is opened on the background, and the user lands on it, instead of returning to chat when tapping on the back button.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e72aed00-bb8c-421c-a76f-fec0bc958f96

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspaces list opened in background when navigating to WS share link

### What is the root cause of that problem?

We did not set `backTo` for `WorkspaceInitialPage` when opening a workspace share link. 
Therefore, clicking the back arrow will call `Navigation.dismissModal()` to show the workspace list on mobile or the settings page on the web.

https://github.com/Expensify/App/blob/367cdfb828666656352e34bae3a6ef53b16f5571/src/pages/workspace/WorkspaceInitialPage.tsx#L398-L405

https://github.com/user-attachments/assets/f801e8d1-cce0-4338-865a-750441888f72

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we must set `backTo` when opening a workspace share link. For example:

1. We need to update the [`openLink`](https://github.com/Expensify/App/blob/ccd097261b73830514a44a657238b5ffb1d5ff36/src/libs/actions/Link.ts#L183) function. We should check if `internalNewExpensifyPath` is a workspace share link, then pass the `backTo` parameter to minimize impact, as `openLink` is used in many places.

https://github.com/Expensify/App/blob/ccd097261b73830514a44a657238b5ffb1d5ff36/src/libs/actions/Link.ts#L183

```diff
// add new
+     function isWorkspaceShareLink(path) {
+       const pattern = /^settings\/workspaces\/[^/]+\/join$/;
+       return pattern.test(path);
+     }

//src/libs/actions/Link.ts#L182
+        const pathWithoutQuery = internalNewExpensifyPath.split('?').at(0);

+        if (isWorkspaceShareLink(pathWithoutQuery ?? '')) {
+            Navigation.navigate(`${internalNewExpensifyPath}&backTo=${Navigation.getActiveRoute()}` as Route);
+            return;
+        }
```

2. We need to update `WorkspaceJoinUserPage` to add `backTo` when navigating to `WORKSPACE_INITIAL`

https://github.com/Expensify/App/blob/c3c7c7ac2c7d844463536c403064b58051add579/src/pages/workspace/WorkspaceJoinUserPage.tsx#L49

```diff
//src/pages/workspace/WorkspaceJoinUserPage.tsx#L33
+       const backTo = route?.params?.backTo;

//src/pages/workspace/WorkspaceJoinUserPage.tsx#L49
        if (!isEmptyObject(policy) && !policy?.isJoinRequestPending && !PolicyUtils.isPendingDeletePolicy(policy)) {
            Navigation.isNavigationReady().then(() => {
                Navigation.goBack(undefined, false, true);
-                Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID ?? '-1'));
+                Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID ?? '-1', backTo));
            });
            return;
        }
```

We will see the workspace list when we backTo from WORKSPACE_INITIAL. This is another issue I have found and will fix if needed, and I will address it in the pull request.

Note: If we have the same case, we can reuse that solution.

## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:53044-test-branch?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/9d1ec2de-963d-4afd-94b8-f915d04ebdde

</details>

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
This is intentional. We are intentionally putting the workspace list page under the stack because we want the user to be navigated to the workspace list page on pressing back for small screens.

**Comment by JmillsExpensify** [comment]
Agreed.
