### ISSUE TITLE
[HOLD for payment 2024-12-25] [HOLD for payment 2024-12-19] Import & Export Onyx state reliability issues

### ISSUE THREAD

**Issue by TMisiukiewicz** [Expensify/App#53060]
Exporting and importing Onyx state features are highly valuable in scenarios such as:
- Troubleshooting bugs caused by inconsistencies in the local Onyx state, which can lead to unexpected errors or unexpected UI behavior
- Measuring and improving performance on accounts experiencing significant slowdowns, as it allows developers to reproduce and analyze performance bottlenecks in a controlled environment.

However, there is significant room for improvement in both features to maximize their potential and ensure reliability. The current issues include the following:

### Export

- Masking export data currently does not include multiple sensitive fields, such as last message, phone number or address
- Every email address and message is replaced with ***. While this ensures data anonymity, it also makes it difficult to analyze and reproduce bugs related to participants-related features and possibly impacts reliability when measuring performance, as the simplified masking fails to simulate realistic data structures or payload sizes

### Import
- Missing items in key UI elements, such as LHN and Search option lists, which results in broken or incomplete user experience
- Imported states often show inconsistnt option titles compared to original state
- Certain expenses are missing which impacts testing expenses workflows
- When splitting expense on 1:1 chat, the original account is displayed as third participant 
- Navigating back to the original state from an opened report screen often triggers errors

All these issues collectively affect the reliability of the export and import features, reducing their effectiveness for debugging and performance optimization tasks. Addressing these problems is crucial for ensuring their value in real-world scenarios.

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by TMisiukiewicz** [comment]
While recording videos with a fix for proper displaying LHN elements I noticed the Import is broken on iOS. I'll focus on fixing this one first before I open any other PR since it blocks testing on the platform entirely
![image](https://github.com/user-attachments/assets/b4dcea40-0dcc-41d3-88e1-a5e11815448c)

**Comment by TMisiukiewicz** [comment]
Found a solution for above error. The `react-native-fs` library is not maintained anymore for more than 2 years now, and it is expecting `NSInteger` pointer for both `position` and `length` parameters of `read` function. According to the [React Native docs](https://reactnative.dev/docs/0.74/native-modules-ios#argument-types), using `NSInteger` should be avoided. 

So we have a couple of options:
1. Patch the library and switch from using `NSInteger` to `NSNumber`
2. Replace the library with it's fork, https://github.com/birdofpreyru/react-native-fs, which is actively maintained and supports new architecture
3. Use `react-native-blob-util` filesystem that we already have in the codebase. It supports reading files as stream, so i think it should work as well.

From my perspective, the fastest way to unblock us with improvements of the Import feature is using a patch. However the last one sounds reasonable as well. Which one should we follow? We can always go with a patch first as it's a quick one (and I already have it working) and rewrite it to `readStream` in the future

**Comment by mountiny** [comment]
If we already use react-native-blob-util in the app and it can be used here too without issues and its maintained, then lets use that instead of patching the unmaintained library.

**Comment by jjcoffee** [comment]
@Gonals Could you assign me here and add the `Bug` label to get a BZ assigned for future payment? Thanks :pray:

**Comment by eh2077** [comment]
Same here, I helped review this PR https://github.com/Expensify/App/pull/53527

**Comment by TMisiukiewicz** [comment]
just FYI there might be another PRs for that in the future linked to this issue - since we already have a couple of fixes merged, I'll do another round of testing if there are still any troubles when using it.

**Comment by RachCHopkins** [comment]
@Gonals does @eh2077 need to be added here per this [comment](https://github.com/Expensify/App/issues/53060#issuecomment-2550856539)?

@jjcoffee can you complete the checklist please?

**Comment by mollfpr** [comment]
👋 I also help reviewed https://github.com/Expensify/App/pull/53559

**Comment by jjcoffee** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by jjcoffee** [comment]
@RachCHopkins Done! I guess the C+s on other PRs should just post regression tests if needed.

The price should be the standard $250 for each PR as far as I can see.

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @TMisiukiewicz - no payment, contractor
- Contributor: @eh2077 to be paid $250 via NewDot manual request
- Contributor: @mollfpr to be paid $250 via NewDot manual request
- Contributor+: @jjcoffee  to be paid $250 via NewDot manual request

No Upwork job.

@Gonals @jjcoffee, can I get a buddy check on this, please? It's a little confusing.

**Comment by jjcoffee** [comment]
@RachCHopkins There's a 4th PR https://github.com/Expensify/App/pull/53370 that @eVoloshchak reviewed, but otherwise that looks right to me!

**Comment by RachCHopkins** [comment]
Wow, this was a real party!! Updating Payment Summary.

**Comment by RachCHopkins** [comment]
Contributors ready for payment via NewDot, no contracts to complete, no Upwork post to close.

Merry Xmas, Happy Holidays and Best Wishes to everyone involved!

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr

**Comment by garrettmknight** [comment]
$250 approved for @jjcoffee

**Comment by JmillsExpensify** [comment]
$250 approved for @eh2077

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
