### ISSUE TITLE
[HOLD for payment 2024-12-07] Amex direct feeds polish

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#53083]
[Connecting to Amex](https://expensify.slack.com/archives/C06ML6X0W9L/p1732559046759189?thread_ts=1732108983.281759&cid=C06ML6X0W9L) is now working, but there are some quirks we need to iron out. Namely: 

- We aren't auto-closing the RHP after successfully connecting via oAuth (This [also happened with Wells Fargo](https://expensify.slack.com/archives/C06ML6X0W9L/p1732291214123289?thread_ts=1732108983.281759&cid=C06ML6X0W9L), so let's fix it everywhere if we can). 
- The feed name is `undefined cards` (should be `American Express cards`.) 
- Card number field on the card list is incorrectly blank (but appears correctly on the card details page, workspace member profile, and wallet page). 

cc @mountiny @VickyStash 

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by joekaufmanexpensify** [comment]
@VickyStash please comment when you have a sec and I'll assign you

**Comment by ChavdaSachin** [comment]
I would like to work on this issue, and would raise a quick pr if needed.

Thank you.

**Comment by VickyStash** [comment]
Note: The last 4 numbers are displayed now, so the card number issue is not relevant.

![image](https://github.com/user-attachments/assets/2197ad5a-9063-401a-9972-d4f85484d18b)

**Comment by VickyStash** [comment]
I've fixed the `undefined` in the name issue and found the reason for RHP not closing.

**Reason of RHP not closing:**
When the connection is successful, the app tries to set the new connection feed as the last selected one and navigates the user back to the cards list (closes RHP).
https://github.com/Expensify/App/blob/bb4c89d894da6eeb50bc12ef2dd09315ef3a9afb/src/pages/workspace/companyCards/addNew/BankConnection/index.tsx#L76-L81

But as you can see there is a check for the `feedName` - it's actually just feed (ex. `oauth.citibank.com`), and a check for connected bank which relays on the feed value as well.

The thing is the app tries to predict the feed and renavigate user to that feed after successful connection. So for example if user selected `American Express` the app will think that the feed which should be set as selected is `oauth.americanexpressfdx.com`. But it's turned out it also can be `oauth.americanexpressfdx.com 2003` for example. So the checks doesn't work and RHP is not closing.

In the video provided by Joe we see the the new feed turned out to be selected, but it's just because it's the only option, and the app selects first feed if the `lastSelectedFeed` key is empty.

**Possible solution:**
1. After the successful connection navigate to the first related feed. For example if user connecting to `American Express` navigate to the first feed in the list which starts with `oauth.americanexpressfdx.com`. Cons: it can select the wrong one if there are several connections to the same bank.
2. Store the `lastSelectedFeed` onyx key in the BE and return it inside the Onyx data after the successful connection. This way the app shouldn't predict the feed and will know it for sure. But this approach will require more updates. 

@mountiny @allgandalf Please, let me know if you have any other ideas or any thoughts.

**Comment by jjcoffee** [comment]
Coming from #81573 where duplicate feeds caused an infinite spinner in the RHP. Assuming that the feed length will increase on new feed connecting is partially responsible, since the length won't change on the addition of a duplicate feed, but the feed connection technically succeeded.
