### ISSUE TITLE
[HOLD for payment 2024-12-17] [$250]  Business Bank Account -"It's not here" page is displayed after selecting Business Bank Account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#53121]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53064
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: The default currency for individual policy is USD

1. [User B] Submit a money request to user A in USD
2. [User A] Open the chat with user B
3. [User A] Go offline
4. [User A] Press Pay with Expensify and select Business Bank Account

## Expected Result:
The "Connect bank account" page is directly displayed.

## Actual Result:
When the app is offline, the "It's not here" page is displayed briefly after tapping Business Bank Account. Then, the "Connect bank account" page is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2d6cfed9-4dc7-4c77-b4ee-6791a735ffa7

![Bug6676225_1732569623109!It_s_not_here_page_displayed](https://github.com/user-attachments/assets/c268115a-c512-41bd-bb0b-92e43d058fec)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864428005734930557</li>
        <li>Upwork Job ID: 1864428005734930557</li>
        <li>Last Price Increase: 2024-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 105204338</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page shows briefly when select business bank account payment option on a IOU request.

### What is the root cause of that problem?
When we select the business bank account, it will optimistically create a new workspace and open a bank account page for that workspace. The page that was not found is showing because the policy object is still empty.
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L432-L443

It doesn't happen while online because we show a loading animation only when online when the ach data hasn't been loaded yet.
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L423-L430

### What changes do you think we should make in order to solve the problem?

The bank account page is wrapped with `usePolicy` and it passes `isPolicyLoading` as a prop. We can see that it's still loading after we create the new workspace optimistically. So, we can fix this by preventing the not found page from showing if the policy onyx data is still loading. We can put the `isPolicyLoading` prop to the `isLoading` variable here.
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L406

This will prevent the not found page from showing because `isLoading` is true.
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L432-L443

However, this leads to an `errorText` variable to have some value
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L510-L511

which will render an error view.
https://github.com/Expensify/App/blob/0135d4ee1f803622a9ceea894fde62791ceed775/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L513-L526

But it's actually not shown because it switched really fast when the policy data becomes ready. But I think we can be safe by showing a loading indicator when `isPolicyLoading` is true. Something like this.

```
if (isLoadingPolicy) {
    return <FullScreenLoadingIndicator />
}
```

(or just return null?)

**Comment by RachCHopkins** [comment]
Got my hands on an android, will repro on Monday.

**Comment by RachCHopkins** [comment]
Goit my hands on Android, working on installing Hybridapp.

**Comment by bernhardoj** [comment]
@RachCHopkins it's reproducible on non hybrid app too from my testing.

**Comment by RachCHopkins** [comment]
I'm sorry, I simply cannot replicate this - no matter what I do, what settings I use or which device I use, the system forces it to NZD and then doesn't give an in-app payment option.

I'll need to rely on the C+ to confirm they can replicate.

**Comment by ikevin127** [comment]
> it's reproducible on non hybrid app too from my testing.

> I'll need to rely on the C+ to confirm they can replicate.

I confirm, I was able to reproduce on **Android: Native** as well:

https://github.com/user-attachments/assets/0235448f-2e78-4640-8977-487200db3392

##

Already started reviewing the proposal.

**Comment by ikevin127** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/53121#issuecomment-2500340920) looks good to me. I tested the first part where the solution suggests **only** adding `isLoadingPolicy` to `isLoading` and this is not enough as it simply replaces the "It's not here" page with the `errorText` (currency error) page which shows briefly:

<details>
<summary>Android: Native (errorText issue)</summary>

https://github.com/user-attachments/assets/b2196df6-c4f7-42b9-962f-ae94aef6d313

</details>

In order to fix the issue the second part is required:

```ts
if (isLoadingPolicy) {
    return <FullScreenLoadingIndicator />;
}
```

which has to be added above the `if (errorText) {` block in order to display the `FullScreenLoadingIndicator` while `isLoadingPolicy` is `true`. I tested this on all platforms and the loader **will only be visible on native platforms**, in **all other platforms the change won't be noticed** as the behaviour would remain unchanged.

<details>
<summary>Android: Native (fix)</summary>

https://github.com/user-attachments/assets/1dc3c752-87a5-4f92-a60c-d8d47ad46164

</details>

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment]
cc @RachCHopkins for visibility

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @bernhardoj to be paid $250 via NewDot manual request
- Contributor+: @ikevin127 paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021864428005734930557)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
