### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Can't click Pay buttons when the edit composer is focused

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1732595434466649)

## Action Performed:
1. Go to any chat that waiting for you to pay
2. Focus on main composer
3. Click to dropdown button or pay button
4. See that the action happen
5. Click edit any message to display edit composer
6. Click to dropdown button or pay button
## Expected Result:
Click buttons should work normally
## Actual Result:
Can't click buttons when the edit composer is focused
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/9e89cc4c-5462-45e9-a96a-751b8cbb205f

https://github.com/user-attachments/assets/047a025f-792e-4d5e-bbba-fc5f93d03234

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862984432318114296</li>
        <li>Upwork Job ID: 1862984432318114296</li>
        <li>Last Price Increase: 2024-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105207759</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by m-natarajan** [comment]
@DylanDylann discovered this bug while reviewing https://github.com/Expensify/App/pull/51172

**Comment by DylanDylann** [comment]
I have more context with focus input while working on https://github.com/Expensify/App/pull/51172. Could I take over this issue as C+ if it is external

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the pay button does nothing when the edit composer is focused and a keyboard is shown.

### What is the root cause of that problem?
The root cause is the same as this old [issue](https://github.com/Expensify/App/issues/12715). When we press the pay button, the edit composer is blurred which triggers the main composer visibility, moving the view up, so the press event isn't caught by the button.
https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/pages/home/report/ReportActionItemMessageEdit.tsx#L546-L553

### What changes do you think we should make in order to solve the problem?

We have a few options.

First, we can follow the same approach as https://github.com/Expensify/App/issues/12715, that is by adding
```
onMouseDown={e => e.preventDefault()}
```

for the button. However, we need to apply this to all buttons/pressable in the chat list, including the reply text, etc.
<img width="428" alt="image" src="https://github.com/user-attachments/assets/7e2500e8-186c-4f44-abc9-490315874ad2">

The other solution is to delay showing the main composer. 

https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/libs/setShouldShowComposeInputKeyboardAware/index.android.ts#L3

`setShouldShowComposeInputKeyboardAware` for android & iOS, only shows the main composer after the keyboard hide, but web doesn't have the same thing. So, we can apply a 0 timeout for web only.
https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/libs/setShouldShowComposeInputKeyboardAware/index.ts#L4-L6

```
const setShouldShowComposeInputKeyboardAware: SetShouldShowComposeInputKeyboardAware = (shouldShow) => {
    setTimeout(() => {
        Composer.setShouldShowComposeInput(shouldShow);
    }, 0);
};
```

or we can delay it using interaction manager and `requestAnimationFrame`.
https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/pages/home/report/ReportActionItemMessageEdit.tsx#L529-L533

**Comment by adelekennedy** [comment]
@DylanDylann one proposal to review!

**Comment by DylanDylann** [comment]
@bernhardoj Could you explain why your first solution will solve this bug?

**Comment by bernhardoj** [comment]
With the first solution, if we apply the prevent default on many pressable elements, pressing that element won't blur the edit composer, thus the main composer won't show and push the content above. I prefer the other solution though to use 0 timeout. This would make it closer to the native which waits for the keyboard to hide.

**Comment by bernhardoj** [comment]
I think it's just because for edit composer case, the edit composer moves the view instantly, so the mouse up isn't received anymore by the pressable which receives the first mouse down event. The press happens if the element receives both mouse down and up. You can try attaching `onMouseDown` and `onMouseUp` to the element (pay button or any else) and see it only receives the mouse down event.

**Comment by DylanDylann** [comment]
> I think it's just because for edit composer case, the edit composer moves the view instantly, 

I mean that we need to clarify why there are differences between edit composer and main composer

**Comment by DylanDylann** [comment]
The second solution looks fine but I want to make clear RCA to make sure that your fix is correct and doesn't cause any regression

**Comment by bernhardoj** [comment]
> I mean that we need to clarify why there are differences between edit composer and main composer

This is the difference
> When we press the pay button, the edit composer is blurred which triggers the main composer visibility

**Comment by DylanDylann** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/53140#issuecomment-2503057334) looks good to me

🎀 👀 🎀 C+ Reviewed

**Comment by Beamanator** [comment]
Agreed @bernhardoj should be hired 👍 

But of the 3 solutions in the proposal, using another `setTimeout` is my least favorite 🤔  before starting the PR, can y'all consider if `setTimeout` is really the best option? If all 3 solutions are equally valid, i feel like solution 3 would be best, no?

**Comment by bernhardoj** [comment]
I prefer the timeout since it's the simplest one and gets the job done. Also, using the interaction manager + requestAnimationFrame gives a longer delay (the last time I tested).

**Comment by Beamanator** [comment]
Aah that's quite interesting 😅 👍  then as long as we add a comment to explain why we use a `setTimeout`, I say LGTM

**Comment by bernhardoj** [comment]
Great, I'll open the PR tomorrow

**Comment by DylanDylann** [comment]
@Beamanator I had the same consideration as you, but I tried both ways and noticed that using setTimeout gives a better performance. Note that we use setTimeout with 0 millisecond, I believe that it is safe enough

**Comment by bernhardoj** [comment]
PR is ready

cc: @DylanDylann

**Comment by adelekennedy** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
@DylanDylann for the checklist above!

**Comment by adelekennedy** [comment]
Contributor: @bernhardoj paid $250 via NewDot
Contributor+: @DylanDylann owed $250 via Upwork

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
created issue!
