### ISSUE TITLE
[HOLD for payment 2024-12-07] Theme - App reverts to using device theme settings after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53168]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2166@gmail.com

**Issue found when executing PR** https://github.com/Expensify/App/pull/52392
## Action Performed:
1. Sign into the hybrid app
2. Navigate to Settings > preferences > Theme and change the theme to either dark or light
3. Sign out and re login with the same account

## Expected Result:
The theme is preserved

## Actual Result:
Theme setting reverts to using the device settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e630bab8-47fa-4064-8126-4e02c96d9488

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861738020759297056</li>
        <li>Upwork Job ID: 1861738020759297056</li>
        <li>Last Price Increase: 2024-11-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by grgia** [comment]
We store the preference if it's set in an NVP that's device-specific and persists when logging out @trjExpensify

**Comment by grgia** [comment]
<img width="421" alt="image" src="https://github.com/user-attachments/assets/6c28f22d-ac94-452a-8d2b-8167fb8f0809">

**Comment by trjExpensify** [comment]
Oh cool, bug then! Reproducible on both the standalone and HybridApp.

**Comment by grgia** [comment]
For context, it should use the same pattern as `nvp_preferredLocale`

**Comment by grgia** [comment]
I went ahead and pushed a PR to fix this

**Comment by trjExpensify** [comment]
Ah nice, amazing.

**Comment by ikevin127** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment]
cc @trjExpensify payment overdue, for visibility

**Comment by trjExpensify** [comment]
Yeah, sorry man. Unfortunately if it falls on the weekend, I'll likely get to it on Monday.  

Payment summary as follows: 

- $250 to @ikevin127 for the C+ review 

Regression test: https://github.com/Expensify/Expensify/issues/451646

Sent you an offer.

**Comment by ikevin127** [comment]
No worries, offer accepted and thank you!

**Comment by trjExpensify** [comment]
Paid, closing!
