### ISSUE TITLE
[HOLD for payment 2024-12-07] [HOLD for payment 2024-12-05] [$250] Android - Chat - Suggestion list appears above the composer with spacing

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND app.
2. Go to chat.
3. Type @.

## Expected Result:
Suggestion list will appear above the composer without spacing.

## Actual Result:
Suggestion list appears above the composer with spacing.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b767dd2-a275-42c6-abee-cf2ad718e573

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861733583208146885</li>
        <li>Upwork Job ID: 1861733583208146885</li>
        <li>Last Price Increase: 2024-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 105093976</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Suggestion list appears above the composer with spacing.

### What is the root cause of that problem?
The `windowHeight` returns from `useSafeAreaFrame` returns the full height of the device in Android

https://github.com/Expensify/App/blob/c62ab78b34dbc993c241277b4ee525ec6277b471/src/components/AutoCompleteSuggestions/index.tsx#L57

https://github.com/Expensify/App/blob/c62ab78b34dbc993c241277b4ee525ec6277b471/src/hooks/useWindowDimensions/index.native.ts#L10

But `y` which is calculated from `measureInWindow` is the related position from the App height

https://github.com/Expensify/App/blob/c62ab78b34dbc993c241277b4ee525ec6277b471/src/components/AutoCompleteSuggestions/index.tsx#L100

So in Android, this bug occurs
### What changes do you think we should make in order to solve the problem?
We should use the `useWindowDimensions` from `react-native` here.

https://github.com/Expensify/App/blob/c62ab78b34dbc993c241277b4ee525ec6277b471/src/components/AutoCompleteSuggestions/index.tsx#L57

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
PR CPed

**Comment by bfitzexpensify** [comment]
Payment summary:

@jayeshmangwani to be paid $250 through NewDot Manual Requests
@nkdengineer paid via Upwork ✅
