### ISSUE TITLE
[HOLD for payment 2024-12-11] Android - Start chat - Huge spacing between bottom button and offline indicator

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device navigation is buttons instead of swipe gestures.

1. Launch ND or hybrid.
2. Go offline.
3. Open FAB > Start chat.
4. Tap Add to group next to any user.
5. Note that there is huge spacing between Next button and offline indicator.
6. Go to #room.
7. Note that there is huge spacing between Create room button and offline indicator.

## Expected Result:
There should not be huge spacing between bottom button and offline indicator.

## Actual Result:
There is huge spacing between bottom button and offline indicator.

This issue is not reproducible if device navigation uses swipe gestures.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1d76c8a-a479-4c67-a6b6-875caf87a5eb

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kirillzyusko</details>

**Comment by mountiny** [comment]
discussing in the linked thread

**Comment by mountiny** [comment]
PR is in main

**Comment by sakluger** [comment]
@mountiny do you mind linking the PR?

Also, @chrispader, if you would like me to assign you on this GH issue, you'll need to leave a comment. If you don't need to be assigned, then no worries.

**Comment by mountiny** [comment]
ah it was not linked correctly in the PR, here it is https://github.com/Expensify/App/pull/53250

**Comment by kirillzyusko** [comment]
@mountiny has it been fixed by changes from #53250?

**Comment by mountiny** [comment]
Asked QA [here](https://expensify.slack.com/archives/C9YU7BX5M/p1733230736806849?thread_ts=1733229205.242329&cid=C9YU7BX5M)

**Comment by sakluger** [comment]
No payment required, but @kirillzyusko could you please complete the BZ checklist before we close the issue? Thanks!

**Comment by sakluger** [comment]
We can close this issue as soon as @kirillzyusko completes the BZ checklist.

**Comment by mountiny** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:



Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [x] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Agency member

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: The author fixed it

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Login to the App using an account that has a workspace chat.

### Test:

No need for this specific test, its a generic testing
