### ISSUE TITLE
[$250] [HOLD for payment 2024-12-11] Android - Expense - Save button moves up and down when keyboard is open

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):**applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to workspace chat.
3. Tap + > Submit expense > Manual.
4. Enter amount > Next.
5. Tap Merchant.
6. Might have to exit merchant editor and tap Merchant field again to see Save button move when keyboard is open.

## Expected Result:
Save button will not move up and down when the keyboard is open.

## Actual Result:
Save button moves up and down when the keyboard is open.

Similar behavior is seen across the app when keyboard is open and where there is Save or Submit button.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c576183f-5213-4e66-939c-d2e20fcd0b3a

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865866933542877637</li>
        <li>Upwork Job ID: 1865866933542877637</li>
        <li>Last Price Increase: 2024-12-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by kirillzyusko** [comment]
I already mentioned this problem here - https://github.com/Expensify/App/pull/42143#discussion_r1858383050

This is PR that introduced new hook `useSafePaddingBottomStyle` hook, that updates style from JS thread. However new implementation of `KeyboardAvoidingView` is based on reanimated usage (i. e. synchronous style changes depending on keyboard position), but this hook performs updates in JS (which are slower) and because of that we see this two stage update on Android.

We can fix it:
- by making `useSafePaddingBottomStyle` returning an instance of `useAnimatedStyle`;
- or by specifying necessary margin `pb5` as `keyboardVerticalOffset` property in `KeyboardAvoidingView` (this approach is preferable, because we don't need to create many animated views and a single view will control keyboard interpolation).

However it's pretty big changes in both variants and it will take some time to implement (because `useSafePaddingBottomStyle` implicitly gets used in many places already, so we will have to go through each screen and verify that there is no jumps).

@mountiny do you think we can deprioritise this and remove blocker label? It was kind of something expected to see such instant button shifts, and I wanted to handle it in follow up tickets (but again it'll take some time to prepare a PR).

**Comment by mountiny** [comment]
I agree, lets do this properly without rushing. I think its not that major to block deploy, user can use the app fine

**Comment by kadiealexander** [comment]
I have a standing Android <> ios bug swap with @jliexpensify.

**Comment by jliexpensify** [comment]
@mountiny - if @kirillzyusko needs some time to work on this, shall we make this a `weekly`?

**Comment by mountiny** [comment]
I think we can keep it daily so @kirillzyusko can work on this with urgency in the coming days. 

Can you base your changes on this PR, @kirillzyusko please? https://github.com/Expensify/App/pull/53250

**Comment by mountiny** [comment]
PR in main

**Comment by kirillzyusko** [comment]
@mountiny should we change PR title to show that the fix in `main` branch?

**Comment by jliexpensify** [comment]
Payment Summary

- C: @ZhenjaHorbach $250 (to be paid via Upworks)
- C+: @allroundexperts $250 (to be paid via ND)
- @kirillzyusko (Agency)

[Upworks job](https://www.upwork.com/jobs/~021865866933542877637)

Just waiting on the checklist

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:



Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [x] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Agency member

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/42143#discussion_r1858383050

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Login to the App using an account that has a workspace chat.

### Test:


1. Launch NewDot App.
2. Go to workspace chat.
3. Tap + > Submit expense > Manual.
4. Enter amount > Next.
5. Tap Merchant.
6. Exit the merchant editor and tap Merchant field again.

Verify that the save button will not move up and down when the keyboard is open.

Do we agree 👍 or 👎

**Comment by jliexpensify** [comment]
Paid and job closed, @allroundexperts [here is the payment summary.](https://github.com/Expensify/App/issues/53183#issuecomment-2526385391)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
