### ISSUE TITLE
[$250] Expense - Merchant's ‘Duplicate’ error message does not disappear after changing i

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53212]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.67-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** aatweq+10102555@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the URL: https://staging.new.expensify.com/
2. Create a WS
3. Create and submit an expense to the WS with: Amount: 123, Merchant: hhh
4. Repeat step 3
5. Click on 'Search' between Settings & Inbox
6. Find the expense and do a click on it
7. Change the merchant name

## Expected Result:
After changing the merchant's name, the error message below merchant should disappear.

## Actual Result:
After changing the merchant's name, the error message persists. (If you change the amount, the error disappear. However, the error appears below the merchant and it is understood that it is caused by the merchant, not by the amount)

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7dc347fc-3c25-414d-b665-0c811e5e87d6

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861836931662502944</li>
        <li>Upwork Job ID: 1861836931662502944</li>
        <li>Last Price Increase: 2024-11-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After changing the merchant's name, the error message persists. (If you change the amount, the error disappear. However, the error appears below the merchant and it is understood that it is caused by the merchant, not by the amount)

### What is the root cause of that problem?

`duplicatedTransaction` violation is mapping to merchant although the reason is the dup amount

https://github.com/Expensify/App/blob/3541c88fa1f2f9208dda09ab5b478c4342127f3b/src/hooks/useViolations.ts#L21
### What changes do you think we should make in order to solve the problem?
Change this to `amount`

https://github.com/Expensify/App/blob/3541c88fa1f2f9208dda09ab5b478c4342127f3b/src/hooks/useViolations.ts#L21

### What alternative solutions did you explore? (Optional)

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Merchant's ‘Duplicate’ error message does not disappear after changing i

### What is the root cause of that problem?
When calling the `UpdateMoneyRequestMerchant` api, Backend didn't return the correct response if the transaction is not duplicated.
![Screenshot_16](https://github.com/user-attachments/assets/f917c8e7-c963-4929-8be9-853d0a8de555)

### What changes do you think we should make in order to solve the problem?
For solving this on frontend side. we should add the onyxData merge block at the above line of API call in the [`updateMoneyRequestMerchant`](https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/libs/actions/IOU.ts#L3062-L3084) when the transaction is not duplicated.
```
    onyxData.successData?.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transactionID}`,
        value: null,
    });
```
And we should find the duplicated transaction id and set it as null too.

### What alternative solutions did you explore? (Optional)
We can also solve this to send the correct response from Backend.

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by David-0910** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Merchant's ‘Duplicate’ error message does not disappear after changing i
### What is the root cause of that problem?
After changing the merchant name, UpdateMoneyRequestMerchant api doesn't return the correct response.
The duplicatedTransaction violation should depend on the merchant name, but it seems, now backend trigger this violation based on the amount.
### What changes do you think we should make in order to solve the problem?
We should fix the backend logic to consider the merchant name, not the amount.
### What alternative solutions did you explore? (Optional)
I'm not sure when we should show 'Duplicate' warning but if we have to show this on the expenses where both amount and merchant name are the same, then we should fix the current workflow.

**Comment by sobitneupane** [comment]
Thanks for the proposal, everyone.

@nkdengineer, could you please provide more details in your proposal, particularly in the root cause section? The current statement seems to validate your solution but doesn't provide much insight into the actual root cause.

Also, aren't we supposed to show the Duplicate error message only if both the merchant and the amount are the same?

**Comment by nkdengineer** [comment]
@sobitneupane I updated my [proposal](https://github.com/Expensify/App/issues/53212#issuecomment-2503933012) with the detail RCA

**Comment by nkdengineer** [comment]
> Also, aren't we supposed to show the Duplicate error message only if both the merchant and the amount are the same?

Yes, the duplicate error will appear whenever you create another expense with the same amount.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/53212#issuecomment-2503933012), @nkdengineer 


> The duplicate detection only applies to the amount, not to the merchant (we can try when submitting two expenses with the same amount and different merchant and two expenses with the different amount and the same merchant to verify that).

First, I would like confirmation from the internal engineering team:
Do we currently detect two transactions as probable duplicates based solely on having the same amount, regardless of the merchant?

- If this is not expected behavior, I suggest making the necessary changes in the backend.
- If this is expected behavior, let's proceed with @nkdengineer's proposal to display the duplicate message below the amount field instead of the merchant field.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@aldo-expensify Please help to check this [comment](https://github.com/Expensify/App/issues/53212#issuecomment-2517152141) when you have a chance.

**Comment by aldo-expensify** [comment]
Looking at OldDot, it looks like @nkdengineer is correct. In OldDot, we warn about duplicates if the amount is the same, no matter if the merchant is different:

![image](https://github.com/user-attachments/assets/805915e2-df77-4dfe-b23e-bb69e3f19818)

@garrettmknight do you know if this is correct?

**Comment by nkdengineer** [comment]
@garrettmknight Can you check this comment [here](https://github.com/Expensify/App/issues/53212#issuecomment-2529442881)?

**Comment by garrettmknight** [comment]
I thought this was for the updated dupe detection functionality we're working on. My bad - I'll close for now.
