### ISSUE TITLE
[HOLD for payment 2024-12-11] [HOLD App#53229] Accounting - Next button doesn't have bottom margin on intacct setup first page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53221]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2193@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a workspace and enable accounting
2. Navigate to accounting and Tap on connect on Sage Intacct
3. Observe the Next button and tap on next

## Expected Result:
There is a bottom margin for next button

## Actual Result:
There is no bottom margin for next button on the first setup page of Intacct

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cafbfb3f-6a0d-4d04-a71f-285f1bd55489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Accounting - Next button doesn't have bottom margin on intacct setup first page

### What is the root cause of that problem?
We lack the margin bottom here
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/pages/workspace/accounting/intacct/SageIntacctPrerequisitesPage.tsx#L94
### What changes do you think we should make in order to solve the problem?

add
```
                        style={styles.mb4}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Accounting - Next button doesn't have bottom margin on intacct setup first page

### What is the root cause of that problem?
We lack the margin bottom here
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/pages/workspace/accounting/intacct/SageIntacctPrerequisitesPage.tsx#L94
that we gave here
### What changes do you think we should make in order to solve the problem?

we can add any margin as the design team suggests like
```
                        style={styles.mb4}

```
### What alternative solutions did you explore? (Optional)

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/837e4416-333c-41ce-ba41-c281da3e404a

**Comment by mountiny** [comment]
cc @chrispader @kirillzyusko Another bottom margin one

**Comment by aldo-expensify** [comment]
@mountiny 👋 , are you going to handle this? (asking because of the self-assign :) )

**Comment by mountiny** [comment]
Based on the video this is very minor and we wont block deploy on this one.

@kirillzyusko lets still assign you to fix these

**Comment by mountiny** [comment]
Putting this on hold for holistic safearea management

**Comment by mountiny** [comment]
Payments been handled on other issue as there was bunch of issues linked to one PR edge-to-edge, no regression test required as we will notice
