### ISSUE TITLE
[Awaiting checklist] [$125] Web - RHP - Going back closes the RHP Instead of navigating to the confirm page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51630
**Email or phone of affected tester (no customers):** biruknew45+22hdkj@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with new Gmail account
3. Open a DM
4. Press + and choose Pay option
5. Enter any amount in USD and go Next
6. Press Pay with Expensify. A validate page will show
7. (web/desktop) Refresh
8. Go back

## Expected Result:
Going back should navigate us to the confirm page.

## Actual Result:
Going back closes the RHP

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/1dc0b249-8a29-41d8-b412-8656788cadf3

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864112749864088782</li>
        <li>Upwork Job ID: 1864112749864088782</li>
        <li>Last Price Increase: 2024-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105193680</li>
<li>FitseTLT | Contributor | 105193682</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - RHP - Going back closes the RHP Instead of navigating to the confirm page

### What is the root cause of that problem?
We are navigating back without the `backTo`
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/pages/settings/Wallet/VerifyAccountPage.tsx#L53
https://github.com/Expensify/App/blob/64eaf2fdd357bd06008adfb9c0c049e09cd375b9/src/pages/settings/Wallet/VerifyAccountPage.tsx#L81
### What changes do you think we should make in order to solve the problem?

We need to pass the backTo to the `goBack`
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@FitseTLT's proposal looks good to me 

🎀 👀 🎀 C+ Reviewed

**Comment by dangrous** [comment]
Yep that looks good to me!

**Comment by twisterdotcom** [comment]
Payment Summary:

- @FitseTLT paid $125 [here](https://www.upwork.com/nx/wm/offer/105193682) (Contributor)
- @DylanDylann paid $125 [here](https://www.upwork.com/nx/wm/offer/105193680) (Reviewer)
