### ISSUE TITLE
[$250] Search - Search section loads infinitely when opened after logging in

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** ibellicotest+51@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Log in with any Gmail account.
3. When logged in, tap on "Search" on the bottom of the screen.
4. Verify that search section and all the content in it, loads smoothly.

## Expected Result:
Search section and all the content in it, should load smoothly when opened.

## Actual Result:
Search section loads infinitely when opened just after logging in.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0cf5eee6-fa3b-4a31-81c1-b32c71adcd7b
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863519972369952192</li>
        <li>Upwork Job ID: 1863519972369952192</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search section loads infinitely when opened after logging in

### What is the root cause of that problem?

We called the search API with this `jsonQuery`, but the response returned an empty `onyxData` array.
```
jsonQuery: {"type":"expense","status":"all","sortBy":"date","sortOrder":"desc","filters":null,"inputQuery":"type:expense status:all sortBy:date sortOrder:desc","hash":243428839,"recentSearchHash":422547233,"offset":0}
```

The reason for the empty `onyxData` array might be that the backend validated the query as having the wrong format or something similar.

And since `onyxData` is an empty array, `shouldShowLoadingState` always returns `false`, which is why the loading state is not hidden.
https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L222

https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L309

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to do two things:

1. Double-check the JSON query to match the backend's requirements.
2. Handle the case where `onyxData` is an empty array.

https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L308
```diff
//src/components/Search/index.tsx#L308
+    if (searchResults === undefined && !isOffline) {
+        setShouldShowStatusBarLoading(false);

+        return (
+            <View style={[shouldUseNarrowLayout ? styles.searchListContentContainerStyles : styles.mt3, styles.flex1]}>
+                <EmptySearchView type={type} />
+            </View>
+        );
+    }
```

<details>
<summary>POC</summary>

<img width="1512" alt="Screenshot 2024-11-29 at 11 37 23" src="https://github.com/user-attachments/assets/52f85a76-164a-4b0f-9c8b-e7116a3c01dd">

</details>

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
cc @luacmartins @lakchote can you have a look into this?

**Comment by luacmartins** [comment]
@daledah the requestID shared [here](https://github.com/Expensify/App/issues/53285#issuecomment-2506910563) shows no errors for that request. Do you have expense data in that account?

**Comment by akinwale** [comment]
@huult Could you clarify what you mean by "Double-check the JSON query to match the backend's requirements." in your proposed solution?

**Comment by huult** [comment]
@akinwale Yes, I mean we need to check with the backend why this JSON query has returned Onyx with an empty error, and [this](https://github.com/Expensify/App/pull/52938#issuecomment-2513003819) resolved it

**Comment by luacmartins** [comment]
This is entirely internal. So gonna unassign BZ and C+

**Comment by luacmartins** [comment]
This is fixed
