### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] iOS - QAB - "You no longer have access to your previous.." displayed when submit first expense via QAB

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5276423
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: new account was created and verified in Web ND.
1. Open staging.new.expensify iOS mobile app
2. Sign in as a new user with gmail account.
3. Create a workspace.
4. Tap FAB button, select quick action.
5. Select any option to create an expense - manual, scan or distance.
6. For manual expense - enter the amount and tap Next.

## Expected Result:
Expense details page should open with "To" section prefilled with the created workspace.

## Actual Result:
"Choose recipient" page opens with the message "You no longer have access to your previous quick action destination. Pick a new one below" when creating first expense via QAB.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d803c1a2-605e-4b9b-9435-4aa20cfe5998
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863415108693824567</li>
        <li>Upwork Job ID: 1863415108693824567</li>
        <li>Last Price Increase: 2024-12-02</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 105226572</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by mountiny** [comment]
demoting, this is a minor issue and the user can use the app just fine. 

Seems like we are setting the optimistic chat reportID incorrectly in this case

**Comment by lakchote** [comment]
@alitoshmatov can you review the proposal here?

**Comment by lakchote** [comment]
Assigning @allroundexperts since it's been 4 days without any review, to make this issue move forward.

**Comment by allroundexperts** [comment]
@etCoderDysto's [proposal](https://github.com/Expensify/App/issues/53307#issuecomment-2511604587) looks good to me. It has the correct RCA, and applying the fix works as well. 

https://github.com/user-attachments/assets/76841f22-3aed-4cdc-82be-d0ecef6d4a98

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
@etCoderDysto's proposal LGTM.

**Comment by lakchote** [comment]
Not overdue, @etCoderDysto's PR is in draft status.

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/51836/files#r1897456548

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- N/A

### Test:


1. Open the app on iOS mobile
2. Sign in as a new user with gmail account.
3. Create a workspace.
4. Tap FAB button, select quick action.
5. Select `Manual` option and enter the amount and proceed to next step.

Verify that the expense details page should open with "To" section pre-filled with the created workspace.

Do we agree 👍 or 👎

**Comment by jliexpensify** [comment]
Kadie is OOO so I'll jump in and handle the checklist and payment

**Comment by jliexpensify** [comment]
Payment Summary

- C: @etCoderDysto $250 (to be paid via Upworks)
- C+: @allroundexperts $250 (to be paid via ND)

[Upwork job](https://www.upwork.com/jobs/~021863415108693824567)

**Comment by jliexpensify** [comment]
Paid and job closed.

@allroundexperts - [checklist here](https://github.com/Expensify/App/issues/53307#issuecomment-2564966338)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
