### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Web - Chat - Web - "stars" emoji changes to a different one after sending it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Open any 1:1 DM
4. Click inside the composer
5. Type ":star"
6. Select the "stars" emoji
7. Send the message

## Expected Result:
The same emoji should be seen in the composer and in the chat.

## Actual Result:
"stars" emoji changes to a different one after sending it.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ed7c4ca8-3b5c-4a29-8cec-2deb7cfd8e93
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864084924595239388</li>
        <li>Upwork Job ID: 1864084924595239388</li>
        <li>Last Price Increase: 2024-12-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Stars emoji is shown differently between composer and message.

### What is the root cause of that problem?
This issue is becaused the emoji is not rendered with the same font family. For the composer, we use the EXP_NEUE and the font family look like this.
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/styles/index.ts#L2202-L2208

<img width="455" alt="image" src="https://github.com/user-attachments/assets/22e47a02-98ce-4ef0-8d2a-49aa2cdbb8ec">

For the emoji, it's rendered by `react-native-render-html` and we also use the EXP_NEUE, but the font family look like this.
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/styles/index.ts#L235-L238
<img width="245" alt="image" src="https://github.com/user-attachments/assets/eab2d66d-4eb1-410a-bac7-55956b1db5e3">

Notice that it doesn't have any fallback font for the emoji, thus the emoji is rendered differently. This happens becaue `react-native-render-html` only [select the first available font](https://meliorence.github.io/react-native-render-html/docs/content/textual#font-selection).

If we remove the `fontFamily` style from `baseFontStyle`, then the emoji `fontFamily` will have the fallback font for the emoji. That's because we use a custom renderer for the emoji and use our custom Text component which has a defaul font family style.
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/components/EmojiWithTooltip/index.native.tsx#L4-L6
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/components/Text.tsx#L31-L39

But not all textual tag has a custom renderer.

### What changes do you think we should make in order to solve the problem?

Since all emoji is rendered with EmojiRenderer, we can apply the font family manually on that component, specifically updating the `emojiDefaultStyles`.
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/components/HTMLEngineProvider/HTMLRenderers/EmojiRenderer.tsx#L20-L23

https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/styles/utils/emojiDefaultStyles/index.ts#L6-L10
https://github.com/Expensify/App/blob/1a6f48ea0e2139a82d0a96578badbf3f761bcf00/src/styles/utils/emojiDefaultStyles/index.native.ts#L4-L8

```
...FontUtils.fontFamily.platform.EXP_NEUE,
```

**Comment by Christinadobrzyn** [comment]
I'm not able to reproduce this.  @bernhardoj are you still seeing this issue? what 'star' emoji are you choosing? It seems like the emoji in the OP isn't one that is available in my Chrome.... maybe that's the issue? 

https://github.com/user-attachments/assets/0894829b-5851-4ded-a865-c69979a4bd75

**Comment by bernhardoj** [comment]
It's the `:stars:` emoji (the 3rd emoji from your video). It's only reproducible on Windows. The issue happens on the live markdown too if we use some markdown, such as bold, italic, etc.

**Comment by Christinadobrzyn** [comment]
Thanks @bernhardoj - adding external so @sobitneupane can review of your proposal.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/53324#issuecomment-2508857389) @bernhardoj 

Proposal from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment]
@bernhardoj do you think this has the same root? https://github.com/Expensify/App/issues/53546 something we can fix together?

**Comment by bernhardoj** [comment]
I'm pretty sure it's not the same.

**Comment by lakchote** [comment]
@bernhardoj's proposal LGTM.

**Comment by bernhardoj** [comment]
I'll open the PR tomorrow

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by Christinadobrzyn** [comment]
Monitoring PR https://github.com/Expensify/App/pull/53676

**Comment by Christinadobrzyn** [comment]
upcoming payment

Contributor: @sobitneupane paid $250 via NewDot
Contributor+: @bernhardoj owed $250 via NewDot

@bernhardoj do we need a regression test for this?

**Comment by bernhardoj** [comment]
@sobitneupane is the C+

**Comment by Christinadobrzyn** [comment]
@sobitneupane do we need a regression test for this?

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open any chat
2. Click inside the composer.
3. Type ":star".
4. Select the "stars" emoji from the suggestion list.
5. Send the message.
6. Verify that the same "stars" emoji appears in both the composer and the chat after sending.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

**Comment by Christinadobrzyn** [comment]
Regression test - https://github.com/Expensify/Expensify/issues/455048

Payment summary here - https://github.com/Expensify/App/issues/53324#issuecomment-2548845625

@sobitneupane please make sure to request payment in ND. TY!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
