### ISSUE TITLE
[HOLD for payment 2024-12-17] [HOLD for payment 2024-12-16] [$250] [Performance] Use initializer callbacks for useState

### ISSUE THREAD

**Issue by rezkiy37** [Expensify/App#53322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

Inefficient React component re-rendering and `useState` usage.

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

This optimization reduces the render time.

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Pass an initializer callback to the `useState` hook instead of immediately calling functions. This ensures the callback is only executed once during the initial render. There is an issue (https://github.com/Expensify/App/issues/53162) that they only fixed for **BottomTabBar** (https://github.com/callstack-internal/expensify-issues/issues/165). 

As a part of the improvement, we need to integrate an Eslint rule (https://github.com/Expensify/eslint-config-expensify/pull/138) to confirm if we will do it properly.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:** 9.0.68-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @rezkiy37 
**Slack conversation:** N/A

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863577701857268791</li>
        <li>Upwork Job ID: 1863577701857268791</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by rezkiy37** [comment]
I am preparing one more PR (https://github.com/Expensify/App/pull/53568).

**Comment by CortneyOfstad** [comment]
@alitoshmatov can you complete the checklist when you have a moment? No rush as we have some time before Dec. 16 👍

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by CortneyOfstad** [comment]
## Payment Summary

@alitoshmatov — to be paid $250 via NewDot
@rezkiy37 — contracted position

## Regression Test

Checklist indicated no test needed [here](https://github.com/Expensify/App/issues/53322#issuecomment-2546739991)

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
