### ISSUE TITLE
Workspace-On deleting debug report details, workspace chat avatar is shown fall back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition:Enable debug mode
1. Go to https://staging.new.expensify.com/home
2. Go to workspace settings
3. Tap workspace - header - debug
4. Scroll down and tap delete
5. Navigate back to workspace settings
6. Note fall back avatar displayed for workspace
7. Tap on workspace
8. Note directed to hmm not here page
9. Navigate to workspace list page
10. Tap on workspace
11. Now note workspace chat is not displayed with fallback avatar and user id email id displayed instead workspace name
12. Tap on workspace chat
13. Tap back
14. Note workspace name shown correctly now

## Expected Result:
On deleting debug report details, workspace chat avatar is must not be shown fall back and must not be directed to hmm not here page.

## Actual Result:
On deleting debug report details, workspace chat avatar is shown fall back and directed to hmm not here page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/452187e8-cf7d-470e-815d-18ca4a52365b

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting report from debug page, going back will show not found page. Also, the workspace chat in the workspace settings page is shown with fallback avatar.

### What is the root cause of that problem?
When we delete the report, we use `navigateToConciergeChatAndDeleteReport` and pass `shouldPopToTop` (2nd param) as true.
https://github.com/Expensify/App/blob/3cc88f5a83a979c5e588e01065083a3d714e69da/src/pages/Debug/Report/DebugReportPage.tsx#L146-L149

`shouldPopTop` is supposed to pop all items until the top so the user is navigated back to the LHN.
https://github.com/Expensify/App/blob/3cc88f5a83a979c5e588e01065083a3d714e69da/src/libs/Navigation/Navigation.ts#L204-L206

However, in our case, we use this in a right modal navigator ([report details, debug]) and the pop to the top only pops all the screens from the right modal navigator and navigate to the concierge chat. The only screens left on the RHP is the report details page. When we go back from the concierge chat, we arrived at the report details page which the report is already deleted, so the not found page is shown.

For the 2nd issue, since the report is deleted, the fallback avatar is shown and we never hide the information when the report is not defined.
https://github.com/Expensify/App/blob/3cc88f5a83a979c5e588e01065083a3d714e69da/src/pages/workspace/WorkspaceInitialPage.tsx#L449-L462

### What changes do you think we should make in order to solve the problem?

For the navigation issue, we have 2 options. First, we cam dismiss the RHP first before using `navigateToConciergeChatAndDeleteReport` without `shouldPopToTop` so going back from concierge chat will arrived at the workspace initial settings/details page.

```
Navigation.dismissModal();
navigateToConciergeChatAndDeleteReport(reportID, false, true);
```

The 2nd option is to fix the `shouldPopToTop` to perform the action on the root stack.
https://github.com/Expensify/App/blob/3cc88f5a83a979c5e588e01065083a3d714e69da/src/libs/Navigation/Navigation.ts#L212-L214

```
const rootState = navigationRef.getRootState();
navigationRef.current?.dispatch({...StackActions.popToTop(), target: rootState.key});
```

For the 2nd issue, we can prevent rendering the information if the report doesn't exist.
https://github.com/Expensify/App/blob/3cc88f5a83a979c5e588e01065083a3d714e69da/src/pages/workspace/WorkspaceInitialPage.tsx#L449-L462

```
{currentUserPolicyExpenseChat && ...}
```
