### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Web - Workspace - Central pane gets blank after resizing and clicking back icon

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Create a workspace if there is no any
3. Navigate to the account settings and select the workspace
4. Resize the window so the LHN of workspace is no longer visible
5. Click on the back icon
6. Return to full screen

## Expected Result:
Workspace profile is displayed in the central pane

## Actual Result:
The central pane is blank. The same happens with other workspace options e.g. Members, Categories

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/531c9795-807c-4414-93e8-d94daf8cacdd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863651912898483255</li>
        <li>Upwork Job ID: 1863651912898483255</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by vincdargento** [comment]
@[bug assignee] FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by puneetlath** [comment]
Re-sizing doesn't feel like a primary flow that is blocker-worthy to me. Going to demote.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The central pane is blank. The same happens with other workspace options e.g. Members, Categories

### What is the root cause of that problem?

when we resize on a screen that is not large screen width, when going from the list workspace to the detail workspace, the route will be `WORKSPACE_INITIAL`
and when resizing again, the route is still `WORKSPACE_INITIAL` so the right side will not be displayed

### What changes do you think we should make in order to solve the problem?



We can add a `useEffect` in `WorkspaceInitialPage` and add dependency `isLargeScreenWidth`

In case `isLargeScreenWidth = true` but route is still `WORKSPACE_INITIAL` then we will automatically navigate to `WORKSPACE_PROFILE`

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
@ntdiary , 👀 on @nkdengineer 's proposal above plz.  I was able to reproduce, will add to #quality as low.

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Central pane gets blank after resizing and clicking back icon

### What is the root cause of that problem?

When we resize to a mobile screen and click the back arrow button, it navigates from `Workspace_Profile` to `Workspace_Initial` and removes `/profile` from the URL.

https://github.com/user-attachments/assets/032f24fa-212a-46ec-8c19-3052bcfc3892

When we then resize to a desktop screen, we remain on `Workspace_Initial`, which causes this issue to occur.

### What changes do you think we should make in order to solve the problem?

To resolve this issue, when we resize to a desktop screen, we must update the screen from `Workspace_Initial` to `Workspace_Profile`.

We able use that logic to apply for this solution some thing like that:
https://github.com/Expensify/App/blob/3ee8c2528300e46bc9de93b48056589b00353894/src/libs/Navigation/AppNavigator/createCustomFullScreenNavigator/CustomFullScreenRouter.tsx#L54-L55

```diff
//src/pages/workspace/WorkspaceInitialPage.tsx#L159
    const isNarrowLayout = getIsNarrowLayout();
    useEffect(() => {
        if (isNarrowLayout || activeRoute !== SCREENS.WORKSPACE.INITIAL) {
            return;
        }
        Navigation.navigate(ROUTES.WORKSPACE_PROFILE.getRoute(policyID));
         // or
        // Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID));
    }, [activeRoute, isNarrowLayout, policyID]);
```

Note: isNarrowLayout can be used for something like this

We must check that `activeRoute` !== `SCREENS.WORKSPACE.INITIAL` to avoid always redirecting to `Workspace_Profile` when resizing.

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/a2532a4e-7ec2-4c4a-a593-48c78542b1e9

</details>

### What alternative solutions did you explore? (Optional)

**Comment by CyberAndrii** [comment]
For some reason after https://github.com/Expensify/App/pull/49937 this function is no longer getting called on resize

https://github.com/Expensify/App/blob/b067baa8d9b667de480785adb87f2d0f952a7d29/src/libs/Navigation/AppNavigator/createCustomFullScreenNavigator/CustomFullScreenRouter.tsx#L88-L92

It should be triggered by this line

https://github.com/Expensify/App/blob/b067baa8d9b667de480785adb87f2d0f952a7d29/src/libs/Navigation/AppNavigator/useNavigationResetOnLayoutChange.ts#L12

**Comment by FitseTLT** [comment]
Can be related to https://github.com/Expensify/App/issues/53445

**Comment by mallenexpensify** [comment]
Contributor+: @ntdiary owed $250 via NewDot 

> No need, as we have added one automated navigation test.

Not creating a test case. 

Thx!

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
