### ISSUE TITLE
[HOLD for payment 2024-12-25] [$250] Billable-Billable and "members must categorize all expense" on toggle off text color behavior

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open a workspace chat with billable option enabled
3. Try to create a expense
4. Note in confirmation page, all option displayed in different color and billable option in different color
5. Toggle off billable option
6. Note now it matches with other option colors
7. Navigate to workspace settings - category- setti gs
8. Note the "members must categorize all expense" And below category heading text color is different
9. Toggle on/off "members must categorize all expense"
10. Note text color doesn't changes

## Expected Result:
Billable and "members must categorize all expense" on toggle off text color behavior must be consistent.

## Actual Result:
Billable and "members must categorize all expense" on toggle off text color behavior is inconsistent.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/54d5d2f2-5241-45f9-8eb2-d26456f9484f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865173764798215374</li>
        <li>Upwork Job ID: 1865173764798215374</li>
        <li>Last Price Increase: 2024-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 105276675</li>
<li>FitseTLT | Contributor | 105276677</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Billable-Billable and "members must categorize all expense" on toggle off text color behavior

### What is the root cause of that problem?
We are only applying the textSupporting color style when the iouBillable is false 
https://github.com/Expensify/App/blob/64829131fe962681626b4b016140521d05f7fe52/src/components/MoneyRequestConfirmationListFooter.tsx#L532
### What changes do you think we should make in order to solve the problem?

We should always apply the text supporting style unconditionally 
```
                        titleStyle={{color: theme.textSupporting}}

```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by saifelance** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the "Billable" toggle is turned off, the text color changes to match other options.
However, when toggling the "members must categorize all expenses" setting, the text color doesn't change consistently.

### What is the root cause of that problem?

- **Consistent State Handling**: Ensure that the toggle states for both "Billable" and "members must categorize all expenses" 

- **Styles Consistency**:
- For the ToggleSettingOptionRow used in both "Billable" and "members must categorize all expenses," ensure that a consistent style is applied based on whether the toggle is on or off.
- Use the same conditional logic for text color change as applied in the "Billable" toggle for the "members must categorize all expenses" toggle.

The existing logic applies a style change when iouIsBillable is false. You can apply similar logic to the "members must categorize all expenses" toggle.

`src/components/MoneyRequestConfirmationListFooter.tsx
`
```
const membersCategorizeStyle = {
    color: isMembersCategorizeActive ? theme.textPrimary : theme.textSupporting,
};

// Apply this style in the "members must categorize all expenses" section.
<MenuItemWithTopDescription
    key={translate('common.membersMustCategorize')}
    title={translate('common.membersMustCategorize')}
    description={translate('common.membersMustCategorizeDescription')}
    style={[styles.moneyRequestMenuItem, membersCategorizeStyle]} // Apply the consistent style
/>
```

When the "Billable" toggle is switched off, you already apply `titleStyle={!iouIsBillable && {color: theme.textSupporting}}. `Ensure that the style for "members must categorize all expenses" is handled similarly in the style prop based on the toggle state

**Comment by ikevin127** [comment]
From my understanding of the issue here is that while the switch inputs are toggled OFF the `Billable` label should be the same as the `Members must categorize all expenses` label, since toggled ON are the same currently.

> Billable and "members must categorize all expense" on toggle off text color behavior must be consistent.

Since the **Expected result** is a bit vague, I'd want to ask @Expensify/design's take on what consistent should mean in this issues case for both `Billable` and `Members must categorize all expenses` before making a decision on the proposals:

| Billable OFF | Members OFF |
| ------------- | ------------- |
| <img width="404" alt="billable-off" src="https://github.com/user-attachments/assets/e7132277-b81e-4c66-8b1a-cb77271699a9"> | <img width="404" alt="mmcae-off" src="https://github.com/user-attachments/assets/8c194472-98f4-435e-a307-07ffccd02ed0"> |

| Billable ON | Members OFF |
| ------------- | ------------- |
| <img width="403" alt="billable-on" src="https://github.com/user-attachments/assets/fc4ebb16-5962-4d75-be4a-e9b7286a8c81"> | <img width="403" alt="mmcae-on" src="https://github.com/user-attachments/assets/318c1b31-841e-45e5-a1aa-5fe903329f11"> |

| Billable w/ Context | Members w/ Context |
| ------------- | ------------- |
| <img width="250" alt="billable-context" src="https://github.com/user-attachments/assets/cd6e91c7-394c-4e42-8840-b46efa527e4a"> | <img width="250" alt="mmcae-context" src="https://github.com/user-attachments/assets/e3c46475-6981-46e2-a6a2-22e2895e098a"> |

The reason why I want design's take on this is because if we look at the `w/ Context` images we can notice that in both cases the input labels are grey and the values are black but in the `Billable` case the label is grey when OFF and black when ON, while in the `Members` case the switch label is always black even though in both cases  input labels are grey and the values are black.

**Comment by dubielzyk-expensify** [comment]
> From my understanding of the issue here is that while the switch inputs are toggled OFF the Billable label should be the same as the Members must categorize all expenses label (meaning black), since toggled ON are the same currently.

Yeah, we don't fade out the text when the toggle is on, so it should remain black at all times. Nothing changes here from how we do it in the rest of the app 👍 

On the Category Settings, I noticed that part of the top screen stays fixed when you scroll which shouldn't be the case:
![CleanShot 2024-12-09 at 13 57 13@2x](https://github.com/user-attachments/assets/973fd112-79b2-49c3-a93d-5286e657b213)

Keen to hear what rest of  @Expensify/design thinks about this too

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/53460#issuecomment-2514641378) according to the above feedback

**Comment by dannymcclain** [comment]
>Nothing changes here from how we do it in the rest of the app 👍

Agree with Jon—the label for the toggle row should be the same color regardless of on/off state. Here's an example from Preferences:
![CleanShot 2024-12-09 at 08 21 14@2x](https://github.com/user-attachments/assets/2ad13b02-f6b9-4834-bb03-43918ed142fa)

**Comment by shawnborton** [comment]
Yup, agree with all of those comments.

**Comment by ikevin127** [comment]
## Clarifying timeline of events
- first proposal came in, incomplete as it was not addressing the fix in `MoneyRequestView` component
- second proposal came in, pretty much a copy of the first proposal (not adding anything new)
- third proposal came in, a complete proposal in the sense that it was addressing the `MoneyRequestView` component as well, but the issue was that it suggested keeping `theme.textSupporting` and removing the condition instead:

    > To achieve this, we can remove the condition from both places and always apply the `theme.textSupporting` color.
- I came in as a reviewer and requested design team's input in [#53460 (comment)](https://github.com/Expensify/App/issues/53460#issuecomment-2524832575)
- design team clarified the expectations, confirming that we don't want the `theme.textSupporting` (grey / faded) but instead the switch labels should be black (on light theme) and white (on dark theme):

    > don't fade out the text when the toggle is on, so it should remain black at all times
- additionally the design team requested a change regarding the top part of the `WorkspaceCategoriesSettingsPage` which should move with the scroll instead of being fixed (see details in [#53460 (comment)](https://github.com/Expensify/App/issues/53460#issuecomment-2526812336))
- third proposal was updated, the only change being the additional change requested by the design team related to the top part of the `WorkspaceCategoriesSettingsPage` moving with the scroll instead of being fixed
- first proposal was updated, adding the missing part related to `MoneyRequestView` label color:

    > we should not fade out on toggle off so we can remove textSupporting styles

    and added a solution for the additional change requested by the design team related to the top part of the `WorkspaceCategoriesSettingsPage` moving with the scroll instead of being fixed

> [!important]
> The distinction between the **first** and **third** proposal is that the first one mentions that we should **remove** the `theme.textSupporting` styling completely, while the third proposal mentions removing the condition which would keep the `theme.textSupporting` styling (grey) which is not what we want according to the design team's feedback.

**Comment by ikevin127** [comment]
Given the timeline of events detailed in https://github.com/Expensify/App/issues/53460#issuecomment-2530101884, let's go with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/53460#issuecomment-2514641378) as the root cause of our issue was identified correctly and the solution works as expected given all the requirements, including the additional scrolling requirement requested by design team.

🎀👀🎀 C+ reviewed

**Comment by johncschuster** [comment]
@ikevin127 and @FitseTLT, I will be OOO starting December 23 and will be returning January 6th. A handful of folks on the BZ team will be online for a few days in between the 25th and the 1st, but we'll be operating with a skeleton crew. I will be issuing my payments when I return on January 6th. If you would like the payment issued sooner, please post this issue in [#expensify-open-source](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q) and someone on the team will jump in.

Thank you!

**Comment by bfitzexpensify** [comment]
Regression test proposed, payments complete.
