### ISSUE TITLE
[HOLD for payment 2024-12-17] [$250] iOS/Android - Contact method - Contact method not displayed until re-login or cleaning cache

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53481]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5291147
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to Account settings > Profile > Contact methods
3. Select New contact method
4. Enter an email of a new contact method
5. Enter the magic code and tap the Verify button

## Expected Result:
New unverified contact method with GBR is displayed in the table

## Actual Result:
New unverified contact method is not displayed in the table until user re-logs in or clears cache and restarts

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/73b8c741-cc11-44c5-958a-dec26c02c2a5
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864287613376718300</li>
        <li>Upwork Job ID: 1864287613376718300</li>
        <li>Last Price Increase: 2024-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 105248372</li>
<li>mkzie2 | Contributor | 105248373</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/39455658-ab12-4012-afea-10fbcce538ee

**Comment by AndrewGable** [comment]
I'm curious if our site stability issues are causing this, but I will look at recent PRs since I'm not 100% sure this should be broken on staging and not prod.

**Comment by AndrewGable** [comment]
Confirmed cannot reproduce on production

**Comment by AndrewGable** [comment]
Ok I confirmed I cannot reproduce on the version 9.0.66 of production, _however_, I think this actually occurs on 9.0.69 which is production according to the branches. I believe this was introduced because of https://github.com/Expensify/App/pull/49937

I see a diff for the ContactsMethodPage on this PR (and none recently before that), which makes me think this is related. @mountiny and @kirillzyusko @hannojg @chrispader do you mind confirming?

Removing deploy blocker because it's on production.

**Comment by brunovjk** [comment]
I can reproduce:

<details>
<summary>v9.0.71-0 Develop</summary>



https://github.com/user-attachments/assets/f84987ce-f6cf-41f6-b0c6-83aff73634f8


</details>

Looking for proposals.

**Comment by mountiny** [comment]
Seems like this must be either issue with the optimistic data management or issue from the backend returning wrong options

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New unverified contact method is not displayed in the table until user re-logs in or clears cache and restarts

### What is the root cause of that problem?
When the validate code modal is closed, we check if `loginData?.errorFields` and `pendingContactAction?.contactMethod` exist we will clear the contact method. But this check isn't correct


https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L168-L174


- `loginData?.errorFields` can be an empty object

- `pendingContactAction?.contactMethod` isn't cleared in success data when we add a new contact method here. And in native, it's cleared [here](https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L76) after the `onClose` is triggered

https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/libs/actions/User.ts#L442


### What changes do you think we should make in order to solve the problem?
We should update the check for `loginData?.errorFields` with `isEmptyObject`

```
if (!isEmptyObject(loginData?.errorFields) && pendingContactAction?.contactMethod) {
    User.clearContactMethod(pendingContactAction?.contactMethod);
    User.clearUnvalidatedNewContactMethodAction();
}
```
https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L170

Optional:  We can clear `contactMethod` in `successData` here

https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/libs/actions/User.ts#L442

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
Thanks for the proposal, your RCA and solution make sense to me, I tested it and it solves the issue well, with that I believe we can go with @mkzie2's [proposal](https://github.com/Expensify/App/issues/53481#issuecomment-2519666275). Thanks.

🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment]
@mkzie2 what is your eta for the PR?

**Comment by mkzie2** [comment]
I will raise the PR today.

**Comment by mkzie2** [comment]
@brunovjk The [PR](https://github.com/Expensify/App/pull/53742) is ready.

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by muttmuure** [comment]
Paid up
