### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] The error message displayed when attempting to proceed without selecting a bank while adding a feed is unclear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733261842397819)

## Action Performed:
1. Enable company card in workspace
2. Click Add card
3. Without choosing any bank click Next
## Expected Result:
Error message displayed for not selecting bank
## Actual Result:
The error message displayed when attempting to proceed without selecting a bank while adding a feed is unclear. It states: "Please select a bank account before continuing."
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/f91543d4-3c93-4744-a76d-05e3fe0a035a" width="40%" height="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865184188126712540</li>
        <li>Upwork Job ID: 1865184188126712540</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The error message displayed when attempting to proceed without selecting a bank while adding a feed is unclear

### What is the root cause of that problem?

We are defining error message [here](https://github.com/Expensify/App/blob/0eec30d00c131d3f9caacf1de6afd33c83bc351e/src/languages/en.ts#L3313) with the message "Please select a bank account before continuing." and it is not clear because we are not adding a bank account. 

https://github.com/Expensify/App/blob/0eec30d00c131d3f9caacf1de6afd33c83bc351e/src/languages/en.ts#L3313

### What changes do you think we should make in order to solve the problem?


We can change this to "Please select a bank before continuing." or something to make it clearer

https://github.com/Expensify/App/blob/0eec30d00c131d3f9caacf1de6afd33c83bc351e/src/languages/en.ts#L3313


### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

NA
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by alexpensify** [comment]
Payment Summary:

Contributor: @narefyev91 payment handled via vendor 
Contributor+: @dukenv0307 owed $250 via NewDot

@dukenv0307 - On Monday, please submit a payment request in NewDot. 

--- 

## Heads up, I will be offline until Wednesday, December 18, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
