### ISSUE TITLE
[HOLD for payment 2024-12-16] After accessing the Who's your card provider? page from a specific bank, going back brings you to the bank list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733261878166119)

## Action Performed:

1. Enable company card in workspace
2. Click Add card
3. Choose any bank and click Next
4. Choose any feed type and click Next
5. Click the back arrow in the Who's your provider page

## Expected Result:
User should be returned to the specific bank page they had selected previously, maintaining their context and choice.
## Actual Result:
User returned to Who's your bank page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/05b3aa98-73de-4259-b390-520644de367c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by saifelance** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
When navigating back from the "Who’s your provider?" page, the user is returned to the general bank list instead of the specific bank page they had previously selected. This disrupts the user flow by not maintaining the selected bank context.

### What is the root cause of that problem?
The back navigation logic (handleBackButtonPress) resets the navigation step to the general bank list (SELECT_BANK) without preserving the selectedBank context, resulting in a loss of the user's previously selected bank information.

### What changes do you think we should make in order to solve the problem?

1. Update the `handleBackButtonPress` logic to pass the `selectedBank` and any other necessary data to maintain the user context.
2. Modify the `setAddNewCompanyCardStepAndData` function to ensure the selected bank information is preserved when navigating back.
3. Ensure that all navigation states and conditions account for the user's previously selected choices.

[App/src/pages/workspace/companyCards/addNew/CardTypeStep.tsx](https://github.com/Expensify/App/blob/0eec30d00c131d3f9caacf1de6afd33c83bc351e/src/pages/workspace/companyCards/addNew/CardTypeStep.tsx#L91-L93)

```
const handleBackButtonPress = () => {
    CompanyCards.setAddNewCompanyCardStepAndData({
        step: CONST.COMPANY_CARDS.STEP.SELECT_BANK,
        data: {
            ...addNewCard?.data, // Preserve existing data
            selectedBank,       // Retain the selected bank
        },
    });
};
```


### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

1. **Valid Bank Selection**: Verify that navigating back from the "Who’s your provider?" page returns the user to the previously selected bank page.
2. **Invalid Bank Selection**: Test back navigation without selecting a bank to ensure it returns to the bank list with no preselection.
3. **State Retention**: Confirm selectedBank is retained across navigations and back actions.
4. **UI State Validation**: Ensure UI elements linked to selectedBank update correctly during transitions.

### What alternative solutions did you explore? (Optional)

1. **State Management**: Use Redux/Context for global state consistency, though more complex.
2. **URL Navigation**: Add selectedBank to route parameters for persistent state.
3. **Breadcrumb Navigation**: Use breadcrumbs for clearer flow and accurate back navigation.
4. **The chosen approach**—preserving selectedBank—is simpler and fits seamlessly with existing logic.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by slafortune** [comment]
Contributor: @narefyev91 is from an agency-contributor and not due payment
Reviewer: @dukenv0307 owed $250 via NewDot
