### ISSUE TITLE
[$250] Settings - Subscription section is missing for the account with the expired free trial

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53052
**Email or phone of affected tester (no customers):** iuliia537+2011.1@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch staging Hybrid app.
2. Sign in to the account that has the free trial expired and doesn't have a payment card.
3. Open Settings tab.

## Expected Result:
Subscription section is displayed in the Settings tab for the account with the expired free trial.

## Actual Result:
Subscription section is missing in the Settings tab for the account with the expired free trial.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/50fa4938-67bb-4c94-98c7-6e8372f8ea11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864859980276648320</li>
        <li>Upwork Job ID: 1864859980276648320</li>
        <li>Last Price Increase: 2024-12-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subscription section is missing for the account with the expired free trial

### What is the root cause of that problem?

When the user does not own any policies the [`useSubscriptionPlan`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L8C10-L8C29) will automatically return `null` because [`ownerPolicies`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L13) is empty.

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L12-L16

Therefore, the [`subscriptionPlan`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L100) in [`InitialSettingsPage`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx) will `null` and subscription menu item won't be visible.

https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L195-L204

### What changes do you think we should make in order to solve the problem?


Let's create a condition to check if the user's free trial has ended and does not have a payment card added. 

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L15-L16

```
if (isEmptyObject(ownerPolicies)) {
    return SubscriptionUtils.hasUserFreeTrialEnded() && !SubscriptionUtils.doesUserHavePaymentCardAdded();
}
```

Optionally, I believe instead of checking if the user has added a payment, we can also check if the card has errors such as if it is expired.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subscription section is missing for the account with the expired free trial

### What is the root cause of that problem?

When the user does not own any policies the [`useSubscriptionPlan`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L8C10-L8C29) will automatically return `null` because [`ownerPolicies`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L13) is empty.

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L12-L16

Therefore, the [`subscriptionPlan`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L100) in [`InitialSettingsPage`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx) will `null` and subscription menu item won't be visible.

https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L195-L204

### What changes do you think we should make in order to solve the problem?


Let's create a condition to check if the user's free trial has ended and does not have a payment card added. 

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L15-L16

```
if (isEmptyObject(ownerPolicies)) {
    return SubscriptionUtils.hasUserFreeTrialEnded() && !SubscriptionUtils.doesUserHavePaymentCardAdded();
}
```

According to the expected behaviors in different cases, we can also check if the card has errors such as if it is expired or remove the second check.

Unlike checking if the user has added a payment and if the free trial has ended like in the above snippet which is meant specifically to solve this issue.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subscription section is missing for the account with the expired free trial

### What is the root cause of that problem?

When the user does not own any policies the [`useSubscriptionPlan`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L8C10-L8C29) will automatically return `null` because [`ownerPolicies`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L13) is empty.

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L12-L16

Therefore, the [`subscriptionPlan`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L100) in [`InitialSettingsPage`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx) will `null` and subscription menu item won't be visible.

https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L195-L204

### What changes do you think we should make in order to solve the problem?


Let's create a condition to check if the user's free trial has ended and does not have a payment card added. 

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L15-L16

```
if (isEmptyObject(ownerPolicies)) {
    return SubscriptionUtils.hasUserFreeTrialEnded() && !SubscriptionUtils.doesUserHavePaymentCardAdded();
}
```

According to the expected behaviors in different cases, we can also check if the card has errors such as if it is expired or remove the second check.

Unlike checking if the user has added a payment and if the free trial has ended as in the above snippet which is meant specifically to solve this issue.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The subscription section is missing for the account with the expired free trial

### What is the root cause of that problem?

When the user does not own any policies the [`useSubscriptionPlan`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L8C10-L8C29) will automatically return `null` because [`ownerPolicies`](https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L13) is empty.

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L12-L16

Therefore, the [`subscriptionPlan`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L100) in [`InitialSettingsPage`](https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx) will `null` and subscription menu item won't be visible.

https://github.com/Expensify/App/blob/e6fc33080486c700bcadda2f375d4b04cfef5303/src/pages/settings/InitialSettingsPage.tsx#L195-L204

### What changes do you think we should make in order to solve the problem?


Let's create a condition that can return `CONST.POLICY.TYPE.TEAM` since there is no control workspace.

https://github.com/Expensify/App/blob/acf418ced84cc7066476d8b7cce7fd52b8397f01/src/hooks/useSubscriptionPlan.ts#L15-L16

The condition for this case is to check if the user's free trial has ended and does not have a payment card added. 

```
if (isEmptyObject(ownerPolicies)) {
    return SubscriptionUtils.hasUserFreeTrialEnded() && !SubscriptionUtils.doesUserHavePaymentCardAdded() ? CONST.POLICY.TYPE.TEAM : null
}
```

According to the expected possibly different behaviors for other cases, we can modify the condition to also check for other prerequisites such as if the card has errors or if it is expired.

**Comment by saifelance** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue involves TypeScript compilation errors caused by missing `path` and `fs` modules in your `export_conversation.ts` file. These modules are built-in Node.js modules and are not natively available in non-Node.js environments like browsers or when targeting certain TypeScript module resolutions.

### What is the root cause of that problem?

- Incorrect Module Resolution: `tsconfig.json` settings may not target Node.js correctly.
- Non-Node.js Bundling: Bundlers (e.g., Webpack) may exclude Node.js modules.
- Unsupported Environment: The script might be executed outside a Node.js runtime.

### What changes do you think we should make in order to solve the problem?
### Fix in tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "lib": ["ES2020"],
    "esModuleInterop": true
  }
}
```
### Fix in export_conversation.ts:
Use conditional imports or check if the code is executing in a Node.js environment

```
let fs: typeof import('fs');
let path: typeof import('path');

if (typeof require !== 'undefined') {
    fs = require('fs');
    path = require('path');
} else {
    throw new Error("This script requires Node.js runtime.");
}
```
If the code must run in both Node.js and non-Node.js environments, use polyfills or external libraries like `browserify-fs` for browser compatibility.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

### What alternative solutions did you explore? (Optional)

### Alternative Solutions

- Polyfills: Use browserify-fs or path-browserify for browser compatibility.
- Downside: Adds complexity.
- Separate Builds: Node.js and browser-specific versions.
- Downside: Harder to maintain.
- API Refactor: Offload file handling to a backend API.
- Downside: Requires infrastructure changes.


The primary fix should be made in both `export_conversation.ts` (to handle dynamic imports or environment checks) and `tsconfig.json` (to ensure Node.js module resolution).

**Comment by sobitneupane** [comment]
@stephanieelliott We show the subscription section if user has control or collect workspace. It is not dependent on the free trial expiration. I believe this is the expected behavior.

https://github.com/Expensify/App/blob/0ef4fb17c867b50f8495cda5127c8f0c537e9c35/src/hooks/useSubscriptionPlan.ts#L8-L24

**Comment by stephanieelliott** [comment]
Ah ok I see what you mean -- I agree then, this is expected behavior. Thanks @sobitneupane!
