### ISSUE TITLE
[$250] Track expense - After replace receipt, download option is missing in receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open self dm
3. Create a expense with receipt
4. Open the expense and tap on receipt
5. Tap 3 dots on top
6. Note replace, download and delete options are displayed
7. Tap replace
8. Replace receipt with new one
9. Open the receipt and tap on 3 dot

## Expected Result:
After replace receipt, download option must not be missing in receipt track expense.

## Actual Result:
After replace receipt, download option is missing in receipt track expense.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/eda2aa21-ffec-4cf1-bfd2-a57ef12689d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864774027340721391</li>
        <li>Upwork Job ID: 1864774027340721391</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Track expense - After replace receipt, download option is missing in receipt

### What is the root cause of that problem?

When the user replaces the receipt, the [`receiptURIs`](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/TransactionReceiptPage.tsx#L25) will be URI pointing locally, meaning [`imageSource`](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/TransactionReceiptPage.tsx#L27) will start with `"blob:"`.

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/TransactionReceiptPage.tsx#L25-L29

Hence, in the [`AttachmentModel`](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx), [`isLocalSource`](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx#L438-) will be `true` and the download menu item won't be pushed but skipped because this [conditional statement](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx#L438) will fail.

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx#L438-L444

### What changes do you think we should make in order to solve the problem?


Let's use the `isReceiptAttachment` boolean to create a better conditional statement that specifically allows receipt attachments to be downloaded even if `isLocalSource` is `true`.

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx#L438

Rewrite the [conditional statement](https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/components/AttachmentModal.tsx#L438) above to be like this.

```
if (!isOffline && allowDownload && (isReceiptAttachment || !isLocalSource)) {
```

**Comment by nkdengineer** [comment]
Backend bug, `ReplaceReceipt` API doesn't update the transaction receipt's source.


<img width="1512" alt="Screenshot 2024-12-06 at 14 05 01" src="https://github.com/user-attachments/assets/90011734-dea3-439c-9484-8aaebdeff163">

**Comment by slafortune** [comment]
Internal hotpick

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
