### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] iOS - Search query is cut off at the bottom for certain letters

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53317
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2299@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open hybrid app
2. Navigate to search 
3. Tap on the search icon at the top right corner 
4. Type lower case g multiple of times
5. Hit enter

## Expected Result:
The letters does not get cut off at the bottom

## Actual Result:
The lower case letter g and other letters like lower case p get cut off at the bottom

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

* Reproduced on iPhone 11 and iPhone 13 models.
## Screenshots/Videos

https://github.com/user-attachments/assets/43be7858-710d-4c45-86fc-85899effdee5

<img src="https://github.com/user-attachments/assets/c3a5b679-043c-4a4c-801d-d396eac6bd85" width="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864712686512100060</li>
        <li>Upwork Job ID: 1864712686512100060</li>
        <li>Last Price Increase: 2024-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 105260216</li>
<li>abzokhattab | Contributor | 105260217</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by isabelastisser** [comment]
I think hybrid issues need to be internal.

**Comment by suneox** [comment]
@abzokhattab [proposal](https://github.com/Expensify/App/issues/53590#issuecomment-2518414823) LGTM. This solution can resolve this issue while still addressing issue #49890

 👀 🎀 C+ reviewed

**Comment by suneox** [comment]
Update [selected proposal](https://github.com/Expensify/App/issues/53590#issuecomment-2522252488) to initiate the bot process.

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment]
Yep that works as root cause; in terms of the actual solution I think it probably makes sense to change the view height and keep the text size as is? cc @Expensify/design

**Comment by shawnborton** [comment]
Nice, the line height solution seems super straight forward.

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/50075/files#r1885756110

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

*N/A: Due to it isn't an impactful bug*

**Comment by isabelastisser** [comment]
The payments are processed in Upwork. All set!
