### ISSUE TITLE
[HOLD for payment 2024-12-17] Workspace - Add workflow button has no bottom padding from navigation bar

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found while executing QA for PR #53570 

**Version Number:** 9.0.71-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53570
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: workspace with enabled workflows. Add approvals is ON.

1. Go to WS > Workflows 
2. Tap on 'Add approval workflow'
3. Input user's email > Next (2 times)

## Expected Result:
'Add workflow' button has bottom padding from device navigation bar.

## Actual Result:
'Add workflow' button has no bottom padding from device navigation bar.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/45d9d7fd-65cc-40b6-860c-68dff334a1ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by vincdargento** [comment]
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Add workflow' button has no bottom padding from device navigation bar.

### What is the root cause of that problem?
- We are using:
https://github.com/Expensify/App/blob/35e4761ec1d043c22b02182016a812c7da62e46d/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsCreatePage.tsx#L58
### What changes do you think we should make in order to solve the problem?
- Should remove ```={false}```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by saifelance** [comment]
# Proposal 

### Please re-state the problem that we are trying to solve in this issue.
The "Add Workflow" button in Workspace > Workflows lacks bottom padding, overlapping the navigation bar, making it hard to interact with on some devices.


### What is the root cause of that problem?
Missing safe area padding in the `ScreenWrapper` component causes insufficient spacing near the device's bottom navigation bar.


### What changes do you think we should make in order to solve the problem?

1. Set `includeSafeAreaPaddingBottom` to `true` in `ScreenWrapper`.
2. Add `paddingBottom` to the button container for consistent spacing.
3. Update theme styles to support reusable bottom padding (e.g., `pb4` for 16px).

`App/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsCreatePage.tsx
`

```
<ScreenWrapper
    includeSafeAreaPaddingBottom={true} // Enabled safe area padding
    testID={WorkspaceWorkflowsApprovalsCreatePage.displayName}
>
    <FullPageNotFoundView
        shouldShow={shouldShowNotFoundView}
        subtitleKey={isEmptyObject(policy) ? undefined : 'workspace.common.notAuthorized'}
        onBackButtonPress={PolicyUtils.goBackFromInvalidPolicy}
        onLinkPress={PolicyUtils.goBackFromInvalidPolicy}
    >
        <HeaderWithBackButton
            title={translate('workflowsCreateApprovalsPage.title')}
            onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_APPROVER.getRoute(route.params.policyID, 0))}
        />
        {!!approvalWorkflow && (
            <>
                <ApprovalWorkflowEditor
                    approvalWorkflow={approvalWorkflow}
                    policy={policy}
                    policyID={route.params.policyID}
                    ref={formRef}
                />
                <FormAlertWithSubmitButton
                    isAlertVisible={!isEmptyObject(approvalWorkflow?.errors)}
                    onSubmit={createApprovalWorkflow}
                    onFixTheErrorsLinkPressed={() => {
                        formRef.current?.scrollTo({y: 0, animated: true});
                    }}
                    buttonText={translate('workflowsCreateApprovalsPage.submitButton')}
                    containerStyles={[styles.mb5, styles.mh5, styles.pb4]} // Added bottom padding
                    enabledWhenOffline
                />
            </>
        )}
        {!approvalWorkflow && <FullScreenLoadingIndicator />}
    </FullPageNotFoundView>
</ScreenWrapper>
```



### What alternative solutions did you explore? (Optional)

- Spacer Component: Adds redundancy and complexity.
- Hardcoded Padding: Lacks adaptability to device layouts.

**Comment by kirillzyusko** [comment]
Hey, I'm Kiryl from Margelo expert agency and I'd like to work on this issue

**Comment by CortneyOfstad** [comment]
Deployed to staging 2 hours ago 🎉

**Comment by CortneyOfstad** [comment]
@kirillzyusko can you confirm if this needs a regression test?

**Comment by alitoshmatov** [comment]
Can someone assign me to this issue as I was reviewer on the PR

**Comment by kirillzyusko** [comment]
> can you confirm if this needs a regression test?

@CortneyOfstad no, I don't think so 🙂

**Comment by CortneyOfstad** [comment]
## Payment Summary

@alitoshmatov — to be paid $250 via NewDot (PR reviewer)

## Regression Test

Determined it was not needed
