### ISSUE TITLE
[HOLD for payment 2024-12-25] [$250] iOS Search - Filter icon is not responsive when navigating to Search via WS chat in WS settings

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to workspace settings.
3. Tap on the workspace chat under "Submit expenses using your workspace chat below"
4. Tap on the search icon on the top right.
5. Type anything and search it.
6. On Search page, tap on the filter icon.

## Expected Result:
Filter options will open.

## Actual Result:
Filter icon is not responsive.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c5f591e9-e277-4a2c-86f2-ff0ad14ce824

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864902077815200576</li>
        <li>Upwork Job ID: 1864902077815200576</li>
        <li>Last Price Increase: 2024-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 105267754</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by saifelance** [comment]
# Proposal 

### Please re-state the problem that we are trying to solve in this issue.
The issue involves [specific problem, e.g., "inconsistent form behavior causing incorrect submissions"], affecting [impact, e.g., "data reliability and user experience"].


### What is the root cause of that problem?
Triggered by [root cause, e.g., "a race condition in asynchronous state management"].


### What changes do you think we should make in order to solve the problem?

1. Refactor state management to handle async operations correctly.
2. Add validation checks at client/server levels.
3. Enhance error handling for better feedback and logging.
4. Update outdated dependencies.

Suggested Fix for the Filter Icon Handler
```
function onFilterIconPress() {
    if (isExecuting) {
        return; // Prevent multiple executions.
    }

    singleExecution(() => {
        // Logic to show filter options
        Navigation.navigate(ROUTES.SEARCH_FILTER); // Adjust as per your route setup.
    })();
}
```

### Add Accessibility and Clickability Checks


```
<TouchableOpacity
    onPress={onFilterIconPress}
    accessible={true}
    accessibilityLabel={translate('search.filter')}
    style={styles.filterIconContainer}
>
    <Expensicons.Filter />
</TouchableOpacity>
```



### What alternative solutions did you explore? (Optional)

1. Rewrite module (time-intensive).
2. Adopt a new state library (steep learning curve).
3. Implementing targeted fixes and robust tests will resolve the issue and prevent recurrence.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The filter button is "unresponsive"

### What is the root cause of that problem?
In WorkspaceInitialPage, we check to see if the active route of the sub-page of the workspace settings page is accessible.
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/workspace/WorkspaceInitialPage.tsx#L360-L376

If not, then we dismiss any RHP. For example, if the user opens a workspace as a member and tries to open the workspace categories setting, then the categories setting RHP will be dismissed and the not found page will show from the workspace categories list page.

In our case, we open the workspace's initial page. The active route becomes `Workspace_Initial`. However, the current `canAccessRoute` logic only checks for the sub-page route. So, when it compares the active route with itself, it fails because `menuItems` doesn't contain `Workspace_Initial`.

We actually have the logic to run it only once.
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/workspace/WorkspaceInitialPage.tsx#L368-L371

But when we open the search page, all routes are "hidden".
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/useStateWithSearch.ts#L44-L57

So, the `wasRendered` logic in WorkspaceInitialPage won't work.

### What changes do you think we should make in order to solve the problem?

We can update `canAccessRoute` to cover the case of the workspace's initial page itself.
```
const canAccessRoute = activeRoute && (menuItems.some((item) => item.routeName === activeRoute) || activeRoute === SCREENS.WORKSPACE.INITIAL);
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Filter icon is not responsive when navigating to Search via WS chat in WS settings.

### What is the root cause of that problem?

> [!note]
> This issue is only present on narrow layout devices (native / mWeb) where screens displayed in RHP act as a modal.

https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/workspace/WorkspaceInitialPage.tsx#L360-L376

When we open the workspace's initial page, the active route becomes `Workspace_Initial`. However, the current `canAccessRoute` logic only checks for the sub-page route - therefore when it compares the active route with itself, it fails because `menuItems` doesn't contain `Workspace_Initial`.

We actually have the logic to only run it once [here](https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/workspace/WorkspaceInitialPage.tsx#L368-L371), but when we open the search page, all routes are "hidden" as explained [here](https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/useStateWithSearch.ts#L44-L57). Because of this, the `wasRendered` logic in `WorkspaceInitialPage` won't work as expected -> when we try to open the filter page, the previously "hidden" routes are added back to the stack and `canAccessRoute` becomes `false` which will dismiss any RHP that we try to open (Filters).

Credits to **bernhardoj** for the RCA.

### What changes do you think we should make in order to solve the problem?

We had a similar issue which I reviewed recently [here](https://github.com/Expensify/App/issues/52258) where we navigated away from `WorkspaceProfileSharePage` to a report **without dismissing the currently opened modal** which caused a weird UI bug in the QR Code because the same modal would be opened twice.

A practical solution for this kind of issue **which wouldn't break any other functionality** is to simply replace the way we navigate away from WS to the report here:

https://github.com/Expensify/App/blob/b595f5d24141a403fcc3f44c73d00cd6951dca7d/src/pages/workspace/WorkspaceInitialPage.tsx#L457

to use `Navigation.dismissModal` instead:

```ts
onPress={() => Navigation.dismissModal(currentUserPolicyExpenseChat?.reportID ?? '-1')}
```

**Why dismissing the modal first fixes our issue ?**
Because as explained in RCA, on narrow layout devices (native / mWeb) screens displayed in RHP act as a modal and by dismissing it when navigating to the report, all the conditions which lead to the Filters RHP to being able to open when clicked on in our case, will now work as expected.

### Result video (before / after)

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/30ed387a-f619-4143-a913-aad6f2ba32b7"> | <video src="https://github.com/user-attachments/assets/7139d6ea-c38e-442c-adc9-90ab1fdff810"> |

</details>

**Comment by ikevin127** [comment]
> [!important]
> I proposed the same solution for [this issue](https://github.com/Expensify/App/issues/53589) and because this solution would fix both issues, if my solution is selected on any of the two issues -> we should put the other one on **HOLD**.

cc @rayane-djouah

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by bfitzexpensify** [comment]
Payment summary:

@rayane-djouah due $250 for C+ work, paid via Upwork ✅ 
@bernhardoj due $250 for contributor work via NewDot manual request

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
