### ISSUE TITLE
[$250] App crashes when clicking add reaction

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation** (hyperlinked to channel name): [expensify_retain](https://expensify.slack.com/archives/C07NZ8B1VTQ/p1733411293984459)

## Action Performed:
1. Go to any chat
2. Send a message
3. Click the "Add reaction" button to add a non-default emoji reaction
## Expected Result:
Emoji reaction menu appears
## Actual Result:
App crashes and shows "Uh-oh, something went wrong!" screen
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/b4ac8491-2d78-4398-b183-e5cca7a17007

```
hook.js:608 Error: Couldn't find a navigation object. Is your component inside NavigationContainer?
    at c (index.ts:32:24)
    at X (index.tsx:107:5)
overrideMethod	@	hook.js:608
uA	@	react-dom.production.min.js:188
a.componentDidCatch.n.callback	@	react-dom.production.min.js:189
Ha	@	react-dom.production.min.js:156
Es	@	react-dom.production.min.js:260
Is	@	react-dom.production.min.js:259
ms	@	react-dom.production.min.js:258
(anonymous)	@	react-dom.production.min.js:282
yl	@	react-dom.production.min.js:280
il	@	react-dom.production.min.js:269
v	@	scheduler.production.min.js:13
k	@	scheduler.production.min.js:14
e.exports	@	_invoke.js:5
f.<computed>	@	_task.js:35
I	@	_task.js:21
E	@	_task.js:25
```
At c is the useNavigation line:
```
const useHtmlPaste: UseHtmlPaste = (textInputRef, preHtmlPasteCallback, removeListenerOnScreenBlur = false, isMarkdownEnabled = true) => {
    const navigation = useNavigation();
```
At X is:
```
useHtmlPaste(input as MutableRefObject<TextInput | null>, undefined, false, isMarkdownEnabled);
```

https://github.com/user-attachments/assets/e019651b-eb49-4a6c-b35a-5efcb1e1ef4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864710692177622796</li>
        <li>Upwork Job ID: 1864710692177622796</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by stitesExpensify** [comment]
Posted [here](https://github.com/Expensify/App/pull/53367#issuecomment-2520894459) on what I think is the offending PR

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash when opening emoji picker.

### What is the root cause of that problem?
This happened after https://github.com/Expensify/App/pull/53367 where we add `useHtmlPaste` to `BaseTextInput`. `useHtmlPaste` depends on `useNavigation` which requires a NavigationContainer.
https://github.com/Expensify/App/blob/18eca4b44fe0b8ebef57994ca43fcd6d19e749fc/src/hooks/useHtmlPaste/index.ts#L31-L32

But since the emoji picker menu isn't inside a navigation container, the error shows.
https://github.com/Expensify/App/blob/18eca4b44fe0b8ebef57994ca43fcd6d19e749fc/src/Expensify.tsx#L259

### What changes do you think we should make in order to solve the problem?

The navigation object inside `useHtmlPaste` is used to unsubs the paste listener when the screen is blurred, which is currently being used for report screen composer.
https://github.com/Expensify/App/blob/18eca4b44fe0b8ebef57994ca43fcd6d19e749fc/src/hooks/useHtmlPaste/index.ts#L136-L144

I think it's better to decouple the navigation object from the`useHtmlPaste` hook. Instead, `useHtmlPaste` can replace the `removeListenerOnScreenBlur` param with `isActive` which registers the listener based on the `isActive` value and the report screen composer can pass the navigation focused state to the `isActive` param. (then we can also remove `isMarkdownEnabled`)
```
const useHtmlPaste: UseHtmlPaste = (textInputRef, preHtmlPasteCallback, isActive = true) => {
    ...
    useEffect(() => {
        if (!isActive) {
            return;
        }
        document.addEventListener('paste', handlePaste, true);

        return () => {
            document.removeEventListener('paste', handlePaste, true);
        };
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [isActive]);
    ...
};
```

https://github.com/Expensify/App/blob/18eca4b44fe0b8ebef57994ca43fcd6d19e749fc/src/components/Composer/implementation/index.tsx#L255

```
const isScreenFocused = useIsFocused();
useHtmlPaste(textInput, handlePaste, isScreenFocused);
```

Then, we need to update the `useHtmlPaste` usage in BaseTextInput (native and non native) to pass `isMarkdownEnabled` as the 3rd param.
https://github.com/Expensify/App/blob/18eca4b44fe0b8ebef57994ca43fcd6d19e749fc/src/components/TextInput/BaseTextInput/index.tsx#L107

```
useHtmlPaste(input, undefined, isMarkdownEnabled);
```

**Comment by lanitochka17** [comment]
We are facing a similar problem, but in a different place. Should we raise this issue?
 

https://github.com/user-attachments/assets/c93b90aa-ea7a-43ff-b10b-72130eea7e40

**Comment by MitchExpensify** [comment]
What's our next steps here @stitesExpensify ?

**Comment by puneetlath** [comment]
QA confirmed it's not reproducible after the revert CP.

**Comment by MitchExpensify** [comment]
If the revert PR fixed this, are we good to close?

**Comment by stitesExpensify** [comment]
Yep we're good!

**Comment by MitchExpensify** [comment]
Reminder set to pay, please complete the BZ steps in the meantime @ntdiary

**Comment by MitchExpensify** [comment]
*Payment summary:*

- $250 @ntdiary requires payment through NewDot Manual Requests

Reminder on the [BZ steps](https://github.com/Expensify/App/issues/53637#issuecomment-2565698889) @ntdiary

**Comment by MitchExpensify** [comment]
Ah, thanks for the catch @ntdiary. Deleting the payment summary in that case!
