### ISSUE TITLE
[HOLD for payment 2024-12-30] [$50] Update BOA and Capital One card images

### ISSUE THREAD

**Issue by dannymcclain** [Expensify/App#53649]
## Problem
The Bank of America and Capital One card images we're currently using are almost invisible in light mode.

One example:
![image](https://github.com/user-attachments/assets/17c42c83-f0d2-4630-b383-bc89baae8316)

## Solution
Let's update the SVGs we're using for these banks/cards so that you can see them better!
> [!NOTE]
> We need to update both the small images that appear in the card list as well as the large ones that appear in the RHP 

### New Files:

- [card-capital_one.svg.zip](https://github.com/user-attachments/files/18028471/card-capital_one.svg.zip)
- [card-bofa.svg.zip](https://github.com/user-attachments/files/18028472/card-bofa.svg.zip)
- [card-capital_one-large.svg.zip](https://github.com/user-attachments/files/18028474/card-capital_one-large.svg.zip)
- [card-bofa-large.svg.zip](https://github.com/user-attachments/files/18028475/card-bofa-large.svg.zip)

![image](https://github.com/user-attachments/assets/7bdf5895-949d-476e-80a7-11062a395535)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864750680476472028</li>
        <li>Upwork Job ID: 1864750680476472028</li>
        <li>Last Price Increase: 2024-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>twilight2294 | Contributor | 105261385</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by dannymcclain** [comment]
The bounty for this one can probably be smaller—it _should_ be as simple as just replacing the files. 🤞

**Comment by bfitzexpensify** [comment]
>The bounty for this one can probably be smaller—it should be as simple as just replacing the files. 🤞

Agreed, going to set this at $50.

**Comment by dannymcclain** [comment]
Oh and cc @Expensify/design just for fun/visibility 😜

**Comment by dannymcclain** [comment]
Not overdue. In the proposal review stage.

**Comment by rushatgabhane** [comment]
🎀👀🎀

https://github.com/Expensify/App/issues/53649#issuecomment-2521265725

@twilight2294's proposal LGTM

**Comment by rushatgabhane** [comment]
@gijoe0295 is also fine because they were first but they did not mention any details which is probably okay for this issue.

@rlinoz your call 😄

**Comment by bfitzexpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by bfitzexpensify** [comment]
Payment summary:

@twilight2294 paid $50 via Upwork
@rushatgabhane due $50 via ND manual request

**Comment by garrettmknight** [comment]
$50 approved for @rushatgabhane
