### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] Workspace list is opened in background when workspace description is opened from workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace.
3. Go to workspace settings > Profile.
4. Click Description, add a description and save it.
5. Click on the workspace chat under "Submit expenses using your workspace chat below" on the same page (important).
6. In workspace chat, click on the header subtitle to open workspace description editor.

## Expected Result:
The background will be workspace settings.

## Actual Result:
The background is workspace list.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/afaedc1c-3380-47b2-9958-876a3c488ff5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864885429995006456</li>
        <li>Upwork Job ID: 1864885429995006456</li>
        <li>Last Price Increase: 2024-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>twilight2294 | Contributor | 105273277</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user clicks on the workspace description in the workspace header, The workspaces list is shown in the background, but Workspace profile is expected.
### What is the root cause of that problem?
We are not passing backTo here, when user click on the desc:
https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/home/HeaderView.tsx#L265
### What changes do you think we should make in order to solve the problem?
pass `Navigation.getActiveRoute()` as backTo route:
`                                                    Navigation.navigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(report.policyID ?? '-1',Navigation.getActiveRoute()));`

and modify the `ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute` to accept backTo :
https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/ROUTES.ts#L856
as:
`        getRoute: (policyID: string, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/description` as const, backTo),`

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace list is opened in background when workspace description is opened from workspace chat

### What is the root cause of that problem?

When we click on the workspace chat under ‘Submit expenses using your workspace chat below,’ the `FullScreenNavigator` is pushed  root state
https://github.com/Expensify/App/blob/522bb766608dd8e3b12446ffaf0aaeedb643134f/src/pages/workspace/WorkspaceInitialPage.tsx#L456

And we click in HeaderView to go to `WORKSPACE_PROFILE_DESCRIPTION` then `Report` will pushed to pushed root state.

So the routes will be: 

1. BottomTabNavigator
2. Settings_Workspace
3. FullScreenNavigator
4. Report
5. Settings_Workspaces
6. RightModalNavigator

To debug this we add this code and follow step in this ticket.

```
    const root = navigationRef.getRootState();
    console.log('****** root 123123 ******', JSON.stringify(root));
    console.log('****** root 123123 ******', root);
```

https://github.com/Expensify/App/blob/1b5ae4353d5c4536e33e6393bb585d5fa157b49d/src/pages/workspace/WorkspacesListPage.tsx#L430

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we follow the stack: `FullScreenNavigator` -> `Settings_Workspaces` -> `RightModalNavigator`. To do this, we need to add `Navigation.goBack()` to go back to the previous page. Something like this:

1 Add go back before navigation to `WORKSPACE_PROFILE_DESCRIPTION`
https://github.com/Expensify/App/blob/5180ef4b9b47a48dda6e4d35e3db615cf70aa187/src/pages/home/HeaderView.tsx#L164-L167

```diff
    if (ReportUtils.canEditPolicyDescription(policy)) {
        Navigation.goBack();
        Navigation.navigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(report.policyID ?? '-1'));
        return;
    }
```

2 This is similar to this issue; we still applied goBack before navigating to `WORKSPACE_PROFILE_DESCRIPTION`
https://github.com/Expensify/App/blob/e8dd2bd3496a313f378678028c2a7b62c0acf30b/src/components/ReportWelcomeText.tsx#L109-L114

```diff
    onPress={() => {
        if (!canEditPolicyDescription) {
            return;
        }

        Navigation.goBack();
        Navigation.navigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(policy?.id ?? '-1'));
    }}
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by skanderphilipp** [comment]
## Proposal

### Cause Analysis
The issue occurs because the navigation logic uses Navigation.navigate() for the route, which may reuse a cached navigation stack containing the workspace list. This happens when the navigation state isn't cleanly reset or managed.


### What changes do you think we should make in order to solve the problem?

Replace Navigation.navigate() with Navigation.closeAndNavigate() to ensure the navigation state is cleaned and the correct route is opened without reusing unintended screens.

Code Change in **HeaderView.tsx** lines 263 - 269 should look like this: 

```typescript
onPress={() => {
    if (ReportUtils.canEditPolicyDescription(policy)) {
        Navigation.closeAndNavigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(report.policyID ?? '-1'));
        return;
    }
    Navigation.closeAndNavigate(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(reportID, Navigation.getReportRHPActiveRoute()));
}}

``` 


https://github.com/user-attachments/assets/007fb0f5-e8d1-4c80-a1eb-d1233c1b9c17


### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

Avoid relying on Navigation.navigate() when the route might already exist in the navigation stack. Also use replacement instead of stacking. 

### What alternative solutions did you explore? (Optional)

Alternative you can use a replace function, resetting or a conditional goBack.

**Comment by skanderphilipp** [comment]
Contributor details
Your Expensify account email: skander@bentech.app
Upwork Profile Link: [Upwork Profile](https://www.upwork.com/freelancers/~01957d242a71f5f63b)

**Comment by Shahidullah-Muffakir** [comment]
@dukenv0307,
What are your thoughts on my  [proposal](https://github.com/Expensify/App/issues/53665#issuecomment-2521701789)? Passing the backTo route is a common pattern we use throughout the app, and it seems to align well with the expected behavior.

Currently, the backTo route is passed in other cases on the same page but is missing specifically for the workspace description. For example, we are passing backTo for **reportDescription**, but not for **workspaceDescription**. This inconsistency seems to be the root cause of the issue, Thanks.

https://github.com/Expensify/App/blob/840c227be7fd907ab096cda7d6f28e1eef4a1d30/src/pages/home/HeaderView.tsx#L244-L245

**Comment by huult** [comment]
@dukenv0307 Thank you for reviewing my proposal. I will update the RCA now

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir Can you elaborate on the RCA? And I did test your solution and it didn't work.

@dukenv0307, we need to pass the backTo route here because:

1. In other parts of the app when RHP open, we pass the backTo route to ensure the current page is show as the fullscreen navigator in the bacgrkound and when user press the back button the user redirects to the current page, without it, the app defaults to the FullScreenNavigator, if user press the back button.

2. The backTo route is also needed when the user refreshes the workspace description edit page. Without it, the page falls back to the workspace list in the background instead of reopening with the Workspace Settings page in the background

After adding my changes:

https://github.com/user-attachments/assets/68495a3a-ce27-4397-b404-1fe89598ab37

**Comment by skanderphilipp** [comment]
> @skanderphilipp Your [proposal](https://github.com/user-repo/issues/issue-id#comment-id) will be dismissed because you did not follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

I updated the proposal, is there still some issues with the template ?

**Comment by Percept-Systems** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
Workspaces list is opened in background when workspace description is opened from workspace chat under "Submit expenses using your workspace chat below"

What is the root cause of that problem?
The issue occur due to preserve the current screen in the navigation stack. Commonly occurs when we need the current screen using Navigation.navigate() in stack.

What changes do you think we should make in order to solve the problem?
To resolve the issue we need to add a Navigation.goBack() before navigating to other screen so that we can clear the current screen as per stack to show the workspace settings screen.

Code Change in HeaderView.tsx lines 263 - 270 should look like this:

onPress={() => {
                                                if (ReportUtils.canEditPolicyDescription(policy)) {
                                                    Navigation.goBack();
                                                    Navigation.navigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(report.policyID ?? '-1'));
                                                    return;
                                                }
                                                Navigation.navigate(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(reportID, Navigation.getReportRHPActiveRoute()));
                                            }}
 
After implementing the above changes in code:


https://github.com/user-attachments/assets/9ee1302c-4361-4bba-9c32-b0e3aabdce68

What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

What alternative solutions did you explore? (Optional)
Alternatives can be replace() to use the required screen in the stack or reset() to clear the stack.

**Comment by huult** [comment]
## [Proposal Updated](https://github.com/Expensify/App/issues/53665#issuecomment-2522577672)

- Add new RCA.

Short RCA: The issue occurs due to an incorrect navigation stack: Report is before Settings_Workspaces, and FullScreenNavigator is before Report, causing navigation to the workspace list instead of the workspace profile.

Solution: We need to use `goBack` to remove the `Report` route and ensure the navigation works as expected

@dukenv0307 I’ve updated the new RCA. If it’s still not enough for you, please let me know, or if you have any questions. Thank you!

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir Your evidence is incorrect, our expectation here is `The background will be workspace settings`, not report chat

@dukenv0307, thanks for clarifying, I misunderstood the expected behavior.

Instead of passing the current page as `backTo`, we can pass the workspace's initial page. Here's the updated code: `Navigation.navigate(ROUTES.WORKSPACE_PROFILE_DESCRIPTION.getRoute(report.policyID ?? '-1', ROUTES.WORKSPACE_INITIAL.getRoute(report?.policyID ?? '-1')));                                                 
`
Updated the proposal https://github.com/Expensify/App/issues/53665#issuecomment-2521701789 as well

https://github.com/user-attachments/assets/55fd88cf-2c53-4237-acd9-742f1a9582f9

**Comment by jliexpensify** [comment]
Hi, Kadie is OOO so I'll take care of checklist and payment here

**Comment by jliexpensify** [comment]
Payment Summary

- C: @twilight2294 $250 (to be paid via Upworks)
- C+: @dukenv0307 (to be paid via ND payments)

[Upwork job](https://www.upwork.com/jobs/~021864885429995006456)

**Comment by jliexpensify** [comment]
Paid and job closed!

@dukenv0307 - [checklist here](https://github.com/Expensify/App/issues/53665#issuecomment-2564959288)

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307

**Comment by jliexpensify** [comment]
Hmm this issue was paid a while back - [I feel like](https://github.com/Expensify/App/issues/54303) came after (as the blocker) so I don't think that issue should have been paid.
