### ISSUE TITLE
Debug - Incorrect date in lastVisibleActionCreated debug mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53323
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2359@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Turn debug mode on 
3. Open a report and send a message 
4. Click on header > Debug 
5. Scroll down until you see lastVisibleActionCreated

## Expected Result:
The date will be today

## Actual Result:
Incorrect date is displayed meanwhile the time is displayed correctly

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/74e4e64c-9c91-4895-96a9-374a62f71fab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Debug - Incorrect date in lastVisibleActionCreated debug mode

### What is the root cause of that problem?
We are not displaying date fields in the current user's timezone setting here
https://github.com/Expensify/App/blob/48b80f65e80d304965cbeb3573d7d6678fb9bd3a/src/pages/Debug/DebugDetails.tsx#L226
### What changes do you think we should make in order to solve the problem?

We should format it to the current user timezone like we did [ReportActionDebug](https://github.com/FitseTLT/App/blob/48b80f65e80d304965cbeb3573d7d6678fb9bd3a/src/pages/Debug/Report/DebugReportActions.tsx#L39)
```
                            defaultValue={datetimeToCalendarTime(String(value), false, false)}

```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
This is not a bug we see the data in UTC instead of the user's timezone as it is for debugging purpose and the BE saves it on UTC 👍

**Comment by DylanDylann** [comment]
@FitseTLT Thanks for your information. I have same opinion with you that let's leave it away

cc @puneetlath

**Comment by puneetlath** [comment]
Makes sense to me too. Going to close. Feel free to comment/reopen if anyone disagrees.
