### ISSUE TITLE
[HOLD for payment 2024-12-30] [$125] Android & iOS - Review duplicates - Confirm button has extra bottom padding on confirm page

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#53669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to workspace chat.
3. Submit two expenses of the same amount.
4. Go to transaction thread of any expense.
5. Tap Review duplicates.
6. Tap Keep this on (any expense).
7. Go through the flow and proceed to confirmation page.

## Expected Result:
Confirm button will not have extra bottom padding.

## Actual Result:
Confirm button has extra bottom padding.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3fe888b9-411d-4989-96f0-1fd67807b8b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867335169078462217</li>
        <li>Upwork Job ID: 1867335169078462217</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is extra bottom spaces in review duplicate transaction page.

### What is the root cause of that problem?
The safe area padding-bottom is applied twice.
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/TransactionDuplicate/Confirmation.tsx#L93-L99

Once from inside the ScreenWrapper itself, and once from the `safeAreaPaddingBottomStyle` that we consume and apply to the View as shown above.

### What changes do you think we should make in order to solve the problem?

Remove the `safeAreaPaddingBottomStyle`. This makes the code simpler too.
```
<ScreenWrapper
    testID={Confirmation.displayName}
    shouldShowOfflineIndicator
>
    <FullPageNotFoundView shouldShow={true}>
        <View style={styles.flex1}>
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A, it's a visual UI issue.

**Comment by slafortune** [comment]
Checking on this https://expensify.slack.com/archives/C01SKUP7QR0/p1734039216754849

**Comment by maniyadhruvit1** [comment]
> 📣 @maniyadhruvit1! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Make sure you've read and understood the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).
> 2. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 3. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 4. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: [dhruvitmaniya@gmail.com](mailto:dhruvitmaniya@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0165203f0416345066

**Comment by maniyadhruvit1** [comment]
### **Proposal**


### **Please re-state the problem that we are trying to solve in this issue.**
 - There is extra bottom spaces in review duplicate transaction page.

### **What is the root cause of that problem?**
 - In this we have used **ScreenWrapper Component** which is adding pedding at bottom.
 - also we have added **safeAreaPaddingBottomStyle** which is also adding pedding at bottom, so we have applied bottom padding two times.
 
###  **What changes do you think we should make in order to solve the problem?**
 - We can remove **safeAreaPaddingBottomStyle** from Confirmation.tsx file.
 - **Problem in code**
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/TransactionDuplicate/Confirmation.tsx#L97-L104
- **Solution**
`<ScreenWrapper
    testID={Confirmation.displayName}
    shouldShowOfflineIndicator>
    <FullPageNotFoundView shouldShow={true}>
        <View style={styles.flex1}>`

### **What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?**
 - N/A

### **What alternative solutions did you explore? (Optional)**
- We can also resolve this issue by adding  **includeSafeAreaPaddingBottom={false}** to remove extra spacing
- **Problem in code**
https://github.com/Expensify/App/blob/3baf965618ced48845ddd7534b0fad4d4110b5de/src/pages/TransactionDuplicate/Confirmation.tsx#L93-L96
- **Solution**
`   <ScreenWrapper
        includeSafeAreaPaddingBottom={false}
            testID={Confirmation.displayName}
            shouldShowOfflineIndicator
        > `

**Comment by maniyadhruvit1** [comment]
Contributor details
Your Expensify account email: [dhruvitmaniya@gmail.com](mailto:dhruvitmaniya@gmail.com)
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~0165203f0416345066)

**Comment by maniyadhruvit1** [comment]
Contributor details
Your Expensify account email: dhruvitmaniya@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0165203f0416345066?mp_source=share

**Comment by jjcoffee** [comment]
Thanks for the proposals everyone!

I think we need to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/53669#issuecomment-2522224015) here, given the changes in https://github.com/Expensify/App/pull/53250, specifically:

> The `<ScreenWrapper>` component should handle the bottom safe area inset in the most places.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by chiragsalian** [comment]
Proposal sounds good to me. Feel free to create the PR @bernhardoj

**Comment by bernhardoj** [comment]
PR is ready

cc: @jjcoffee

**Comment by jjcoffee** [comment]
Not sure where Melv is getting the $250 from since it's $125 in the issue title!

**Comment by jjcoffee** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by slafortune** [comment]
@jjcoffee - Role C+ - owed $125 via NewDot
@bernhardoj - Role Contributor - owed $125 via NewDot

**Comment by garrettmknight** [comment]
$125 approved for @jjcoffee

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$125 approved for @bernhardoj
