### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] iOS&Android Expense - App does not respond to long tap on receipt placeholder area on expense preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+zm69@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create an expense with receipt.
4. On the main workspace chat, long tap on the receipt area on the preview.
5. Note that it responds to long tap and opens menu.
6. Delete the expense.
7. Submit an expense without receipt.
8. On the main workspace chat, long tap on the receipt placeholder area on the preview.

## Expected Result:
App will respond to the long tap and open more options menu.

## Actual Result:
App does not respond to long tap on the empty receipt placeholder area on the expense preview.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/91ebb35f-3f2f-4f84-ac83-d8e0262065a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866480849153052085</li>
        <li>Upwork Job ID: 1866480849153052085</li>
        <li>Last Price Increase: 2024-12-10</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 105311644</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long press on a empty receipt doesn't show the context menu.

### What is the root cause of that problem?
The receipt empty state is wrapped with a pressable.
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/components/ReceiptEmptyState.tsx#L24-L33

This makes it a nested pressable in a ReportPreview or MoneyRequestPreviewContent. The long press doesn't bubble up, which is why we manually handle the report preview long press to show the context menu.
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/components/ReportActionItem/ReportPreview.tsx#L464-L468

But we don't do the same for the receipt empty state component.

### What changes do you think we should make in order to solve the problem?

But instead of handling the long press manually for receipt empty state, we can just render a View instead of Pressable if the receipt empty state `onPress` is undefined. (we need to remove the `onPress` default value)
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/components/ReceiptEmptyState.tsx#L24-L33

```
const Wrapper = onPress ? PressableWithoutFeedback : View;
    return (
        <Wrapper
```

Then, we can remove the receipt image `onPress` from the ReportPreview and MoneyRequestPreviewContent. (the onPress is only being used by receipt empty state)
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/components/ReportActionItem/ReportPreview.tsx#L475-L480
https://github.com/Expensify/App/blob/b9107bf59cbb3982d958abbae357e3b903ed4c63/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L351-L355

It was added because the parent pressable `onPress` isn't triggered when pressing on the receipt empty state. But we can remove it now since we won't use nested pressable anymore for the receipt empty state.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by suneox** [comment]
@bernhardoj [proposal](https://github.com/Expensify/App/issues/53697#issuecomment-2523165254) LGTM. In this case, we can prevent nested pressables

🎀 👀 🎀 C+ reviewed

**Comment by blimpich** [comment]
@bernhardoj @suneox can we add unit testing to the proposal? Or list a strong reason why we aren't adding unit tests? See [this slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1733148961659549) for a reminder on our new policy of unit tests for bugs.

**Comment by suneox** [comment]
> @bernhardoj @suneox can we add unit testing to the proposal? Or list a strong reason why we aren't adding unit tests? See [this slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1733148961659549) for a reminder on our new policy of unit tests for bugs.

Currently, our tests focus on unit testing for functions like utilities, Onxy data, Req/Res, .... However, this issue involves user interactions, which we don’t fully support in unit tests yet
But we can explore related code changes and provide manual test scenarios to prevent regression.

**Comment by blimpich** [comment]
I believe we are able to test user interactions, there just aren't many test suites yet. See below test suites:
- `tests/ui/WorkspaceSwitcherTest.tsx`
- `tests/ui/UnreadIndicatorsTest.tsx`
- `tests/ui/SwitchToExpensifyClassicTest.tsx`
- `tests/ui/PaginationTest.tsx`

If there is a technical reason why we can't add unit tests for this I'd like that to be added to the proposal. If it would take too much work than I'd also accept that, but I'd like to know why it takes so much work / isn't possible right now.

**Comment by bernhardoj** [comment]
I have the same thought as @suneox of this [comment](https://github.com/Expensify/App/issues/53697#issuecomment-2536854328).

> If there is a technical reason why we can't add unit tests for this I'd like that to be added to the proposal.

I was trying to create the test and found that it's not "possible" to test it. I have added the explanation on the proposal.

**Comment by blimpich** [comment]
@bernhardoj Thank you for the explanation! Sorry for bugging you both for it but we are really trying to push for more unit tests and its very helpful for me to know why its difficult or what scenarios we aren't able to test right now. Thank you! Lets fix this without new jest tests 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @suneox

**Comment by bfitzexpensify** [comment]
Payment summary: 

@bernhardoj to be paid $250 for contributor work via ND manual request
@suneox to be paid $250 for C+ work - @suneox, please complete the BZ checklist and I'll finalise payment via Upwork

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/52848/files#r1899525216

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    *N/A: Due to it isn't an impactful bug*

**Comment by bfitzexpensify** [comment]
Thanks! Payment complete.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
