### ISSUE TITLE
[$250] Eemployee added to a workspace in Classic with a user role doesn't have the Concierge chat pinned in ND

### ISSUE THREAD

**Issue by flaviadefaria** [Expensify/App#53788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** NA
**Reproducible in staging?:**  Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** NA
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):** flavia.usertesting+migrationuser2@gmail.com
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @flaviadefaria 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1733514836993019

## Action Performed:
1. Add a new user with a `user` role to a workspace in Classic
2. Sign in to the user's account in ND

## Expected Result:
Concierge should be pinned for the user

## Actual Result:
Concierge wasn't pinned for the user in New Expensify

<img width="621" alt="image" src="https://github.com/user-attachments/assets/7496ce95-1e4d-4a0e-acda-db6810e1dbc4">

## Workaround:
NA

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866216652652457199</li>
        <li>Upwork Job ID: 1866216652652457199</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Eemployee added to a workspace in Classic with a user role doesn't have the Concierge chat pinned in ND
### What is the root cause of that problem?
I think we don't need !`shouldShowGreenDotIndicatori `n 
https://github.com/Expensify/App/blob/4f4720e896d6db90fd9acca0982d8620b3937e47/src/components/LHNOptionsList/OptionRowLHN.tsx#L343
### What changes do you think we should make in order to solve the problem?
we can remove the !shouldShowGreenDotIndicator from the condition

**Comment by rojiphil** [comment]
> what are your thoughts on the proposals above? This is a critical issue for #migrate so we're aiming for a quick turnaround here.

Sure. Looking into the issue now.

**Comment by rojiphil** [comment]
@flaviadefaria As per the OP steps, the concierge chat is already pinned. It is just that there is pending activity for the user here so that the `pin` is not displayed. But once the user takes the necessary action, the pin is displayed. Here is the test video demonstrating the same. 

But I also notice in the image attached in OP that GBR or pin is not displayed for concierge. Also, the subtitle displays `You’ve been upgraded Congratulations!` So, it looks like some additional steps are needed to reproduce this. Can you please provide more information (steps or video) that can help reproduce this issue?

https://github.com/user-attachments/assets/f78f274d-d54c-4798-bf33-2d80c413276f

**Comment by flaviadefaria** [comment]
This is weird, as you can see on my screenshot the chat was unpinned without any GBR. Now when I click the Concierge chat again it does get a GBR that I cannot make go away because I deleted the workspace related to it so maybe this is what needs fixing. 

Can you try the following steps to see if you run into the same issue?
- Create a new account in NewDot
- Delete the workspace without checking off the tasks
- Sing out and back in 
- Click the Concierge

**Comment by flaviadefaria** [comment]
We decided to close this as an edge case given we might remove tasks as part of the onboarding.
