### ISSUE TITLE
 Search Filter - Search results for date filter are irrelevant

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52938
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com
2. Navigate to search
3. Press the Filters button
4. Select the Submitted filter and verify that you can select a date
5. Select the date that the report was submitted and make the search

## Expected Result:
Only reports submitted on the specified date are displayed

## Actual Result:
Search results for date filter are irrelevant, not only reports submitted on the specified date are displayed

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/11558285-331f-4812-82b2-8766704395ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
@IuliiaHerets do you have the reportIDs for the reports showing up? The date shown in that column is the date the report/transaction was created, not submitted, so it's possible that those were actually submitted after the dates in the filters. I do agree that this is confusing though (along with the other date filters) since we don't display those in the UI

**Comment by trjExpensify** [comment]
I've asked Isa if we can get this. :)

**Comment by IuliiaHerets** [comment]
@luacmartins Sorry for the delay, the tester is on vacation now, but I checked on my side and received the same behavior, search results for the date filter are irrelevant.
ReportIDs are:
- 6042319611351939,
- 5479959859441864.
I used the account applausetester+ihchat4_0101_01@applause.expensifail.com

https://github.com/user-attachments/assets/becde82c-4559-4474-ac6e-39e13e67cc3b

**Comment by luacmartins** [comment]
Yea, so I checked the data in OldDot and those reports don't have a submitted date and that's why they don't show up in your search. I wonder if we need to filter on something else

![Screenshot 2024-12-13 at 4 00 12 PM](https://github.com/user-attachments/assets/ca0d391d-0b4b-40f7-906c-7556b9dc4a68)

![Screenshot 2024-12-13 at 3 59 58 PM](https://github.com/user-attachments/assets/a5812720-e768-43a4-bf47-dbbaa7b4aafc)

**Comment by trjExpensify** [comment]
>Yea, so I checked the data in OldDot and those reports don't have a submitted date and that's why they don't show up in your search

Oh, because of instant submit and the report being created in the `processing` state, perhaps? 🤔

**Comment by luacmartins** [comment]
maybe, for some reason we don't update the `submitted` date on the DB. How should we filter reports in this scenario?

**Comment by trjExpensify** [comment]
Interesting. I wonder why not? The report is created submitted isn't it, so I'd have assumed the submitted date would be equal to created date for instant submit.

**Comment by luacmartins** [comment]
I'm not sure which flow is doing that. We do set the `submitted` date hen I test creating a `processing` report in NewDot. So it must be some other flow that's skipping that. I'll have to investigate.

**Comment by luacmartins** [comment]
Ok, so I solved one mystery. It seems like we are setting the submitted value, but OldDot is using `cachedData` so that's why it doesn't show up in my images above
<img width="527" alt="Screenshot 2024-12-19 at 12 03 27 PM" src="https://github.com/user-attachments/assets/92d0ba58-820d-4da0-a562-297133755880" />

Gonna request a CQ to see what the actual values are for reports 6042319611351939 and 5479959859441864.

**Comment by luacmartins** [comment]
Requested [here](https://github.com/Expensify/Expensify/issues/454963)

**Comment by luacmartins** [comment]
Ok, so the submitted data is correct and I also think that the search is correct. Here's the data for the report:

DATE(submitted)      reportID        
-------------------  ----------------
2024-12-03              5479959859441864
2024-12-08.             6042319611351939

The [video](https://github.com/Expensify/App/issues/53781#issuecomment-2542340444) shows we're searching for `submitted>2024-12-03 submitted<2024-12-08`, which yields no results since that filter is using `>` and `<`, which doesn't include the same date

**Comment by luacmartins** [comment]
So I think we can close this issue.

**Comment by trjExpensify** [comment]
Ohhh, interesting. I wonder how many people will be tripped up by that. You need `>=` to include those dates. Do we support it? 🤔

**Comment by luacmartins** [comment]
We do support it in the syntax, but the UI only uses `>`. We can change that if we think it's better

**Comment by luacmartins** [comment]
I'm gonna close this issue since the data is correct. We can create a new issue if we think that adding a `on` date to the date filters
