### ISSUE TITLE
Chat - The cursor is displayed at the beginning when you edit a message.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53797]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with the new account.
3. Create a workspace and go to the #Admin room of the WS.
4. Write a message and perform the function to edit the message.

## Expected Result:
The cursor should always be displayed at the end of the message.

## Actual Result:
This only happens after interacting with the #Admin room. When editing a message sent, the cursor is displayed at the beginning. After you type a letter, the cursor returns to the normal position. This is reflected in the group's chats and threads as well.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ca39c094-ed09-4b81-a8be-620bc0b201c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the edit message input opens, the cursor is in the beginning of the message, but it should in the end of the message
### What is the root cause of that problem?
we did not consider this case here:
https://github.com/Expensify/App/blob/ccc1ddca270854b09871046d2061bf14c9e107bf/src/pages/home/report/ReportActionItemMessageEdit.tsx#L83
### What changes do you think we should make in order to solve the problem?
we can add this useEffect:
```
   useEffect(()=>{
        setSelection({
            start: draftMessage.length,
            end: draftMessage.length,
            positionX: draftMessage.length,
            positionY: draftMessage.length,
        });
    },[])
```

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing a message in the #Admin room or other group chats and threads, the cursor initially appears at the beginning of the message instead of the end.
### What is the root cause of that problem?
The issue is caused by how the selection state is initialized in the ReportActionItemMessageEdit.tsx file. 
https://github.com/Expensify/App/blob/ccc1ddca270854b09871046d2061bf14c9e107bf/src/pages/home/report/ReportActionItemMessageEdit.tsx#L109
### What changes do you think we should make in order to solve the problem?
Update the initial state of selection to set the cursor position at the end of the `draftMessage` by using its length. This ensures that the cursor appears at the correct position as soon as the edit input opens.
update this: 
https://github.com/Expensify/App/blob/ccc1ddca270854b09871046d2061bf14c9e107bf/src/pages/home/report/ReportActionItemMessageEdit.tsx#L109

to :

`    const [selection, setSelection] = useState<TextSelection>({start: draftMessage.length, end: draftMessage.length, positionX: 0, positionY: 0});`

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor is at the beginning of the message if we open the admins room from the workspace profile page.

### What is the root cause of that problem?
The root cause of the issue is similar to https://github.com/Expensify/App/issues/46095. This is caused by the active focus traps that prevents the focus event to be received by the composer. You can read more detail on that root cause [here](https://github.com/Expensify/App/issues/46095#issuecomment-2248239994).

The different thing in this issue is, we already pause the focus trap if the screen isn't focused.
https://github.com/Expensify/App/blob/8981081bed8fb8a07f8797d49af2797332c9259d/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L41

In this case, the screen that has the active focus trap is the workspace full screen navigator. When we open the workspace profile share page, the workspace full screen navigator focus trap is paused. When we click the #admins room link, the RHP is closed and focus trap automatically unpause the previous focus trap, which is the workspace full screen navigator focus trap.
https://github.com/focus-trap/focus-trap/blob/f85c73ac36553d952a8e03d1033b35544247caa0/index.js#L28-L36
https://github.com/focus-trap/focus-trap/blob/master/CHANGELOG.md#400

### What changes do you think we should make in order to solve the problem?

We don't want the workspace full screen navigator focus trap to be unpaused when the RHP is closed because the screen is still blurred. We have 2 options.

First, instead of pausing the focus trap when the screen is blurred, we can deactivate it. We can return `isFocused` here (or we can do it only for FullScreenNavigator to be very safe).
https://github.com/Expensify/App/blob/8981081bed8fb8a07f8797d49af2797332c9259d/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L35-L36

If the focus trap is deactivated, unpause doesn't do anything.
https://github.com/focus-trap/focus-trap/blob/f85c73ac36553d952a8e03d1033b35544247caa0/index.js#L1037-L1040


Second, we can add a new option to the `focus-trap` repo to not automatically pause/unpause the focus-trap when a focus-trap is activated/deactivated.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


N/A

**Comment by stephanieelliott** [comment]
Hm, I'm not able to repro this -- it's working on Safari and Chrome for me.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/6e159441-62fd-4597-b9e7-780edfce82e4">

Either way, I think this is not really impacting users in a negative way and not worth prioritizing a fix. Gonna close but add the label in case we want to address cursor consistency as a whole in the future

**Comment by bernhardoj** [comment]
@stephanieelliott you need to open the #admins room from the workspace share page.
<img width="1239" alt="Screenshot 2024-12-11 at 14 34 34" src="https://github.com/user-attachments/assets/b913b20b-13a4-4d18-a29e-5f2fc7777e8d">

The issue is not only about the cursor being shown at the end of the text but also:
1. The cursor moves to the end on every character we type even though we put the cursor on other positions
2. The composer's green border is missing
3. This happens to the main composer too
4. TAB-ing doesn't work at all

https://github.com/user-attachments/assets/3e1277a7-d486-4278-ab2d-7ebdbe797d6b

**Comment by bernhardoj** [comment]
@stephanieelliott can you recheck this one, please?
