### ISSUE TITLE
[HOLD for payment 2024-12-19] Search - Search query "status:" is always "status:all" when the status type is changed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh0112006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Click on the search icon on the top right.
4. Click Search in <DM name>.
5. Type anything and hit Enter.
6. Note that the search query shows "status:all".
7. Change the status type.

## Expected Result:
The search query "status:" will update accordingly when the status type is changed (production behavior).

## Actual Result:
The search query "status:" is always "status:all" when the status type is changed.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d16138fa-4749-4d91-851d-4ffeaf010c6b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by IuliiaHerets** [comment]
Production 

https://github.com/user-attachments/assets/39bf4f41-1819-4b03-9dbd-02d0047b4c5e

**Comment by techievivek** [comment]
Not a blocker but definitely a regression. CC @luacmartins any idea about this regression?

**Comment by ChavdaSachin** [comment]
Notably it is working as expected on narrow layout, if it helps...

**Comment by Kicu** [comment]
Please assign me and I will handle this.
I work for SWM I have introduced multiple changes to Search input over the past couple of days, so I have a lot of context.

**Comment by Kicu** [comment]
This was a simple regression, fixed here: https://github.com/Expensify/App/pull/53859

**Comment by luacmartins** [comment]
Thanks @Kicu

**Comment by ikevin127** [comment]
I require payment here as C+ reviewer of PR https://github.com/Expensify/App/pull/53859.

**Comment by luacmartins** [comment]
Thanks for the ping @ikevin127! Assigned you to the issue

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR DEC 19

- Fix: @Kicu - no payment required
- PR Review: @ikevin127 [$250 if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/105357137)

@ikevin127 The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed. Please copy/paste the BugZero Checklist from [here](https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/BUGZERO_CHECKLIST.md) into a new comment on this GH and complete it.

**Comment by ikevin127** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/53198#issuecomment-2546346062.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: **N/A**.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

1. Open Search via the search icon on the top right or `CMD + K` / `Ctrl + K` depending on platform.
2. Type anything and hit Enter.
3. Note that the search query shows `status:all`.
4. Change the status type (`Drafts`, `Outstanding`, `Approved`, etc).
5. Verify that the status type input query changes in accordance with the type selected in step (4).

Do we agree 👍 or 👎.

##

✅ Offer accepted, thank you!

**Comment by abekkala** [comment]
@ikevin127 payment sent and contract ended - thank you! 🎉
