### ISSUE TITLE
Invoices - Export button is present in invoice details RHP but invoice cannot be exported

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53846]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO

1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select a participant
4. Select the workspace connected to QBO as the sender
5. Send the invoice
6. Click on the invoice preview.
7. Click report header.
8. Click Export.
9. Note that Export option is available but the option does not allow to export invoices.
10. Have the invoice receiver pay the invoice.
11. Repeat Step 6 to 8.

## Expected Result:
Export button should be removed from report details RHP if invoices cannot be exported to QBO.

## Actual Result:
Export button is present in report details RHP but it does not allow invoices to be exported.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c1add3a4-1aa1-49b9-9ea7-d678de7f5bd5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoices - Export button is present in invoice details RHP but invoice cannot be exported

### What is the root cause of that problem?
We are not checking for `canBeExported` when showing the menu here
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/pages/ReportDetailsPage.tsx#L473-L476
### What changes do you think we should make in order to solve the problem?

We should display the menu if the report can be exported with the function we use here
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/pages/home/report/ReportDetailsExportPage.tsx#L41
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoices - Export button is present in invoice details RHP but invoice cannot be exported

### What is the root cause of that problem?
We are not checking for `canBeExported` when showing the menu here
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/pages/ReportDetailsPage.tsx#L473-L476
### What changes do you think we should make in order to solve the problem?

We should display the menu if the report can be exported with the function we use here
https://github.com/Expensify/App/blob/219dabf6a0a907f16aef543306c78fab172c3c4b/src/pages/home/report/ReportDetailsExportPage.tsx#L41
```
        if (policy && connectedIntegration && isPolicyAdmin && !isSingleTransactionView && isExpenseReport) {

```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Added [alternative](https://github.com/Expensify/App/issues/53846#issuecomment-2531519578) approach to allow invoice report exporting

**Comment by VictoriaExpensify** [comment]
@IuliiaHerets  I actually think it's fine for the export button to be present here. The message shown is very clear to the user why it cannot be exported, and I think removing the export button would create more confusion for the customer.

I don't think we need to do anything here
