### ISSUE TITLE
[HOLD for payment 2024-12-20] [HOLD for payment 2024-12-19] [$250] Search - Approve button becomes green when the held expense is selected via checkbox

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 53889
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Add approvals feature is enabled.
- Admin is the approver.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Click on the report header > Hold > Hold the expense.
6. Go to Search.
7. Note that Approve button is gray.
8. Select the expense via checkbox.

## Expected Result:
Approve button should remain gray as long as the expense is held.

## Actual Result:
Approve button becomes green when the held expense is selected via checkbox.
It turns gray when hovered in selected state.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f9544407-2f7b-418b-9c5f-2b4f5fd3f708

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866771543910403509</li>
        <li>Upwork Job ID: 1866771543910403509</li>
        <li>Last Price Increase: 2024-12-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approve button becomes green when the held expense is selected via checkbox.
It turns gray when hovered in selected state.

### What is the root cause of that problem?
 
We are setting button style with `styles.buttonSuccessHovered` if this row is selected [here](https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/ActionCell.tsx#L95)

https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/ActionCell.tsx#L95

even though we have set `shouldUseSuccessStyle` to false if `isOnHold` [here](https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/TransactionListItemRow.tsx#L283)

https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/TransactionListItemRow.tsx#L283

### What changes do you think we should make in order to solve the problem?


We should update this [condition](https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/ActionCell.tsx#L95) to show style `buttonSuccessHovered` when `shouldUseSuccessStyle` as true

```
    const buttonInnerStyles = isSelected && shouldUseSuccessStyle ? styles.buttonSuccessHovered : {};
```

https://github.com/Expensify/App/blob/dac90e1f6fb00ba749e4ff9a6456f037e725e91d/src/components/SelectionList/Search/ActionCell.tsx#L95

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jayeshmangwani** [comment]
@nkdengineer Your change will also remove the button background. Please check the SS
<img width="1139" alt="Screenshot 2024-12-11 at 15 15 56" src="https://github.com/user-attachments/assets/48439c26-bcb6-4d3f-8f88-ef94b3f5ab63">

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Approve button becomes green even though it's on hold when it's selected.

### What is the root cause of that problem?
When the item is selected, we always use the `buttonSuccessHovered` style even though `shouldUseSuccessStyle` is false.
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ActionCell.tsx#L95-L104

### What changes do you think we should make in order to solve the problem?

When the item is selected but `shouldUseSuccessStyle` is false, we should use `buttonDefaultHovered`, just like the View action.
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ActionCell.tsx#L81

```
const buttonInnerStyles = isSelected ? shouldUseSuccessStyle ? styles.buttonSuccessHovered : styles.buttonDefaultHovered : {};
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

**Comment by jayeshmangwani** [comment]
What significant difference is in your Propsoal @Krishna2323  then @bernhardoj 's propsosal ,I have tested it and it worked fine

**Comment by jayeshmangwani** [comment]
@Krishna2323 Could you provide an example where you think that the above condition might fail?

**Comment by jayeshmangwani** [comment]
No issues, thanks for your proposal 🙌

**Comment by Gonals** [comment]
@bernhardoj, all yours! This is a deploy blocker, so let's get it fixed ASAP!

**Comment by bernhardoj** [comment]
PR is ready

cc: @jayeshmangwani

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Approve button becomes green when the held expense is selected via checkbox

### What is the root cause of that problem?
There are two problems right now.
1. Wrong button style is used when item is selected and expense is held

When the item is selected, we always use the buttonSuccessHovered style even though shouldUseSuccessStyle is false.

https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ActionCell.tsx#L95-L106

2. currently we use defaultHover style when item is selected to extinguish the button color from background color due which button does not change style when it's hovered and the button looks disabled.

### What changes do you think we should make in order to solve the problem?
There are Two case to be handled here.
1. Item is selected and expense is not on held - Currently we use successHover style here, due which button would not change style when hovered and looks in-interactive.

- So we should instead use default success style even when item is selected and use success hover style when button is hovered.

2. When item is selected and expense is on hold - here default button style and selectItem styles has same BG color, so we should use defaultHovered style when item is selected and create a new style 1 shade darker for hover to keep button looking interactive.

So make following changes here,
```js
    const buttonInnerStyles = isSelected && !shouldUseSuccessStyle && styles.buttonDefaultHovered ;
    return (
        <Button
            text={text}
            onPress={goToItem}
            small
            style={[styles.w100]}
            innerStyles={buttonInnerStyles}
            isLoading={isLoading}
            success={shouldUseSuccessStyle}
            isDisabled={isOffline}
            hoverStyles={isSelected ? shouldUseSuccessStyle ? styles.buttonSuccessHovered : styles.buttonSelectedHover : {}}
        />
    );
```
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ActionCell.tsx#L95-L106

and add this style here
```js
        buttonSelectedHover: {
            backgroundColor: theme.buttonPressedBG,
            borderWidth:0,
        },
```
https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/styles/index.ts#L659

Similar logic should be applied [here](https://github.com/Expensify/App/blob/c1454f772b8b780e015c01c1bffc4669d5383a78/src/components/SelectionList/Search/ActionCell.tsx#L81-L92) as well

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment]
@jayeshmangwani I understand this is a blocker issue but do you mind taking a look at my proposal.
Thank You.

**Comment by ChavdaSachin** [comment]
## Result comparison

Please notice button interactiveness

<details><summary> Currently Selected Proposal </summary>

https://github.com/user-attachments/assets/b077b0da-dccd-4df3-9663-29c5cbb4aa3a

</details>
<details><summary> My Proposal </summary>

https://github.com/user-attachments/assets/613173bc-c622-4a3a-a7a8-d870646414ad


</details>

**Comment by luacmartins** [comment]
btw this was likely a regression from https://github.com/Expensify/App/pull/53117.

**Comment by RachCHopkins** [comment]
@jayeshmangwani can you complete the checklist so that I can get the payment organised, please?

**Comment by jayeshmangwani** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [x] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/53117#issuecomment-2552811937

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A


## Regression Test Proposal
### Precondition:

- The approvals feature is enabled.
- The user is an admin and designated as the approver.


### Test:


1. Go to the Workspace Chat.
2. Submit an expense.
3. Open the Transaction Thread for the submitted expense.
4. Click on the Report Header > Hold > Hold the Expense.
5. Go to Search.
6. Verify that the Approve button should appear gray by default.
7. Verify that After selecting the expense using the checkbox, the Approve button should remain gray as long as the expense status is "Held"


Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment]
@RachCHopkins Yes, the checklist is completed! 🙌

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @bernhardoj to be paid $250 NewDot manual request
- Contributor+: @jayeshmangwani to be paid $250 NewDot manual request

Upwork job [here](https://www.upwork.com/jobs/~021866771543910403509)

**Comment by RachCHopkins** [comment]
Contributors are ready to request payment, there are no contracts to complete, and the Upwork post has been closed.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
