### ISSUE TITLE
Web - QBO - Changing the QBO export dropdown option in report details changes it for other reports

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5324684&group_by=cases:section_id&group_id=309135&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to QBO
7. Wait for the sync to finish (refresh the browser if it's stuck at importing data)
8. Navigate to the workspace chat
9. Submit a manual expense with any amount, merchant, and category
10. Pay the expense "elsewhere"
11. Submit another manual expense with different amount, merchant, and category
12. Pay the expense "elsewhere"
13. Click on the second expense
14. Click on the QBO export dropdown arrow
15. Click on "Mark as manually entered"
16. Navigate back to the workspace chat

## Expected Result:
It shouldn't change for older reports.

## Actual Result:
Changing the QBO export dropdown option in report details changes it for other reports too.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2d04b0c6-8973-4eda-b2ea-bdd27b13006b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
This looks like expected behavior to me.

To summarize:

You have a report with a single expense on that report. You mark that expense as paid, but it hasn't been exported yet. You now create a second expense, which is contained on the same report. You mark that expense as paid, but it hasn't been exported yet. You now have two expenses on a report, and that report is waiting to be exported.

You mark the report as exported, which exports _all_ expenses contained within the report that have not been exported yet. Given you have two expenses that have not been exported, I would expect both of those expenses to be exported, and their export status should be updated.
