### ISSUE TITLE
[$250] Track distance - Not here page opens after submitting track distance expense to new workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53995]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** dnfioffdjojdfoidfjod@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Account has no workspace (new account).

1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a distance expense.
4. Click Share it with my accountant.
5. Click Rate.
6. Select any rate.
7. Click Submit.

## Expected Result:
The track distance expense is submitted to the workspace chat.

## Actual Result:
Not here page opens after submitting track distance expense to a new workspace.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/79f10339-bf2a-4a62-a219-2afd71bc8730

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867171525628939701</li>
        <li>Upwork Job ID: 1867171525628939701</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by Julesssss** [comment]
I believe this is the backend error: 

<img width="1234" alt="Screenshot 2024-12-12 at 10 30 09" src="https://github.com/user-attachments/assets/1600c532-78c3-4868-90f8-ba0979780c0e" />

`UpdateMoneyRequestDistanceRate` fails because `customUnitRateID` is passed, but is missing necessary fields. The transactionNVPs json must include `customUnit` and `customUnit.name` must be `Distance.

**Comment by Julesssss** [comment]
I'm not seeing any recent changes on the backend. There is a single App PR on the checklist related to distance customUnits, which I have [commented](https://github.com/Expensify/App/pull/51517#issuecomment-2538559698) on.

**Comment by Julesssss** [comment]
Thanks @paultsimura. That backend PR only modified tests unfortunately, so I don't think that can be the cause.

**Comment by neil-marcellini** [comment]
> Thanks @paultsimura. That backend PR only modified tests unfortunately, so I don't think that can be the cause.

It's linked to an Auth PR, which did make changes. @paultsimura sounds like we're going to revert this one since the error isn't reproducible on production, but is after our PR. The problem might very well be on the backend but this way it's not possible for users to encounter it until we fix it.

Would you please explain the root cause on the original issue. Any idea what's causing a problem on the backend or what error is returned? I haven't investigated myself yet but I can later.

**Comment by Julesssss** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1734083542675209).

**Comment by isagoico** [comment]
Retest was a pass! 

https://github.com/user-attachments/assets/298b9fbf-ff84-48df-b3a1-9e77390f2844

**Comment by mallenexpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mallenexpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>
