### ISSUE TITLE
Copilot - Error displayed is inconsistent in copilot page after entering invalid magic code

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54045]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.75-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team
**Device used:** Redmi note 10s
**App Component:** User Settings

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with unverified gmail account
3. Go to settings - security - add copilot
4. Enter a mail address- full access
5. Tap add copilot 
6. Try entering invalid magic code 
7. Go back to previous page and again enter invalid code 
8. Repeat this 6 times
9. On 6th time, magic code not sent error displayed
10. Enter invalid code
11. Note 2 errors displayed in the page
12. Log out from site
13. Login another gmail unverified account
14. Go to settings - security - add copilot
15. Enter a mail address- full access
16. Tap add copilot 
17. Enter invalid magic code
18. Close the error 
19. Repeat entering invalid magic code , closing the error and tapping verify button for 10times

## Expected Result:
Error displayed must be consistent in copilot page

## Actual Result:
On entering invalid magic code every time from previous page, on sixth time 2 errors displayed, but entering invalid code from the same magic code page only one error is shown after trying 10 times also.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/be4e3259-d813-4b21-8ee7-47e449ca8807

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
I believe this is not an issue; rather, it is the expected behavior due to the following reasons:

**Case 1: Returning to the Previous Page**
When the user navigates back to the previous page and clicks the **Add Copilot** button again, a new magic code is sent to the user. This can be confirmed by the 30-second timer displayed beneath the magic code input field, indicating a fresh magic code has been generated.
If the user repeats this process multiple times, it eventually crosses a predefined limit, triggering two error messages:

1. One for exceeding the magic code request limit.
2. Another for entering an incorrect magic code.

**Case 2: Staying on the Magic Code Input Page**
When the user repeatedly enters an incorrect magic code on the same page, no new magic code is sent (even after multiple attempts). Hence, the error for exceeding the magic code request limit does not apply. Only the "incorrect magic code" error is displayed, which is consistent with this scenario.

In both cases, the error messages reflect the intended logic of the flow. Therefore, the observed behavior aligns with the expected outcome.

**Comment by johncschuster** [comment]
Nice callout, @Shahidullah-Muffakir! I agree with you!
