### ISSUE TITLE
[HOLD for payment 2025-01-02] Patch failed to be applied but succeeded message is shown

### ISSUE THREAD

**Issue by gedu** [Expensify/App#54108]
![Screenshot 2024-12-13 at 12 44 02](https://github.com/user-attachments/assets/7aec6da9-c5b2-4754-ba5b-fac957f655c5)

Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1734090304591509

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by fabioh8010** [comment]
cc @mountiny

**Comment by noumantahir** [comment]
Two relevant patch failures...

- [ ] react-native-community/netinfo turbomodule patch
- [ ] react-navigattion-core patch

<img width="728" alt="Screenshot 2024-12-13 at 17 47 40" src="https://github.com/user-attachments/assets/ef47ce11-52a7-4401-82a8-c684a042bd77" />

<img width="730" alt="Screenshot 2024-12-13 at 16 57 18" src="https://github.com/user-attachments/assets/df6b9e76-dd84-44bc-84ee-d3f8f7f96cee" />

**Comment by mountiny** [comment]
@gedu I have seen couple people being slowed down by this, would you be able to prioritize this issue please?

**Comment by gedu** [comment]
@pac-guerreiro Will take a look at this, @mountiny you can assign the issue to him

**Comment by pac-guerreiro** [comment]
@gedu @mountiny PR is live now - https://github.com/Expensify/App/pull/54355 😄

**Comment by pac-guerreiro** [comment]
I'll be away until January 2nd but someone should take care of my work 😄 Happy holidays! 🎉

**Comment by pac-guerreiro** [comment]
Waiting for @mountiny to review the PR

**Comment by mountiny** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>
