### ISSUE TITLE
Onboarding Flow - "Free trial ended" is missing from the report after running snippet

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.75-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5341760
**Email or phone of affected tester (no customers):** rybkina+121224@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac/Chrome 14.4
**App Component:** User Settings

## Action Performed:
Pre: New user has created a new workspace and has started their onboarding checklist and the free trial has started.

1. Login as the account that has a free trial
2. Open console and enter snippet: Onyx.merge('nvp_private_lastDayFreeTrial', '<today's date time>');
E.g: if today's date is 8/26/2024 it would look like: Onyx.merge('nvp_private_lastDayFreeTrial', '2024-08-26 01:01:00');

## Expected Result:
This snippet will end the free trial.

## Actual Result:
"Free trial ended" is missing from the report after running snippet.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a942c327-5941-489f-92a0-53cff20760f8

<img width="998" alt="bug" src="https://github.com/user-attachments/assets/f987400c-3dde-41fa-9960-adc8fa47d5c1" />

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I can't get the script to run, it gives me this error:

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/d919643f-8283-4718-9f7f-e550816b95ea" />

**Comment by trjExpensify** [comment]
Okay, I was able to execute that on staging. I don't get the trial end message either: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/b69845a0-6c2a-4077-8b62-4dd344baa2d3" />

CC'ing @chiragsalian @MitchExpensify for 👀 I suspect this is backend, and needs to be `internal`?

**Comment by chiragsalian** [comment]
> I can't get the script to run, it gives me this error:

That looks really weird. i think something is just borked in your UI. Try to clear cache and refresh. Running onyx methods should work.

> Actual Result:
> "Free trial ended" is missing from the report after running snippet.

@vincdargento, so in the video i noticed you used month as `13` i.e., `2024-13-12` (its format is yyyy-mm-dd), i wouldn't expect that work since its an invalid month 😅 can you try again using today's or a past UTC date with a past timestamp like `2024-12-16 00:00:00`

**Comment by chiragsalian** [comment]
Oh onyx methods dont work on prod. TIL. Oh i guess for safety reason we don't allow it on prod, cool.
whoops i missed your second comment.

> but you can see they do a correct date initially

Yeah but when they do the correct date the free trial banner goes away so things looks good to me. 
Maybe there is some confusion with the expectation here.

The snippet will end the free trial in the UI, i.e., hide the "free trial: 7 days left" banner from the report, LHN and subscription page. 
The snippet will not send a free trial end message to any report. This message is normally sent via a bedrock job that's queued for the day the free trial ends. To see the message, internally we need to,
1. Run a query to set free trial end message as expired so that's its saved in the backend
2. Run the bedrock job to run now.
and that's not something QA can do.

I check the test rail and i see this,
> Verify there is a message in the DM with the onboarding checklist that reads that your free trial has ended and to add a payment card

We can remove that because it won't work. I doubt it had ever worked unless we had optimistic code for it, which IMO would be hacky and unnecessary for this scenario. The rest of the test rail steps LGTM, we can maybe update this,
> Click “Add payment card” in Concierge DM message 

to - Go to the subscription page.

Let me know if I'm misunderstand something here.

**Comment by trjExpensify** [comment]
Oh, interesting. So how do we test this email is being received? 🤔 It's like the pull back to put a card down, I'm hesitant to not test it at all.

**Comment by chiragsalian** [comment]
> So how do we test this email is being received?

Currently, it can only be tested internally. We could build something out though. Like if the email contains `freetrialendtest`, then set NVP to end in say 3 minutes and the job to be sent in 3mins, instead of 7 days for both. This way QA can test it out. But we'll need to code this out.

**Comment by trjExpensify** [comment]
Maybe taking a step back for a sec. On this: 

>The snippet will not send a free trial end message to any report. This message is normally sent via a bedrock job that's queued for the day the free trial ends. 

The snippet sets the `private_lastDayFreeTrial` NVP. Does that not queue up a bedrock job at that time then?

**Comment by chiragsalian** [comment]
oops i typed this out yesterday and forgot to click send.

> The snippet sets the private_lastDayFreeTrial NVP. Does that not queue up a bedrock job at that time then?

Nope, anything run via onyx.merge is purely just superficial for the front end. It usually does not trigger API requests or make any backend updates. A refresh or signout/signin, would clear the changes made by manually running onyx.merge.

The bedrock job is queued when free trial begins like so,
1. User performed a billable action. Say they submitted an expense. 
2. Auth sets free trial NVPs in the db and tells PHP API layer a free trial started, it gives us the free trial start and end date.
3. A bedrock job is queued for the free trial end date. This is usually for 7 days later.
4. Any onyx.merge snippets run on the front end does not update the actual NVP in the db nor on the bedrock job.

**Comment by trjExpensify** [comment]
Dang, super interesting! Then I think we should probably do something [like this](https://github.com/Expensify/App/issues/54106#issuecomment-2546712219). 

@ryanschaffer to loop you in on this for visibility as you're working on free trial stuff. The message we send NewDot users when a free trial ends containing the button to add a payment card isn't currently being tested. There isn't a great way for QA to force that to send and we'd need to do something [like this](https://github.com/Expensify/App/issues/54106#issuecomment-2546712219). Given the importance of this pullback to add a billing card, do you agree it's worth investing in?

**Comment by JmillsExpensify** [comment]
I think testing the core flows in conversion is time well spent.

**Comment by trjExpensify** [comment]
Cool, let's do it then @chiragsalian! :)

**Comment by chiragsalian** [comment]
okay sounds good, I'll close this issue and have created another one for myself - https://github.com/Expensify/Expensify/issues/455376.
I'll set its priority to weekly but if you guys feel like its priority should change let me know.
