### ISSUE TITLE
[HOLD for payment 2025-01-02] [HOLD for payment 2024-12-30] [$500] Onboarding flow is not showing upon first sign in

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#54322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
Break down in numbered steps

1. Sign into a new account
2. The onboarding modal is not showing
3. Refresh the page
4. The modal is shown

## Expected Result:
Describe what you think should've happened

The modal should be shown first upon signing the user should not be allowed to skip it

## Actual Result:
Describe what actually happened

The user is not presented with the modal

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2cf46102-ff72-47d7-8711-110d8cc29fa8

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021869459467806061602</li>
        <li>Upwork Job ID: 1869459467806061602</li>
        <li>Last Price Increase: 2024-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 105391259</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by mountiny** [comment]
I will take it over

**Comment by mountiny** [comment]
@trjExpensify has confirmed that the OpenApp returns the `hasCompletedGuidedSetupFlow` as false so this seems to be app issue indeed

**Comment by trjExpensify** [comment]
Yep, here's a vid of that:

https://github.com/user-attachments/assets/9e0231f8-3e8b-43cc-be9d-fddeb37fdd65

**Comment by Shahidullah-Muffakir** [comment]
Working on it here, https://github.com/Expensify/App/issues/53724

**Comment by Shahidullah-Muffakir** [comment]
**In case this helps others pinpoint the root cause:**

I tested on all supported platforms, and the onboarding flow modal works correctly on mWeb, native, and desktop.

However, on macOS with Chrome and Safari, the onboarding modal does not appear when the browser window is large., if we refresh the page after signup, the modal appears as expected. or If I reduce the window width (narrowLayout) before starting the signup, the modal works fine on both browsers.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Describe what actually happened

### What is the root cause of that problem?
After the user signs in, we must wait for the `onboarding` data to be loaded before starting an onboarding flow here.

https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/hooks/useOnboardingFlow.ts#L71-L74

And we will reset the root state here

https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/libs/actions/Welcome/OnboardingFlow.ts#L47-L50

But at this time, we also have a logic to change the navigation on the `ReportScreen` here
https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/pages/home/ReportScreen.tsx#L154

Then the onboarding is not added to the navigation stack which causes the bug occur and that is the reason why it only happens on web/desktop
### What changes do you think we should make in order to solve the problem?
We should return early here if the onboarding data is loading

https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/pages/home/ReportScreen.tsx#L143

Or we can use `Navigation.isNavigationReady` here
https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/pages/home/ReportScreen.tsx#L163

or here to execute the logic when the navigation is ready

https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/libs/actions/Welcome/OnboardingFlow.ts#L47-L50

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix onboarding modal in macOS Chrome/Safari.

### What is the root cause of that problem?
1. In the `hasCompletedGuidedSetupFlowSelector` function, when the `onboardingFlow` object is empty or `hasCompletedGuidedSetupFlowSelector` is undefined, we are returning `true`:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/onboardingSelectors.ts#L14-L20
2. This results in the `useOnboardingFlowRouter` hook returning `true`:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L243
   and as the `isOnboardingCompleted` is `true`, this condition fails:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L538-L542
   Hence, the Onboarding Modal is not shown.

When the onboardingFlow is available in the hasCompletedGuidedSetupFlowSelector and the hasCompletedGuidedSetupFlowSelector return false, the AuthScreen is not re-rendering the https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L538-L542 part.
### What changes do you think we should make in order to solve the problem?

We can wrap this part https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L538-L542 in useCallback , and when the isOnboardingCompleted updates, it will be updated as:

```
    const onBoardingModal = useCallback(() => {
        // Dynamically add onboarding screen based on state
        if (isOnboardingCompleted) {
            return null;
        }
            return (
                <RootStack.Screen
                    key={NAVIGATORS.ONBOARDING_MODAL_NAVIGATOR}
                    name={NAVIGATORS.ONBOARDING_MODAL_NAVIGATOR}
                    options={{...rootNavigatorOptions.basicModalNavigator, gestureEnabled: false}}
                    component={OnboardingModalNavigator}
                    listeners={{
                        focus: () => {
                            Modal.setDisableDismissOnEscape(true);
                        },
                        beforeRemove: () => Modal.setDisableDismissOnEscape(false),
                    }}
                />
            );
        
    }, [rootNavigatorOptions, isOnboardingCompleted]); 
```

and then user it here as :
`                {onBoardingModal()}
`

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

**Comment by s77rt** [comment]
@nkdengineer Thanks for the proposal but it doesn't answer why this works on mWeb?

**Comment by nkdengineer** [comment]
@s77rt On mWeb, we will land at LHN and then it will not have any other navigation executed when we call `startOnboardingFlow`.


https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/libs/actions/Welcome/OnboardingFlow.ts#L40

**Comment by s77rt** [comment]
@Shahidullah-Muffakir Thanks for the proposal. Your RCA is not correct. The onyx value is not the problem since the `startOnboardingFlow` gets called correctly.

**Comment by s77rt** [comment]
@nkdengineer Are you saying that after we reset the root, another navigation query (which comes from ReportScreen) overwrites the navigation stack?

**Comment by nkdengineer** [comment]
@s77rt Yes. That is the reason I think based on the last log from my side. But I can not prove more and verify it because `SignUpUser` returns error.

**Comment by nkdengineer** [comment]
@s77rt You're right. Seem like `navigationRef.resetRoot(navigationRef.getRootState())` is called unexpectedly when we login in web and do a navigation action like [here](https://github.com/Expensify/App/blob/0a1f843fa83a0f2ffb6a8708e6b3c30fa2cafad8/src/pages/home/ReportScreen.tsx#L163). I also tested by disabling this line and the onboarding modal appears

I think we can fix it by only calling `navigationRef.resetRoot(navigationRef.getRootState())` if `shouldUseNarrowLayout` is changed

```
const {shouldUseNarrowLayout} = useResponsiveLayout();
const prevShouldUseNarrowLayout = usePrevious(shouldUseNarrowLayout);

useEffect(() => {
    if (!navigationRef.isReady() || shouldUseNarrowLayout === prevShouldUseNarrowLayout) {
        return;
    }
    navigationRef.resetRoot(navigationRef.getRootState());
}, [prevShouldUseNarrowLayout, shouldUseNarrowLayout]);
```

https://github.com/Expensify/App/blob/5ebb9db5fb2ead724d9b452d92942c86fa31c872/src/libs/Navigation/AppNavigator/useNavigationResetRootOnLayoutChange.ts#L17

**Comment by mountiny** [comment]
I think there was bunch of changes in the navigation from the native stack and follow up fixes so I would not be surprisedif any of them caused this. At this point I would prefer a fix rather than a revert though and the solution from @nkdengineer sounds good. Are you able to raise a PR and we can test it there?

**Comment by nkdengineer** [comment]
@mountiny Sure.

**Comment by mountiny** [comment]
What is your ETA @nkdengineer ?

**Comment by nkdengineer** [comment]
I'm working on it now.

**Comment by nkdengineer** [comment]
@mountiny I can't test this locally because of the backend error. Can you trigger a build on this draft PR?

**Comment by s77rt** [comment]
@nkdengineer Let's start fresh on this issue. I don't think we found the root cause yet. I just realized that the `navigationRef.resetRoot` call is not the culprit, if it was then on refresh it shouldn't work either. This is in fact more related to onyx value not being available in time.

**Comment by s77rt** [comment]
Part of what @Shahidullah-Muffakir referenced makes sense here (deleted comment). I have been working on this for a while and the reason the navigation does not work is because the `getStateForAction` from the router returns `null`. I found that it does so only because the supplied routes contains `OnboardingModalNavigator` and that route does not exist as it's rendered conditionally here https://github.com/Expensify/App/blob/13700ca27674f85c71e67c98bf3d01746cfc36e4/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L538-L550 If it happens that the onyx value is not available from the beginning then the navigator will not be available either (at all).

**Comment by s77rt** [comment]
Yet, I still didn't find a clear reason on why this works on mWeb

**Comment by s77rt** [comment]
Hmm NVM The above seems to be a problem but not our problem

**Comment by s77rt** [comment]
Okay, I can confirm that the first theory of @nkdengineer is correct but it's not the `findLastAccessedReport` call that's causing the bug, it's this line that sets the `params` https://github.com/Expensify/App/blob/13700ca27674f85c71e67c98bf3d01746cfc36e4/src/pages/home/ReportScreen.tsx#L163

Here you can see the log where after "doing action" for the onboarding modal gives us the correct state but right after that state is overwritten

<img width="545" alt="Screenshot 2024-12-19 at 4 10 24 AM" src="https://github.com/user-attachments/assets/93411155-a752-42b2-98fb-88402ef6752d" />


If we comment offending line, here are the results

<img width="1728" alt="Screenshot 2024-12-19 at 4 13 24 AM" src="https://github.com/user-attachments/assets/a978e50e-509d-42b5-ab6b-3d25c64dbc7e" />

**Comment by s77rt** [comment]
By the look of it, this seems to be an upstream bug `setParams` shouldn't affect other screens

**Comment by nkdengineer** [comment]
> But at this time, we also have a logic to change the navigation on the ReportScreen here
>it's this line that sets the params

@s77rt That is what I said. The problem comes from the second time `setParams` is called

**Comment by nkdengineer** [comment]
@s77rt Confirmed the problem comes from the second `setParams` calls. I tested by reverting all previous changes and created a ref `lastAccessedReportIDRef`, set it here and return early if it exists then the onboarding works fine and no empty report bug.

https://github.com/Expensify/App/blob/66d09e062edb94b433f336efd43f71e9e222112d/src/pages/home/ReportScreen.tsx#L163

**Comment by nkdengineer** [comment]
Do you think it's a valid solution?

**Comment by nkdengineer** [comment]
Or we should reduce the dependency on this `useEffect` to prevent `setParams` is called two times.

**Comment by bernhardoj** [comment]
> Here you can see the log where after "doing action" for the onboarding modal gives us the correct state but right after that state is overwritten

I think this is what happen.

Looking at the [code](https://github.com/react-navigation/react-navigation/blob/5a8d0f65e0d118317417cf76749e6f28fc50c02a/packages/routers/src/BaseRouter.tsx#L14-L36), `setParams` returns a new state containing the routes (with the updated params) from the state that is passed to `getStateForAction`. But looks like the state passed to the function doesn't have the onboarding route.

```
return {
  ...state,
  routes: state.routes.map((r, i) =>
    i === index
      ? { ...r, params: { ...r.params, ...action.payload.params } }
      : r
  ),
};
```

Here, we pass the state to `getStateForAction` from the `nextState` variable.
https://github.com/react-navigation/react-navigation/blob/5a8d0f65e0d118317417cf76749e6f28fc50c02a/packages/core/src/useNavigationBuilder.tsx#L545-L551

The `nextState` initial value will be the same as `state`.

https://github.com/react-navigation/react-navigation/blob/5a8d0f65e0d118317417cf76749e6f28fc50c02a/packages/core/src/useNavigationBuilder.tsx#L477-L485

```
let state =
  // If the state isn't initialized, or stale, use the state we initialized instead
  // The state won't update until there's a change needed in the state we have initalized locally
  // So it'll be `undefined` or stale until the first navigation event happens
  isStateInitialized(currentState)
    ? (currentState as State)
    : (initializedState as State);

let nextState: State = state;
```

`state` can either be `currentState` or `intiailizedState`. `currentState` contains the updated state of each action and we expect `state` to contain the new state from the `resetRoot` action. But when we do the `resetRoot`, we set the `stale` to true.
https://github.com/Expensify/App/blob/154a485f35609cb51e655aad3dca9e3131f3b23e/src/libs/actions/Welcome/OnboardingFlow.ts#L47-L51

It makes `isStateInitialized(currentState)` return false, so `state` contains the `initializedState` value which doesn't have the onboarding route.
https://github.com/react-navigation/react-navigation/blob/5a8d0f65e0d118317417cf76749e6f28fc50c02a/packages/core/src/useNavigationBuilder.tsx#L355-L360

This can easliy be reproduced with this code.
```
<Pressable onPress={() => {
    navigationRef.resetRoot({routes: [{name: BottomTabNavigator}, {name: Report}, {name: Report}]});
    navigation.setParams({reportID: '1'});
}}>
  <Text>Test</Text>
</Pressable>
```

**Comment by blazejkustra** [comment]
Just FYI, we are looking into this issue with SWM's navigation experts. We suspect it comes from a PR where native stacks were introduced. We'll keep you updated

**Comment by s77rt** [comment]
The bug may simply be due to the nature of dispatching events being async:

```js
navigationRef.resetRoot({
    routes: [
        {
            name: 'BottomTabNavigator',
        },

        {
            name: 'OnboardingModalNavigator',
            path: '/onboarding',
        },
    ],
    index: 1,
});

console.log("rootstate", navigationRef.getRootState()); // <- This is not updated yet and contains the old state
navigation.setParams({report: 123}); // <- Thus this will also use the outdated state
```

**Comment by mountiny** [comment]
@adamgrzybowski @WojtekBoman Seems like the solution we applied for now is just a hot fix but the root cause is else where. Could you take this on to chase down the root cause? Thanks!

**Comment by mountiny** [comment]
PR being CPed, will be validated on the checklist

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [X] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/49937 (unknown exact cause but it's very likely that the bug is caused by this PR for switching to `PlatformStackNavigation`)

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: I don't think this is required here (QA test should pretty much cover this)

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    Bug requires regression test: No, a test already exists https://expensify.testrail.io/index.php?/cases/view/2990391

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by bfitzexpensify** [comment]
Payment summary:

$500 paid to @nkdengineer for contributor work ✅ 
$500 to be paid to @s77rt for C+ work

**Comment by JmillsExpensify** [comment]
$500 approved for @s77rt
