### ISSUE TITLE
Search - The Tax Rate filter does not display results when the query is manually entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/53688
**Issue reported by:**Applause - Internal Team

## Action Performed:
Preconditions:
User has at least one workspace with Taxes enabled.
The user has expenses with the tax rate that will be used to filter the results.
Steps:
1. Login to ND (can be Gmail or expensifail account)
2. Go to any chat or expense report
3. In the Search Router, enter a query using the Tax Rate filter, eg. tax-rate:"Tax Rate 1" and press Intro - or tap the Magnifier button in the keypad -

## Expected Result:
The Tax Rate filter displays results when the query is entered manually, similar to when the query is selected from Suggestions or entered in Filters (on the Reports tab)

## Actual Result:
The Tax Rate filter does not display results when the query is manually entered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ae4d0843-5189-422d-af82-e2fc6c08b159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax rate filter not working when entering filter manually.

### What is the root cause of that problem?
The query send to backend when we manually enter is different from when we search for tax rates
When we manually enter, it is:
```json
{"operator":"eq","left":"taxRate","right":"Tax Rate 1"}
```
When we select from suggestions, it is:
```json
{"operator":"eq","left":"taxRate","right":"id_TAX_RATE_1"}
```
due to this, the results are not visible when manually entering

### What changes do you think we should make in order to solve the problem?

We need to replace tax rate names with tax rate ids and similar replacement is being done for email-ids by [getQueryWithUpdatedValues](https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/libs/SearchQueryUtils.ts#L683) which calls [getUpdatedFilterValue](https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/libs/SearchQueryUtils.ts#L204) so, we need to update getUpdatedFilterValue and add logic to replace tax-rate names with their ids. 

https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/libs/SearchQueryUtils.ts#L204-L225

We need to add policy id as param for  getUpdatedFilterValue and  then add below code in the getUpdatedFilterValue function:
```js
    if (filterName === CONST.SEARCH.SYNTAX_FILTER_KEYS.TAX_RATE) {
        if (typeof filterValue === 'string') {
            return PolicyUtils.getTaxRateKey(filterValue, policyId)
        }

        return filterValue.map(taxRates => PolicyUtils.getTaxRateKey(filterValue, policyId)).flat()
    }
```

We will also need to add below policy utils to get tax rate id from the names

```js
function getTaxRateKey(name: string, policyId?: string) {
    if (policyId) {
        const policy = getPolicy(polictId)
        return getTaxRateKeyForPolicy(policy) ?? name
    }

    const taxRateKeys = []
    Object.values(allPolicies).forEach(policy => {
        const taxRateKey = getTaxRateKeyForPolicy(policy)

        if (taxRateKey) {
            taxRateKeys.push(taxRateKey)
        }
    })

    return taxRateKeys
}

function getTaxRateKeyForPolicy(taxRateName: string, policy: Policy) {
    if (!policy?.taxRates?.taxes) {
        return
    }

    return Object.entries(policy.taxRates.taxes)
    .find(([taxRateKey, taxRate]) => taxRate === taxRateName)?.[0]
}
```

Update [here](https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/libs/SearchQueryUtils.ts#L695) and [here](https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/libs/SearchQueryUtils.ts#L667) to pass policy id to getUpdatedFilterValue


### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We need to add unit tests for getQueryWithUpdatedValues to check if tax rates are being replaced. The new cases will check that tax rates are subsituted properly, tax rate ids are preserved properly and update the [existing](https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/tests/unit/Search/SearchQueryUtilsTest.ts#L59) tests for all subsitutions

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Tax Rate filter does not display results when the query is manually entered

### What is the root cause of that problem?

[`getUpdatedFilterValue`](https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L204) does not update the `taxRate` or `filterValue`,  in the search payload to its respective tax key or id, eg: `"Tax Rate 1"` should be converted to `id_TAX_RATE_1`

https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L200-L204

Therefore, the backend can not find any results because it searches the tax filter based on the tax IDs or keys instead of its name which is sent to [`/api/Search?`](https://www.expensify.com/api/Search?) in the built `jsonQuery`.

![Screenshot 2024-12-20 at 18 57 55](https://github.com/user-attachments/assets/daebc592-c669-4272-a88a-ad0352a064e7)

### What changes do you think we should make in order to solve the problem?


Convert the `filterValue` if the `filterName` is `CONST.SEARCH.SYNTAX_FILTER_KEYS.TAX_RATE` to the tax key by finding which tax key the `filterValue` belongs to.

Let's add the following statement [`getUpdatedFilterValue`](https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L204) over [here](https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L223)

```javascript
if (filterName === CONST.SEARCH.SYNTAX_FILTER_KEYS.TAX_RATE) {
        const allTaxRates = Object.entries(PolicyUtils.getAllTaxRates());
        if (typeof filterValue === 'string') {
            return (
                allTaxRates
                    .find(([taxRateName, taxRateKeys]) => {
                        return taxRateName === filterValue ? taxRateKeys : undefined;
                    })?.[1]
                    .at(0) ?? filterValue
            );
        }

        return filterValue
            .map(
                (value) =>
                    allTaxRates
                        .find(([taxRateName, taxRateKeys]) => {
                            return taxRateName === value ? taxRateKeys : undefined;
                        })?.[1]
                        .at(0) ?? value,
            )
            .flat();
    }

```

Optionally, we can create a function to handle the update and simplify [`getUpdatedFilterValue`](https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L204).

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


Test [`getUpdatedFilterValue`](https://github.com/Expensify/App/blob/8a4011d5c90048b9f9733ca1684786bc2e8fa52e/src/libs/SearchQueryUtils.ts#L204) with other search filters and values.

**Comment by RachCHopkins** [comment]
@lanitochka17 I don't understand this bug - how does a customer know to do this:

> In the Search Router, enter a query using the Tax Rate filter, eg. tax-rate:"Tax Rate 1"

i.e how can we guarantee that the query is correct without the list of filters - I tried and clearly didn't get it right. 

We don't have any guidance online for how users take this action. I don't think this is something that we need to focus on right now, as we have no current plans for adding this to our help docs.

**Comment by jaydamani** [comment]
We already do something similar for from/to filters where from:jay@mail.com will work even if you press enter without using suggestions and the search router is relatively new so maybe this is worth fixing
cc: @luacmartins as they manage search related stuff

**Comment by luacmartins** [comment]
The reason it works for emails is that email is a unique identifier. The same cannot be said about other filter/values, e.g. tags, categories, tax rates, etc so in those cases we need to rely on autocomplete.

**Comment by jaydamani** [comment]
I understand now, thanks for the confirmation.
