### ISSUE TITLE
Expense - Category RHP loads infinitely when opening category page in 1:1 expense flow

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.78-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Click + > Submit expense > Manual.
4. Enter amount > Next.
5. Click Description on confirmation page.
6. Modify the link "description" to "category".
7. Hit Enter.

## Expected Result:
Not here page will open (as in PR #37747)

## Actual Result:
Category RHP opens and loads infinitely.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/36129920-7224-45af-bc74-eda86e85bbcc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category RHP loads indefinitely in 1:1 flow
### What is the root cause of that problem?

We do not show not found page in category RHP when report does not have a policy. Same issue could occur if the categories are disabled for the workspace.

https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/pages/iou/request/step/IOURequestStepCategory.tsx#L86

### What changes do you think we should make in order to solve the problem?


Add condition to show not found page if `report.policyId` is not present. Additionally, we can also show not found page if workspace does not have categories enabled.

#### Current code:
https://github.com/Expensify/App/blob/8fb9cf7c04fdff9cf06548a6be641aa3cbb44dee/src/pages/iou/request/step/IOURequestStepCategory.tsx#L86

#### Updated code
if we only check that report is in workspace:
```js
const shouldShowNotFoundPage = !report?.policyId || (isEditing && (isSplitBill ? !canEditSplitBill : !ReportActionsUtils.isMoneyRequestAction(reportAction) || !ReportUtils.canEditMoneyRequest(reportAction)));
```

if we also want to check that categories are enabled:
```js
const shouldShowNotFoundPage = !policy?.areCategoriesEnabled || (isEditing && (isSplitBill ? !canEditSplitBill : !ReportActionsUtils.isMoneyRequestAction(reportAction) || !ReportUtils.canEditMoneyRequest(reportAction)));
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

No extra tests are needed for this

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category RHP opens and loads infinitely.

### What is the root cause of that problem?

The `shouldShowNotFoundPage` is `false` if the policy is personal policy or it's `undefined`

https://github.com/Expensify/App/blob/58539c5f38dff838c3029af4a7b89f58a7213442/src/pages/iou/request/step/IOURequestStepCategory.tsx#L86

Then because `policyCategories` is `undefined`, the loading page appear
https://github.com/Expensify/App/blob/58539c5f38dff838c3029af4a7b89f58a7213442/src/pages/iou/request/step/IOURequestStepCategory.tsx#L96
### What changes do you think we should make in order to solve the problem?
We should add a condition to update `shouldShowNotFoundPage` to `true` if the policy is not group policy. Because we can enable the category feature with the empty state then we should only display not found page if the policy doesn't have policy feature (policy isn't group policy)

```
const isGroupPolicy = ReportUtils.isReportInGroupPolicy(report) || ReportUtils.isGroupPolicy(policy?.type ?? '');
const shouldShowNotFoundPage = !isGroupPolicy || (isEditing && (isSplitBill ? !canEditSplitBill : !ReportActionsUtils.isMoneyRequestAction(reportAction) || !ReportUtils.canEditMoneyRequest(reportAction)));
```
https://github.com/Expensify/App/blob/58539c5f38dff838c3029af4a7b89f58a7213442/src/pages/iou/request/step/IOURequestStepCategory.tsx#L86


https://github.com/Expensify/App/blob/58539c5f38dff838c3029af4a7b89f58a7213442/src/pages/iou/request/step/IOURequestStepCategory.tsx#L77

That is how we do [here](https://github.com/Expensify/App/blob/58539c5f38dff838c3029af4a7b89f58a7213442/src/pages/iou/request/step/IOURequestStepTag.tsx#L70)
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU category page opens but shows infinite loading on a DM IOU flow.

### What is the root cause of that problem?
When we open the category page from a DM IOU, the policy categories will be undefined and if we are online, then the loading will show.
https://github.com/Expensify/App/blob/e94df0f79443f99b33be867fec8637c6a9aa5821/src/pages/iou/request/step/IOURequestStepCategory.tsx#L96

The not found page doesn't show because we don't have any check whether the user can access the category field page or not.
https://github.com/Expensify/App/blob/e94df0f79443f99b33be867fec8637c6a9aa5821/src/pages/iou/request/step/IOURequestStepCategory.tsx#L86

### What changes do you think we should make in order to solve the problem?

We can wrap the page with `AccessOrNotFoundWrapper` which handles the check whether the user can access it or not. For category page, it will look like this:
```
return (
    <AccessOrNotFoundWrapper 
        policyID={policy?.id}
        iouType={iouType}
        featureName={CONST.POLICY.MORE_FEATURES.ARE_CATEGORIES_ENABLED}
    >
        ...
    </AccessOrNotFoundWrapper>
```

This will prevent the user to access the page if:
1. The IOU flow is a DM IOU
2. The IOU is a workspace request, but the categories feature is disabled

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/A

### What alternative solutions did you explore? (Optional)
Or even better, we can copy the condition whether to show the field or not from the confirmation list field to each step page.

https://github.com/Expensify/App/blob/e94df0f79443f99b33be867fec8637c6a9aa5821/src/components/MoneyRequestConfirmationListFooter.tsx#L311
https://github.com/Expensify/App/blob/e94df0f79443f99b33be867fec8637c6a9aa5821/src/components/MoneyRequestConfirmationListFooter.tsx#L367
https://github.com/Expensify/App/blob/e94df0f79443f99b33be867fec8637c6a9aa5821/src/components/MoneyRequestConfirmationListFooter.tsx#L417

etc.

We can create a util function for the condition that is more complex.

**Comment by slafortune** [comment]
https://new.expensify.com/create/submit/category/1/5400341052115475/?backTo=%2Fcreate%2Fsubmit%2Fconfirmation%2F1%2F5400341052115475

https://new.expensify.com/create/submit/description/1/5400341052115475?backTo=%2Fcreate%2Fsubmit%2Fconfirmation%2F1%2F5400341052115475

The URLs are different, which you didn't update - category includes a / before the ? which is not in the description URL. I don't think that in real life, anyone is going to update the URL to get to the location in the app they need - they will navigate there using the app.
