### ISSUE TITLE
[N6] AddressSearch component is not autofilling

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#5794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
There are two ways to test this

1) Sign into New Dot (new account is fine)
2) Create a new workspace
3) Connect a new bank account
4) Follow this SO for the routing number and account number https://stackoverflow.com/c/expensify/questions/342/525#525
5) Input valid information on all fields in the Company Information step (doesn't need to be real info)

### Variant 1
6) Refresh the page

### Variant 2
6) Hit Submit. When you're on Step 3 (Personal Information) click the back arrow to go back to Step 2 (Company Informaion)

### Either way
7) Notice that all the fields are auto-filled except for the Company Address. 

## Expected Result:
Describe what you think should've happened

The Company Address field should draw info from the reimbursementAccountDraft onyx key to autofill itself. 

<img width="534" alt="Screen Shot 2021-10-12 at 2 13 05 PM" src="https://user-images.githubusercontent.com/49007721/137051025-1a1c9b20-f539-4939-88a0-32b8b2c92498.png">

## Actual Result:

The Company Address field does not autofill

<img width="560" alt="Screen Shot 2021-10-12 at 6 27 10 PM" src="https://user-images.githubusercontent.com/49007721/137051054-cea2dbc2-2456-451d-aa34-112928615e64.png">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

The user can manually input their address again.

## Platform:

Where is this issue occurring?

- Web - definitely 
- iOS - haven't tested
- Android - haven't tested
- Desktop App - haven't tested
- Mobile Web - haven't tested

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Spent some time looking into this and alternatives with @Luke9389 [here](https://expensify.slack.com/archives/C03TQ48KC/p1634088400387400). I am pretty solidly on team `1` and if we know that will work let's just do it. Sometimes we have to apply things the way a 3rd party libs wants and in those cases I think it's fine to make exceptions. Feels like the [rule about hooks here](https://github.com/Expensify/App/blob/main/STYLE.md#are-we-allowed-to-use-insert-brand-new-react-feature-why-or-why-not) applies. Let's make just add a comment if we have to do `useEffect()` or something the developer recommends because we have no other option.

**Comment by Luke9389** [comment]
le whoops!
