### ISSUE TITLE
[HOLD for payment of bonus-only 2021-12-06] VBA- disabling future dates in the date picker 

### ISSUE THREAD

**Issue by SofiedeVreese** [Expensify/App#5922]
Coming from #5722 

----

Creating a new issue for disabling future dates in the date picker and assigning that to @Santhosh-Sellavel per CME @puneetlath 's comment [here](https://github.com/Expensify/App/issues/5722#issuecomment-944662051).

**Comment by developvsn** [comment]
Proposal

When the user chooses a date in the datepicker, the user won't be able to select the days after a maximumDate set up by you or the current day. The days will be inactive for clicking while other available dates will be active for the action to select. If necessary will be set a limit by minimumDate for users to be unable to select the dates that are too old. 

If for some reason user manages to select the incorrect date, an error message will be displayed below the datepicker field therefore it won't be possible for users to make changes / click on the "Save & Continue" button until users select the correct date.

**Comment by SofiedeVreese** [comment]
Hey @Santhosh-Sellavel are you still wanting to work on this one?

**Comment by puneetlath** [comment]
@SofiedeVreese @Luke9389 I'm back from vacation now. What @PrashantMangukiya said is correct. I recommended that we split the implementation of the validation and the date picker changes [here](https://github.com/Expensify/App/issues/5722#issuecomment-944662051) which is why there are separate issues and they are submitting separate PRs.

**Comment by Luke9389** [comment]
Ah OK so let me see if I have this straight. We are adding the following line in @PrashantMangukiya's PR because they don't have to use the date picker:
```js
return testDate.isValid() && testDate.isBetween(pastDate, currentDate);
``` 

In @Santhosh-Sellavel's PR we'll be making changes to the `DatePicker` component itself to make future dates unselectable.

Is that correct @puneetlath?

**Comment by puneetlath** [comment]
That's correct!

**Comment by Luke9389** [comment]
OK cool! 
Sorry to have thrown a wrench in the works here, heh. 
@Santhosh-Sellavel please feel free to resume your PR.

**Comment by SofiedeVreese** [comment]
No updates on this: open PR.

**Comment by SofiedeVreese** [comment]
Not overdue, PR is open.

**Comment by puneetlath** [comment]
@SofiedeVreese the PR has been merged. Let's make sure to add the company offsite bonus for @Santhosh-Sellavel when you pay this one out. Thanks!

**Comment by SofiedeVreese** [comment]
This job was already [paid out ](https://github.com/Expensify/App/issues/5922#issuecomment-954318857 )as we closed it due to a suspected double-up. But I'll pay out the bonus amount 7 days from successful deploy!

**Comment by SofiedeVreese** [comment]
Deployed to Prod- as the original amount was already paid out, only the Offsite hold bonus is remaining which I'll pay out 7 days from today.

**Comment by SofiedeVreese** [comment]
Hey @Santhosh-Sellavel I've just paid out the remaining bonus amount of $250 for the company offsite hold.

I've paid out the bonus via the original contract.

Closing GH.
