### ISSUE TITLE
Fix inconsistent translation key naming

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#6990]
# Problem

Translation key names are inconsistently applied. 

Sometimes we use an English phrase to repeat the exact text (which may change over time):

https://github.com/Expensify/App/blob/16942b556afe3250f06ac429b2ebebdbce2e0b8a/src/languages/en.js#L122

Other times we use a generic name or something misleading

https://github.com/Expensify/App/blob/16942b556afe3250f06ac429b2ebebdbce2e0b8a/src/languages/en.js#L139-L140

This can make it hard to provide guidance on _how_ to label a key and lead to disagreements.

# Solution

I am not too sure. But @chiragsalian had one idea about how translation keys should maybe reflect [how they are used](https://github.com/Expensify/App/pull/5150#discussion_r777658474) and not use short names that don't give any ideas.

**Comment by chiragsalian** [comment]
Yeah, I personally don't mind if the label repeats the copy because `iOUConfirmationList.whatsItFor` describes the copy imo. 
But `welcomeText.welcome` and `welcomeText.welcomeBack` does not describe the copy and is redundant. Its like the first words of the copy was used in the variable name rather than the parts that are relevant.

As i think about this a lot of copy is well plain text so "how they are used" might not help much (eg `whatsItFor`) and so instead i think we should just try to be as verbose to describe the copy as possible. Something which i think `whatsItFor` does fine but `welcomeText.welcome` or even `phrase2` does not.

**Comment by marcaaron** [comment]
If we apply that verbose thinking we would end up with something like this:

```js
welcomeText: {
  welcomeEnterPhoneOrEmailToContinue: 'Welcome to the New Expensify! Enter your phone number or email to continue.',
  moneyTalks: 'Money talks. And now that chat and payments are in one place, it\'s also easy.',
  yourPaymentsGetToYou: 'Your payments get to you as fast as you can get your point across.',
  welcomeBackEnterYourPassword: 'Welcome back to the New Expensify! Please enter your password.',
},
```

?

And maybe distilling that down we are saying something like... 

>A good translation key name should reference the copy itself. It does not need to include the entire phrase, but should capture the essence of the copy and should also be easy to differentiate from a key with similar copy.

**Comment by chiragsalian** [comment]
Yeah i honestly like those verbose key names a lot more. I don't mind its redundancy and would rather have it redundant and more verbose than just ambigious keys.

I like the way you phrase it in the distilling it down section.
