### ISSUE TITLE
Continue button is not accessible in samsung s20 default browser

### ISSUE THREAD

**Issue by vijeeshin** [Expensify/App#7667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. While connecting to bank account from mobile native app
2. Page opened in Samsung default browser
3. Continue button is not easily accessible

## Expected Result:
1. Page must be scrollable one

## Actual Result:
1. Page is not scrollable  

## Workaround:
yes 

## Area issue was found in:
On Samsung s20 default browser

## User impact:
It's very difficult to find the button 

## Suggested resolution:
.App__content {
    display: flex;
    flex-direction: column;
    height: 100%;
    z-index: 11111;
    overflow: scroll;
}
may help
## Platform:

Where is this issue occurring?

- Mobile Web

Version Number:8.5.33.1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/772974/153338890-10da27dc-9169-485d-b0e2-e057405f4d98.mp4

**Comment by mallenexpensify** [comment]
H @vijeeshin, we updated our process a couple months back and we're asking contributors to post all bugs to our shared Slack channel #expensify-open-source.  If you haven't been granted access yet, you can do so by emailing contributors@expensify.com, asking to join, and including a link to your upwork profile (it's necessary because all payments are managed via Upwork).  Below is the template to use for posting the bug.  Thanks

BUG:  
Action Performed: 
Expected Result:
Actual Result:
Platforms:
Version Number:
Screenshots or Videos:
