### ISSUE TITLE
Save button overlaps with text on paypal page in small screen - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app on the smaller screen device 
2. Navigate to Settings>Payments>Add a payment>Paypal.me 

## Expected Result:
Buttons should not overlap with content 

## Actual Result:
on a very small screen button overlaps with the content 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.34-0
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="563" alt="Screenshot 2022-02-02 at 12 37 15 AM" src="https://user-images.githubusercontent.com/43995119/153814205-dcbae7ae-0ae5-4ca0-92e5-0d01658e3be7.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1643745946971729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
It is reproducible on small screen device (mWeb)

### Proposal

For disabled success button we use 0.5 opacity and for disabled danger button we use different color. If we do the same for success button the issue will be solved. 
https://github.com/Expensify/App/blob/fd24e0d1b61b90058f2a1888fb1fb103e470f4cb/src/styles/styles.js#L394-L396
https://github.com/Expensify/App/blob/fd24e0d1b61b90058f2a1888fb1fb103e470f4cb/src/styles/styles.js#L408-L410
The reason this issue isn't on other page is that we use `ScrollView` on other pages so the second way of solving this would be using `ScrollView` instead of `View` on line 84 and 101
https://github.com/Expensify/App/blob/fd24e0d1b61b90058f2a1888fb1fb103e470f4cb/src/pages/settings/Payments/AddPayPalMePage.js#L84-L101


Before using ScrollView -

https://user-images.githubusercontent.com/83179295/153862697-ec36032a-c771-41b8-9ead-84ee0af9fbd1.mov

After using ScrollView-

https://user-images.githubusercontent.com/83179295/153862669-e36f492d-b6de-47c3-8551-093f108c6c44.mov

I think even if we decide using the ScrollView we should also add a background color for disabled success button because if we keep the opacity 0.5 we might again face this issue in future on some other component where we wouldn't be using ScrollView
If we decide to add a background color for disabled success button, we can use this `#a0eabf`
