### ISSUE TITLE
Cmd+k shortcut is not working on web/Chrome - reported by @ahmdshrif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app on Web / Chrome 
2. Cmd+K 

## Expected Result:
Search should open 

## Actual Result:
Search doesn't open 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.39-0
**Reproducible in staging?:**  need repro 
**Reproducible in production?:**  need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![IMG-20220204-WA0001](https://user-images.githubusercontent.com/43995119/155658902-76328aaf-b3fe-49c1-8ad0-564454104486.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:**    @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1643998148257529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmdshrif** [comment]
@mvtglobally 

I now get a clear understanding of why this happens with me only, 
it only happens when I enable this extension called Blackbox. when I disable it cmd +k is worked fine. by the way, cmd + k is not one of the Extention shortcuts. 
https://chrome.google.com/webstore/detail/blackbox-select-copy-past/mcgbeeipkmelnpldkobichboakdfaeon

I am not sure but it seems no issue with the app. as it will be from the extension.
