### ISSUE TITLE
Android / iOS - Attachment - User is not able to send video files when selecting gallery option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Go to any chat
3. Tap + and select add attachment option in the compose box
4. Select "Choose from Gallery"
5. Select a video file and send it

## Expected Result:
Video file is sent successfully. If file type is not supported user shouldn't be able to select mp4 files from the gallery or supported file types should be displayed when selecting the "Choose from Gallery" option

## Actual Result:
When the user attaches the video, the video is not attached and is constantly loaded in iOS and in Android filet type not supported error message after sending the file

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.44_2

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/159777459-686bad81-60ef-450e-8699-41ee7cd5cb5f.mp4
![Bug5492625_IMG_20220316_100905](https://user-images.githubusercontent.com/43996225/159777623-16979e0c-ebdd-4ef6-8700-6282cb61d8eb.jpg)

https://user-images.githubusercontent.com/43996225/159777539-3d2b6ec0-d1f4-4bf6-ae18-5a922e559f5b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@kavimuru I can only reproduce this on iOS. What is the email of the account used in the tests?

**Comment by kbecciv** [comment]
@luacmartins User credentials: hateemshafi00@gmail.com / Hateem123

**Comment by kavimuru** [comment]
@luacmartins You can check with kavi.utest+chatd@gmail.com / Test1234

https://user-images.githubusercontent.com/43996225/159927019-79774d90-fe0b-49c9-ae22-c9f9eaa57c33.mp4

**Comment by luacmartins** [comment]
@kavimuru Thanks! It seems that those files don't have an extension in their name and that's why they are failing.

Some thoughts:

1. I put up a PR to update the image picker library. That doesn't fix the issue completely, but should help with video files in iOS. Right now we don't get any extensions from those files, so upload will fail. Updating he library fixes that issue.
2. I couldn't find any way to disable certain file types with the library. I'll keep looking.
3. We could add a fallback method in our API to try to infer the file extension based on its MIME type. We would probably just cover the extensions [here](https://github.com/Expensify/Web-Expensify/blob/147b448b9e45411c7aa1998944ae6f653044f320/lib/ReportUtils.php#L69-L90) though, which might be enough.

**Comment by luacmartins** [comment]
Opened a discussion in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1648158172215349). I also think that this is working as intended if a file does not have an extension in the name, but I'll leave the discussion open to see what other people think.
