### ISSUE TITLE
[$500] Mixed messages of Spanish and English in the pronouns displayed 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set profile language to Spanish 
2. Set pronoun 
3. Navigate to chat with any other user with pronoun set 

## Expected Result:
Pronouns should display in Spanish 

## Actual Result:
Mixed messages of Spanish and English in the pronouns displayed 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.44-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Reproducible](https://user-images.githubusercontent.com/43995119/160849697-e7956e9a-bedf-448b-950f-943872eb59e3.jpg)

**Upwork job link:** https://www.upwork.com/jobs/~01c7cd706acf546ab1

**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647628630984219

![image - 2022-03-29T222312 507](https://user-images.githubusercontent.com/43995119/160738102-cd4ddbd4-4e64-4a1b-955a-6bba6f0ad23d.png)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Team was able to repro, so adding Engineering

**Comment by michaelhaxhiu** [comment]
This one reminds me of https://github.com/Expensify/App/issues/5113

**Comment by iwiznia** [comment]
I think it's a separate issue, given that was fixed and @mvtglobally just reproduced this again.

**Comment by michaelhaxhiu** [comment]
Upwork job link - https://www.upwork.com/jobs/~01c7cd706acf546ab1

**Comment by Julesssss** [comment]
Awaiting proposals

**Comment by rushatgabhane** [comment]
I can't repro this bug.

And we're translating the pronouns here.
 
https://github.com/Expensify/App/blob/43910fe5c20584b05fe56013005e8e59ba93e8a6/src/components/ReportWelcomeText.js#L67

**Comment by Julesssss** [comment]
I'm able to see the bug on staging:

![Screenshot 2022-04-11 at 09 52 56](https://user-images.githubusercontent.com/10736861/162701147-1f42429d-b20a-4e06-8796-55a9b9d0f717.png)

**Comment by rushatgabhane** [comment]
Oh I see, it's reproducible for accounts that have set their pronouns [before ~7 months](https://github.com/Expensify/App/commit/1d3155760a409422f9f5f899eb570071a79265f9). Eg: Rajat's account and Rory's account

<img width="390" alt="image" src="https://user-images.githubusercontent.com/29673073/162715903-af26009a-b4ef-4e19-9178-85c5ea2fb390.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/29673073/162715769-a5037e86-143c-4e3e-a576-19cb252115e0.png">

But this issue is **_NOT_** reproducible for accounts that have recently set their pronouns.
Eg: rushat222 [at] gmail.com

<img width="378" alt="image" src="https://user-images.githubusercontent.com/29673073/162716001-b811ac27-d081-4988-9046-5cf3e70b8f39.png">

<hr/>

#### Cause

We're failing this check because the pronouns for old users don't start with the prefix `__predefined_`.
This prefix was added 7 months ago in this commit https://github.com/Expensify/App/commit/1d3155760a409422f9f5f899eb570071a79265f9
https://github.com/Expensify/App/blob/43910fe5c20584b05fe56013005e8e59ba93e8a6/src/components/ReportWelcomeText.js#L65

#### Solution

@Julesssss my best bet would be to run a database query 😨 and replace `He/him/his` with `__predefined_heHimHis` etc.
An alternative solution would be to patch this in frontend and support deprecated pronoun prefixes.

Happy to be proven wrong :)

**Comment by Julesssss** [comment]
Hmm, good spot @rushatgabhane. 

If the fix is simply to change the setting, perhaps we just do nothing and let people fix it on their own?

**Comment by iwiznia** [comment]
Wait wait, if the bug is fixed and this is only happening to old accounts, then I agree we should do nothing and give people the workaround @Julesssss menitoned

**Comment by michaelhaxhiu** [comment]
wow I totally meant to double another GH and did this one - sorry! closing job
