### ISSUE TITLE
[$250] mWeb/Chrome - Text Insertion point goes out of the sight on typing in the middle of the paragraph - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go Chat
 2. Write 10-12 line text
 3. Type some words on the 4th-5th line.

## Expected Result:
Text insertion point should remain at a constant position.

## Actual Result:
It kept moving in and out of sight.

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Mobile Web (Chrome)

**Version Number:** 1.1.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/163698343-dcc08aef-380e-40a7-ab58-27bbd873cd6f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1646931771824919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Posted to Upwork! 
https://www.upwork.com/jobs/~01506330c899546260
https://www.upwork.com/ab/applicants/1517324288985792512/job-details

**Comment by b1tjoy** [comment]
### Proposal
### Reason
When the text changed in TextInput, the updateComment callback function is called, and in the last line of the function we always set scollTop to scrollHeight, which means always scoll to the last of TextInput, this is why the insertion point goes out of the sight.
https://github.com/Expensify/App/blob/0fb59f50af6c75cada48cae444d5eecb0299919a/src/pages/home/report/ReportActionCompose.js#L304-L327
And I checked the submit history of ReportActionCompose.js
Pull #7369 add the code
https://github.com/Expensify/App/blob/0fb59f50af6c75cada48cae444d5eecb0299919a/src/pages/home/report/ReportActionCompose.js#L326
 to solve issue #7351, but cause our current issue, the right way to fix issue #7351 is to call TextInput focus() at last of updateComment callback, not just set scroll to the last of TextInput.
### Solution
Modify this line
https://github.com/Expensify/App/blob/0fb59f50af6c75cada48cae444d5eecb0299919a/src/pages/home/report/ReportActionCompose.js#L326
to

`this.textInput.focus();`

will fix both issue #7351 and the current issue.

I will upload screenshot lately.

**Comment by parasharrajat** [comment]
@b1tjoy Thanks for the analysis. That PR indeed caused this issue. 

Your solution seems to work great. But did you test the same on native and mobile Web? What is the effect of this change.

**Comment by parasharrajat** [comment]
Bump @b1tjoy

**Comment by b1tjoy** [comment]
### Proposal
### Reason
The reason I posted 6 days ago was right, but the solution was wrong.

Remove this line will fix our current issue:
https://github.com/Expensify/App/blob/68f0bbf9c7fe8a95c7d65b0a9153229375863d1e/src/pages/home/report/ReportActionCompose.js#L323
But we still need to fix issue #7351, it took me a few days to figure out the root cause of this issue. The real problem of issue #7351 was when _we paste a large paragraph **copy from HTML page**, the input field does not scroll down to the right position_, but if we paste a large paragraph of plain text copy from notepad, the input field scroll down to the right position as we expected.
When we paste something, this hanlder is called:
https://github.com/Expensify/App/blob/68f0bbf9c7fe8a95c7d65b0a9153229375863d1e/src/components/Composer/index.js#L257-L259
If paste type contains HTML, we prevent the default browser action by line 273:
https://github.com/Expensify/App/blob/68f0bbf9c7fe8a95c7d65b0a9153229375863d1e/src/components/Composer/index.js#L270-L275
So the input field does not scroll to the right position. And if we paste plain text, we haven't prevented the default browser action, everything goes fine.
### Solution
Remove this line will fix issue #8663
https://github.com/Expensify/App/blob/68f0bbf9c7fe8a95c7d65b0a9153229375863d1e/src/pages/home/report/ReportActionCompose.js#L323
Remove this line will fix issue #7351
https://github.com/Expensify/App/blob/68f0bbf9c7fe8a95c7d65b0a9153229375863d1e/src/components/Composer/index.js#L273

**Comment by parasharrajat** [comment]
Won't this new solution break pasting HTML?

**Comment by b1tjoy** [comment]
Sorry, I forget the basic knowledge, if we want to override the paste event handler, we must cancel the default action. The new 'solution' break pasting HTML indeed. Still need to find a solution for #7351.

**Comment by parasharrajat** [comment]
Looking forward to it.

**Comment by b1tjoy** [comment]
### Proposal
### Problem
Reasons for our current issue and issue #7351 are in my previous posts.
### Solution
Solution for our current issue is to remove this line:
https://github.com/Expensify/App/blob/bd548576e288229e516223d2ac40929a7825b6a0/src/pages/home/report/ReportActionCompose.js#L323
Solution for #7351:

Since pasting HTML breaks the default behavior of scrolling to the right position of TextInput, we can remember the scroll position by the height to the bottom before we insert the HTML data, and recalculate the scroll position by new scrollHeight and previous scroll position after we insert the HTML data.

`+ const computedStyle = window.getComputedStyle(this.textInput);`
`+ const paddingTopAndBottom = parseInt(computedStyle.paddingBottom, 10)`
`+ + parseInt(computedStyle.paddingTop, 10);`
`+ const heightToBottom = this.textInput.scrollHeight - paddingTopAndBottom - this.textInput.scrollTop;`
https://github.com/Expensify/App/blob/bd548576e288229e516223d2ac40929a7825b6a0/src/components/Composer/index.js#L245-L246
`+ this.textInput.scrollTop = this.textInput.scrollHeight - paddingTopAndBottom - heightToBottom;`

I have tested the fix in different scenarios, and will take screenshots and upload them lately.

**Comment by parasharrajat** [comment]
Ok. But let's discuss your first proposal [here](https://github.com/Expensify/App/issues/8663#issuecomment-1110040130). It was working for me. Why did you think that is not a correct solution?

**Comment by b1tjoy** [comment]
@parasharrajat 

I find out my first proposal works not fine in some situation, after apply my first proposal:

a) write 10 line text, and type some words in 4th-5th line, text insertion point remains at it's position, as we expected:

https://user-images.githubusercontent.com/103875612/166475090-06d1de5a-06f7-480c-87ae-f863d8bd4361.mov

b) paste a large paragraph from HTML page, **text insertion point move out of sight, and TextInput does not scroll to the right position**:

https://user-images.githubusercontent.com/103875612/166475772-ba6443a6-9b37-4991-a5a7-5ff53030421c.mov

c) paste a large paragraph of plain text, TextInput scroll to the right position as we expected:

https://user-images.githubusercontent.com/103875612/166478802-3ce3944a-8220-47c0-9b5f-da041e554422.mov

**Comment by kadiealexander** [comment]
@parasharrajat any thoughts on the above?

**Comment by parasharrajat** [comment]
Sorry for the delay. I tested your first proposal @b1tjoy It is working fine for me after removing https://github.com/Expensify/App/blob/f390e2767f28dbb832696f39aac8a4e23460786c/src/pages/home/report/ReportActionCompose.js#L371 on firefox Linux web. But it does not work on chrome Linux web. 

ok. Your [last](https://github.com/Expensify/App/issues/8663#issuecomment-1116002461) proposal is doable but will it work when 
- we replace the selection with pasted content.
- Let's say the content in textinput is scrollable and you scroll close to the bottom. Now you select the text from bottom to top in a way that the remaining text does not make the input scrollable. Now paste the content. 

etc..

**Comment by b1tjoy** [comment]
> * Let's say the content in textinput is scrollable and you scroll close to the bottom. Now you select the text from bottom to top in a way that the remaining text does not make the input scrollable. Now paste the content.

@parasharrajat Thanks for your review. When we select the text from bottom to top, make sure the selection makes the scroll bar goes up, then paste the content copy from HTML page, it will not scroll to the right position.

We still need to find a solution for #7351.

**Comment by b1tjoy** [comment]
@parasharrajat Simply replace this line
https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/pages/home/report/ReportActionCompose.js#L371
with
```JavaScript
this.textInput.blur();
this.focus();
```
will solve both current issue and issue #7351.

Works fine on both firefox mac web and chrome mac web.

**Comment by parasharrajat** [comment]
Ok, I see. There is a small difference between chrome and firefox but that could be due to browser differences. On Chrome, the End of the pasted text is at the middle row on the Composer when content is bigger than the composer viewport. But that is fine IMO. 

One change I would request is _Instead of using `this.focus`, we can use `this.textinput.focus`_.

so I like @b1tjoy's [fourth](https://github.com/Expensify/App/issues/8663#issuecomment-1126691427) proposal. 

cc: @pecanoro 
:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by pecanoro** [comment]
Sounds good! Assigning @b1tjoy to the issue! Don't forget to apply in Upwork

**Comment by kadiealexander** [comment]
@b1tjoy please let me know your upwork username so I can hire you for the job. :)

Offers sent to @parasharrajat for C+ and @Tushu17 for reporting.

**Comment by Tushu17** [comment]
Offer accepted👍

**Comment by b1tjoy** [comment]
> @b1tjoy please let me know your upwork username so I can hire you for the job. :)

Took me some time to figure what my upwork username is, but i still don't know, can I submit a proposal on upwork?

I have issue with screenshot on Android simulator, I will take screenshot on real device and make pull request less than 24 hours.

**Comment by kadiealexander** [comment]
Discussions happening in the PR, not overdue.

**Comment by kadiealexander** [comment]
@parasharrajat and @b1tjoy could you please share an update here?

**Comment by parasharrajat** [comment]
I have to do some research for moving ahead with the PR.

**Comment by kadiealexander** [comment]
@parasharrajat how's your research going?

**Comment by parasharrajat** [comment]
Updates on the PR. We are moving ahead.

**Comment by parasharrajat** [comment]
Shared an update on PR.

**Comment by kadiealexander** [comment]
Not overdue, updates in PR.

**Comment by Tushu17** [comment]
The payment is pending here.
cc: @kadiealexander

**Comment by kadiealexander** [comment]
Sorry for the confusion there! Have opened and will pay after the regression period.

@pecanoro please don't close these issues until the payment is issued.

**Comment by kadiealexander** [comment]
Everyone is paid! Thanks team :)
