### ISSUE TITLE
Feature Request: User is not able to start over after filling some info in VBA flow - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8718]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Add bank account manually
 2. Fill some fields in company information page and press the cross icon at the top right to go to homepage
 3. Now go back to the connect bank account page
 4. Check if you see any option to start over or continue with the setup
 5. Press connect manually and you will see your account details.
 6. Press save you will see more info that you had filled in company information page

## Expected Result:
You should see the option to start over and continue with the setup

## Actual Result:
There is no option to start over or continue with the setup 
When you leave company information page after filling some info, then on going back to the connect bank account page you won't see any option to continue with the setup or start over. However if you select the connect manually option you will see the info you had filled.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/164371413-6c5e4ccc-8c11-4c66-8199-e4c910e38d84.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648738198536209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
I've wanted to fix this for a while! Sending to engineering.

**Comment by roryabraham** [comment]
Sorry, I'm having difficulty following this issue, and I think that some screenshots would be really helpful to clarify it. @Puneet-here since you reported the issue, do you mind collecting some screenshots to go along with the issue description?

**Comment by roryabraham** [comment]
Going to pass this back to @kadiealexander in the meantime.

**Comment by roryabraham** [comment]
Sorry, I guess there already _is_ a video. Maybe I can just clarify this:

### Action Performed
1. Create a workspace if needed.
1. Go to `Settings` -> `Your workspace` -> `Connect Bank Account`.
1. Press `Connect Manually`
1. Enter a routing and account number, then press `Save and Continue`.
1. Start filling out the company information.
1. Press the `x` to close the bank account setup modal and return to the homepage.
1. Go to `Settings` -> `Your workspace` -> `Connect Bank Account`.
1. Press `Connect Manually`

### Expected Result
You are shown a screen that gives you a choice:

- Continue with your previous bank account details, _OR_
- Start fresh with different bank account details

If you choose to continue with your previous bank account details, then you are taken to the step you left off in, and all the information you entered in the previous steps (routing number, account number, company details) is restored when you see the relevant forms again.

If you choose to start fresh, you restart the VBA flow with none of the form fields filled out.

### Actual Result
You are taken to the routing/account number page, and it's pre-populated with the information you entered before. If you continue to the company step, the information you entered previously is still there.

---

Is all that correct? If so, I would like to get broader consensus from more Expensify employees in slack before continuing with this feature request. Thanks for your patience – it's better to be extra-thorough up front and get broad consensus on the expected behavior before we dive into this feature request.

Also, I'm going to make this a weekly instead of a daily, because as a company I believe we have more urgent priorities at the moment.

**Comment by Puneet-here** [comment]
Yes, that's correct, right now we only see the start over option when we exit after adding and saving the personal details
<img width="374" alt="Screenshot 2022-04-22 at 12 34 18 AM" src="https://user-images.githubusercontent.com/101883770/164535408-8d98168c-9855-4a70-8875-4b45819f07d0.png">

**Comment by kadiealexander** [comment]
@Puneet-here could you please clarify what you mean by "right now we only see the start over option"? In your screenshot there is an option for "continue with setup", is this option not working?

**Comment by Puneet-here** [comment]
Sorry for the confusion QA team logged it as a feature request but this is a bug.

@kadiealexander, we show two options one to start over and one two continue with the setup. The bug here is that this page only shows up when you exit after saving personal details. If you exit before that your data will be saved but you won't see this page.

**Comment by kadiealexander** [comment]
Right, thanks for explaining @Puneet-here! I get what you mean now. @Expensify/design could you please weigh in here and let us know if this is intentional?

**Comment by shawnborton** [comment]
cc @joekaufmanexpensify @kevinksullivan as our VBA form gurus. I'm not sure what the intended behavior should be here.

**Comment by kevinksullivan** [comment]
Yeah I agree with the overall proposal, that once a user has completed the plaid or routing/account number step, they have technically started the process of adding a VBA and it would be logical to show the `Continue with setup` or  `Start over` option if they exit and return at that point. 

@marcaaron I'd be curious for your thoughts on this though, because I vaguely remember we waited till after the `Company info`  step because the bank account is technically not created until a user has passed that step. Was it a decent lift to change this, and that's why it's currently designed as is?

**Comment by marcaaron** [comment]
Yes, that is exactly why we ask the user again for this information. I'm not sure how much of a lift this will be, but it will require API changes.

I agree with @roryabraham on this. Overall seems like this is not a priority or maybe can be part of a design doc as some larger reworking of the VBA flow.

----

Separately, when did we start moving contributor Feature Requests straight to issues again? I thought we stopped that... 

The "New Feature" label is for things that we have actually agreed are worth doing and related to design docs?

**Comment by kadiealexander** [comment]
Good question! @mallenexpensify do you have any insight on why feature requests are moving forward without weigh-in? Did the process change and we missed it?

**Comment by mallenexpensify** [comment]
It's likely cuz it was reported as a bug, which it _seems_ like it is, right?  
Maybe @mvtglobally accidentally titled with `Feature Request` or thought that is should be a FR vs bug? 
¯\_(ツ)_/¯

**Comment by mvtglobally** [comment]
@mallenexpensify 
There was another tread where discussion was that similar issues should be treated as Feature requests. I'll try to find and will update in a bit

**Comment by mvtglobally** [comment]
@kadiealexander, @mallenexpensify, @marcaaron Since "start over" button is not exiting in the flow and we had similar issues in the past where it wasn't a bug, but rather a feature, I logged this as feature request. If everyone is aligned it is a bug, I will just modify the title and change labels to Engineering now?

**Comment by kadiealexander** [comment]
I think we all agree that this is a good move, but we can leave it as a feature request for now since the product is currently working as we intended it to, this is just an improvement. Passing back to engineering triage now that we're all aligned. Thanks everybody!

**Comment by kevinksullivan** [comment]
Hm my understanding form this conversation is that this is a nice to have but also not a priority right now.

**Comment by stitesExpensify** [comment]
I agree. I think that this is a nice to have, but is not worth pursuing at the moment since this will have to be an internal issue.
