### ISSUE TITLE
 LHN - the workspace chat in the left hand navigation isn't appeared for public account (gmail)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8476

## Action Performed:
Precondition: Create new public account (Gmail)
1. Launch App and login
2. Create a new workspace.

## Expected Result:
Verify that you immediately see the workspace chat in the left hand navigation

## Actual Result:
The workspace chat in the left hand navigation isn't appeared.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.56.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** rybkina+4202022@gmail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/164479750-838d2022-76a5-4939-aef5-5864b1e211c3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
I haven't been able to reproduce this issue. I am on the [1.1.56-0 branch](https://github.com/Expensify/App/tree/1.1.56-0) and I also tested on `main`.

Video:

https://user-images.githubusercontent.com/7277067/164788054-faf2e540-3743-4524-af43-7038eba97ed4.mov


@kbecciv do you think perhaps it's just that you were in Focus mode instead of Most Recent? The new workspace doesn't have any unread messages, nor is it pinned, so in Focus mode I think it's expected that the workspace wouldn't show in the LHN. Let me know if I'm misunderstanding though!

**Comment by mvtglobally** [comment]
@amyevans, We are not able to repro this issue with the expensifail accounts. It is only repro with Gmail(public domain). It is not related to focus mode.

**Comment by francoisl** [comment]
cc'ing @TomatoToaster as per the QA steps in the PR:

> No failure case needed since this is in beta, if this is not working let @TomatoToaster know so it can be fixed in a followup PR

**Comment by amyevans** [comment]
Good eye @francoisl, thanks for catching that!
