### ISSUE TITLE
Web - "Expense Violations" tab enabled is not showing any confirmation and after refresh, disable

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8744]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Access staging.expensify.com
Sign into a verified account
Go to the Policy and to the "Expenses" tab
Click on the "Enable" button next to "Expense Violations"
Refresh the page

## Expected Result:
The user expects to see a confirmation message that the Violations have actually been enabled or a message to refresh the page to renew the policy

## Actual Result:
The user does not receive any message confirmation and after refreshing the page, the "Expense Violations" tab is disabled again

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** n/a

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** n/a

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/164571550-098a793b-a4b5-4b94-9dd4-8ad673db8857.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
Andrew already triaged in https://github.com/Expensify/Expensify/issues/207142

**Comment by laurenreidexpensify** [comment]
@joelbettner's comment from there - 
Oh...actually, I just tested this myself. The reason enabling expense violations on a policy isn't "sticking" is because there were no parameters added for what constitutes a violation. Thus, since there was nothing to enforce, we show the violations as turned off after the refresh. As soon as I put something in to enforce for expense violations, the violations stayed on.
![image](https://user-images.githubusercontent.com/13264774/164267788-a9f16ddc-8fc0-49b6-a79b-72e86e2fe2a9.png)

So...now I'm not so sure if this is a bug, or a feature.  @laurenreidexpensify your thoughts here on whether or not this needs to be fixed? It certainly isn't a rush and could be worked on externally. (un-assigning myself)

**Comment by laurenreidexpensify** [comment]
@AndrewGable second pair of eyes pls - given Joel's comments above? Thanks!

**Comment by AndrewGable** [comment]
1. This looks like it will be an internal issue as it's OldDot
2. Yes, I do think that there needs to be a value inputted for it to "stick"

**Comment by laurenreidexpensify** [comment]
oh my god yesterday was not my day 🤦🏽‍♀️ 🤦🏽‍♀️ it threw me that someone from Applause had created this E/E ! Will re-open the original issue
