### ISSUE TITLE
IOS - User isn't logged out after destroyed the device credentials

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8713

## Action Performed:
1. Launch the app
2. Navigate to Preferences and verify there are new testing preferences available
3. Toggle on "Simulate failing network requests"
4. Send message or do something in app
5. Go back to preferences and untoggle this option
6. Invalidate the authToken via the button that says "Invalidate"
7. Do something in app
8. Back on Preferences  and tap on destroy button
9. Do something in app
10. Verify that log out

## Expected Result:
User is logged out after destroyed the device credentials

## Actual Result:
User isn't logged out after destroyed the device credentials

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/165829093-0ce0db53-382b-44ef-9a06-53c1c1cf8081.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@marcaaron @marcochavezf, just to confirm, do we want this one to go external or will it be taken care of internally as polish with the Offline first project?

**Comment by marcaaron** [comment]
Hmm I am actually not sure why Applause is creating these issues or who asked them to do. We haven't given any instructions on how they should work or how they should be used. In this case, it makes sense you are not logged out because the toggle to fail the network requests is preventing it from happening.

**Comment by marcaaron** [comment]
Let's please wait until we give specific instructions for how to use these features before creating any issues.

**Comment by isagoico** [comment]
@marcaaron We created this issue because this [PR](https://github.com/Expensify/App/pull/8713) was included in our [PR checklist](https://github.com/Expensify/App/issues/8777) and we were following the QA steps mentioned there. 2 testers were able to reproduce the same behavior in iOS and this ticket was opened. 
Our current process for issues that fail QA steps in PRs is to create a new ticket. This is basically what we do in numbered steps:  

1. Verify the QA steps in the deploy checklists in the required environments (Web/mWeb, Desktop, iOS, Android) 
2. If the PR fails we create a ticket and link it to the PR
3. We leave the PR unchecked in the checklist until the issue is reviewed by the PR creator/reviewer. 

Hopefully this clears why we opened the ticket. Happy to give more details of our current processes for opening bugs if needed. Also please let me know if we misunderstood the PR instructions

**Comment by marcaaron** [comment]
@isagoico, thanks for confirmation! Glad that we are not making random issues 😄  

Though, in this case, the test steps were not followed correctly. Step 8 here is wrong and can be compared with step 9 in the linked QA where it says to invalidate the authToken twice. Thanks!
