### ISSUE TITLE
mWeb - Long press on hyperlink not always displayed Copy URL to clipboard title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/8815

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with any account
2. Navigate to chat conversation 
3. Send any hyperlinked text
4. Long press in hyperlinked text

## Expected Result:
Long press on hyperlink displayed `Copy URL to clipboard` title

## Actual Result:
Long press on hyperlink not always displayed `Copy URL to clipboard` title

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 9new feature)

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167973090-303fb1cd-a47c-464c-a95f-6bf1c596eb85.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
It can be External.

**Comment by eVoloshchak** [comment]
> CC: @eVoloshchak as it seems like [this PR](https://github.com/Expensify/App/pull/8815) didn't quite work.

This issue isn't connected to my PR, it was present before
It's still open https://github.com/Expensify/App/issues/8311
Before submitting my PR i raised a concern [here](https://github.com/Expensify/App/issues/7844#issuecomment-1112084534), but was [told ](https://github.com/Expensify/App/issues/7844#issuecomment-1112092498)i could submit a PR since that's a separate issue
>Thanks for looking into it. It is a different issue than the one we are trying to solve here. So you don't have to fix that in this PR.

I also stated that in the PR description, in the Screenshots/mWeb section

I also researched https://github.com/Expensify/App/pull/8815, it is present on mWeb and Native platforms, but it's somewhat different on these platforms: on mWeb it shows wrong context menu for all links, on native it shows wrong menu only if message contains text and a link

**Comment by trjExpensify** [comment]
Okay got it, thanks for that added context. If we've got #8311, do we need this issue open as well?

**Comment by eVoloshchak** [comment]
> Okay got it, thanks for that added context. If we've got #8311, do we need this issue open as well?

Not sure if you you were asking me, but imo this one is a duplicate

**Comment by trjExpensify** [comment]
Cool, cool. I'm going to close this out. Thanks! @danieldoglas, let me know if you disagree.
