### ISSUE TITLE
Send Money - In the preview for sent money using I'll settle up elsewhere is not meaningful text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Set your payment with PayPal
1. Go to https://staging.new.expensify.com/
2. Log in with account
3. Select user and tap send Money
4. Select amount and click next
5. Select -I'll set elsewhere and click Send

## Expected Result:
After send money preview should be more descriptive

## Actual Result:
I'll set elsewhere is missing some part of the text "using" for Send money

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.63.2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/169626294-89aa775f-c7ac-4e0a-8f2c-cdc1f155f8d2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause exploratory
![Bug5577850_Elsewhere](https://user-images.githubusercontent.com/43996225/169626300-c2d0f7a5-87e5-45ac-8b15-9d0aedd48ca2.png)

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@kavimuru Thanks for this report. 

What is the expected behaviour based on though? Although I agree it is not that explanatory right now, it is not a regression and it is expected behaviour as of now. We could change it later on but that would be more of a product decision I would say. I think we should close to prioritize broken features or new features.

Feel free to comment if I have missed anything and this should definitely get more attention, we can reopen then.
