### ISSUE TITLE
Chat - Endless loading spinner appears when sending a .ps/mp3/.rar formats file and no error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App as login user
2. Select any chat
3. Sent attachment file with .ps

## Expected Result:
File should be sent or if the file type is not supported proper error message should appear.

## Actual Result:
Endless loading spinner appears and after a while attachment disappeared.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**  rybkina@gmail.com / Qwerty123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5584550_Screen_Shot_2022-05-24_at_6 12 51_PM](https://user-images.githubusercontent.com/43996225/170150405-dc47dd33-fe5c-4cbb-8a87-c812fbb6d0c6.png)

https://user-images.githubusercontent.com/43996225/170150411-6881cf61-065e-486d-bb98-646d3883a539.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
I think this can be external!

**Comment by parasharrajat** [comment]
This will be internal as the backend needs to add the file upload support. That's all.

**Comment by Christinadobrzyn** [comment]
Testing `mp4` on desktop - uploads successfully into chat
Testing `m4a` on desktop - throws same error as `mp3` on desktop

Testing `mp3` on desktop app - I'm getting an error
![2022-05-27_12-31-29 (1)](https://user-images.githubusercontent.com/51066321/170629323-5d2347d0-c608-4579-af9d-1697f299ff30.gif)


testing `mp3` on mobile - I'm able to reproduce @kbecciv video - loading spinners - no fail message

**Comment by Christinadobrzyn** [comment]
> This will be internal as the backend needs to add the file upload support. That's all.

So should we keep this internal for part of the fix or for the entire fix? I can create an Expensify/Expensify GH if we're keeping this internal.

**Comment by Christinadobrzyn** [comment]
@Gonals and @parasharrajat Created an Internal GH here - https://github.com/Expensify/Expensify/issues/212254

Going to make this weekly - while we wait for the internal update

**Comment by Christinadobrzyn** [comment]
Deployed internal update to staging - https://github.com/Expensify/Expensify/issues/212254

**Comment by Christinadobrzyn** [comment]
Looks like the Internal update is complete - https://github.com/Expensify/Expensify/issues/212254#event-6773641340

What do you think @parasharrajat and @Gonals - should we make this an Upwork job?

**Comment by parasharrajat** [comment]
Then we are good. We should able to upload the file now.

**Comment by Christinadobrzyn** [comment]
Posted in Upwork 

Internal Job  - https://www.upwork.com/ab/applicants/1535157989620789248/job-details
External Job - https://www.upwork.com/jobs/~0152c8b41284651e68

**Comment by parasharrajat** [comment]
I meant to say we don't need the Upwork job. It should be fixed already. Next step should be QA testing it. @Christinadobrzyn

**Comment by mananjadhav** [comment]
@Christinadobrzyn, What @parasharrajat said is right. This isn't reported by an external contributor and is fixed internally.  Hence we don't need any Upwork jobs here.

**Comment by kbecciv** [comment]
@mananjadhav @Gonals @Christinadobrzyn @parasharrajat   Here is the list of formats files where endless loading spinner appears: .rar, .webp, .epub, mp3 and .ps.

**Comment by parasharrajat** [comment]
>  .rar, .webp, .epub, mp3 and .ps.

I guess we can request more files to be added from backend cc: @aldo-expensify

**Comment by aldo-expensify** [comment]
Sorry, just catching up here. I'm understanding that we just have to fix this on the API, right?

If any of you have been playing with files with these formats, can you upload them to the GH issue? (only if GH allows it, I don't know if it allows it :P)

**Comment by aldo-expensify** [comment]
> @mananjadhav @Gonals @Christinadobrzyn @parasharrajat Here is the list of formats files where endless loading spinner appears: .rar, .webp, .epub, mp3 and .ps.

is it enough to just change the extension of the file? like.. if you have .txt, change it to .rar and then you get an infinite spinner?

**Comment by parasharrajat** [comment]
> I'm understanding that we just have to fix this on the API, right?

Yes, we only need to allow these files from backed and they will start working. Previously we had an issue for svg and Marc suggested to enable the support for files that we encounter issue. 

But my suggestion was to add error handling from frontend when a file is not supported, fronted should error out. 
1. First, add proper file extensions that are allowed to be uploaded to the file upload config. 
2. Second, Add another check is file is not supported throw error. I guess backend already throws error. 
3. If possible, allow the file to be uploaded. In many cases, we won't want to allow the file to be uploaded. Such as rar file could be a virus. So unless we scan the file or add a clause somewhere that we are not responsible for content shared. It is a security hole and we should not allow the file to be shared.

**Comment by aldo-expensify** [comment]
There are a huge number of extensions out there and the approach of allowing them one by one doesn't seem to scale well. It doesn't make sense for me to block files just because we don't have the extension in our list. If we care about blocking some extensions, I would do a list of blocked extension and allow the rest.

The approach of allowing the through a list made more sense to me in the context of the Old Expensify app, because it was just used to share receipts (afaik). I'll ask for other opinions in slack.

Regarding 2), I think it makes some sense to duplicate the check in the front end and block the user before sending the request with the file... this is similar to form validations done in the front and back, but I see it as low priority.

Regarding 3), my guess is that we will never be able to prevent 100% someone sending a "virus", so it should be always good to have some "clause somewhere that we are not responsible for content shared" (no matter if we try to scan for virus or not). Scanning for virus is nice to have I would say, but I'm don't know if we already have some of that implemented or if it is difficult to implement.

**Comment by Christinadobrzyn** [comment]
> What @parasharrajat said is right. This isn't reported by an external contributor and is fixed internally. Hence we don't need any Upwork jobs here.

Ah, thank you for confirming! Sorry for the confusion. I removed the job in Upwork.

**Comment by aldo-expensify** [comment]
I asked for opinions in slack [here](https://expensify.slack.com/archives/C03TQ48KC/p1654886092308369). I'll try to put some work on this later this week

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week) for original file formats

**Comment by aldo-expensify** [comment]
Haven't got time to work on this again yet

**Comment by aldo-expensify** [comment]
I'm going to close this issue because the original upload problems related to the specific file types .mp3/.ps was solved in the backend.

Improving the front end feedback on failure will be done with the refactoring that is happening here: https://github.com/Expensify/Expensify/issues/211241 / https://github.com/Expensify/App/pull/9556
I don't think it is worth doing it now because it will probably have to be undone.

I created a [new GH issue](https://github.com/Expensify/Expensify/issues/216891) for updating how we handle file types in the back.
