### ISSUE TITLE
[$250] Unread message count is doubled on unread message pill - Reported by @aswin-s

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a report 
2. Mark few messages unread
3. Change Chat in LHN
4. Go back to the chat with unread messages
5. Scroll up

## Expected Result:
Pill should show the actual count of unread messages

## Actual Result:
Pill shows double the count of unread messages

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171088867-de678f76-7904-4ad3-b154-35496737b62b.mp4

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650866298168889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aswin-s** [comment]
**Reason** 

Unread message count (`messageCounterCount`) is updated every time user the counter is made visible on this line

https://github.com/Expensify/App/blob/29f07d2d60f0786e698adfa19f495399ad1377f4/src/pages/home/report/ReportActionsView.js#L315-L320

And it gets reset to `0` when the counter is hidden

https://github.com/Expensify/App/blob/29f07d2d60f0786e698adfa19f495399ad1377f4/src/pages/home/report/ReportActionsView.js#L363-L367

But the variable value is already set to the current unread count in the constructor. line 101
https://github.com/Expensify/App/blob/29f07d2d60f0786e698adfa19f495399ad1377f4/src/pages/home/report/ReportActionsView.js#L92-L102

And we are adding previous value in state with unread count in `updateMessageCounterCount ` (line 335), **which doubles the unread count.** 
`prevState.messageCounterCount + this.props.report.unreadActionCount;` 

https://github.com/Expensify/App/blob/29f07d2d60f0786e698adfa19f495399ad1377f4/src/pages/home/report/ReportActionsView.js#L331-L339


**Proposal**

The proposal to fix this issue is to initialise the message counter variable with 0. Since the unread count gets recomputed anyway right before the counter gets shown, this will prevent the previous value being unread count itself. 

```jsx
    constructor(props) {
        super(props);
        ...
        this.state = {
            isFloatingMessageCounterVisible: false,
            // Initialise messageCounter with 0
            messageCounterCount: 0,
        };
```

Before the fix:

https://user-images.githubusercontent.com/6880914/171343497-838a6d7f-a88e-478c-ac39-7245b1b05a9e.mp4

After the fix:

https://user-images.githubusercontent.com/6880914/171343530-ed4ce024-4523-43f5-8b4f-76dc23e6b55e.mp4

**Comment by jboniface** [comment]
https://www.upwork.com/jobs/~01079a845d0958e78c

**Comment by Santhosh-Sellavel** [comment]
@jboniface 

As I'm going OOO, I am unassing this new one. Can you re-apply Exported Label, thanks!
