### ISSUE TITLE
[$250] IOS -  On selecting edit or delete comment from the context menu an other context menu shows up for a brief moment  @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat
2. Open the context menu by long press on any message
3. Tap on edit comment or delete comment
4. Check another context menu will show up for a brief moment

## Expected Result:
Another context menu shouldn't show up.

## Actual Result:
Another context menu shows up

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.78.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/174803832-50bbc1e8-9c28-4e3f-abb0-3eb74ea8bd92.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @thesahindia

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1648072346149029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Oh wow odd, yeah, looks like a bug to me!

**Comment by NicMendonca** [comment]
job post: https://www.upwork.com/jobs/~01dff267d3f1a00bf9

**Comment by JosueEchandiaAsto** [comment]
### Proposal

### Issue

Another context menu shows up, when is hiding.

### Fix


You need to set true in `useNativeDriver` and `hideModalContentWhileAnimating` in the Modal component, if you don't want to change it for all modals you can just add it in PopoverWithMeasuredContent

https://github.com/Expensify/App/blob/3282de35957e68ba8712e0f0e4e7e92b5e665a14/src/components/Modal/index.ios.js#L6-L15

It already exists in Modal for Android, if we remove it this bug is replicated in android.
Modal android without `useNativeDriver`:

https://user-images.githubusercontent.com/16966456/175192363-cf114b52-6792-46d7-8ba2-7c90c2d5c805.mov

It is true that using this element had a problem specified in this link. This Issue is Closed.
https://github.com/react-native-modal/react-native-modal/issues/92

And per recommendation we include `hideModalContentWhileAnimating` to prevent the modal emits a "flash" in iOS.

Commit: https://github.com/Expensify/App/commit/3282de35957e68ba8712e0f0e4e7e92b5e665a14

### Result

https://user-images.githubusercontent.com/16966456/175193084-b8ca8066-b003-4cc1-9b0c-c5b64ac5eb77.mp4

**Comment by NicMendonca** [comment]
@Santhosh-Sellavel bump on the review ☝️

**Comment by Santhosh-Sellavel** [comment]
Sorry missed this one, will get to  this by today.

**Comment by Santhosh-Sellavel** [comment]
@flodnv @iwiznia 
 I am unable to reproduce this on my personal device. Seem this occurs only on simulators. Were you able to reproduce on device?

**Comment by Santhosh-Sellavel** [comment]
Have you checked out?  @kbecciv @flodnv

**Comment by kbecciv** [comment]
@iwiznia Unable to reproduce with latest version 1.1.79.13

https://user-images.githubusercontent.com/93399543/177224852-0c4ed6d1-76a9-4eba-81a4-be3085363c24.MP4

**Comment by thesahindia** [comment]
This is an ios (app) only issue It's also reproducible on real device (just tried on iPad)

**Comment by thesahindia** [comment]
@flodnv, can we reopen this?

**Comment by flodnv** [comment]
@kbecciv are you able to confirm?

**Comment by kbecciv** [comment]
@flodnv Checking with team, will update you shortly.

**Comment by kbecciv** [comment]
@flodnv Sorry, QA team is unable to reproduce it.
