### ISSUE TITLE
Web - Editing the last sent message does not update summary in LHN @parasharrajat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Send some message to any user on web.
3. Go offline (disconnect the wifi) etc.
4. Edit the message.

## Expected Result:
The message text is updated optimistically in LHN.

## Actual Result:
Message is not updated until API request is made to the server.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.78.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/174875825-782571d2-0de4-43bd-b4bf-bf491fff086a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @parasharrajat

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654709689929729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Going to add Eng to check this.

**Comment by chiragsalian** [comment]
Hmm Its a valid bug but nothing needs to be done here because for any issue offline we captured in our offline UX patterns doc and  internal API Refactor doc. These are currently being worked on and hence this issue should be tackled [here](https://github.com/Expensify/Expensify/issues/211601). Closing this issue. We can reopen once again if the internal API refactors are done and this is not handled.
