### ISSUE TITLE
[HOLD for payment 2022-08-11] [$250] Web - Moving to and  from search bar to bottom emoji is inconsistent @daraksha-dk

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Go to any chat > click on emoji picker > press down arrow key
3. Nothing is selected
4. Same thing with up arrow, if you're under "Frequently Used", it will not go to Search on first click

## Expected Result:
 It should move to the correct location in one click

## Actual Result:
 Need to click up or down two times instead of one

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79.17

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177441971-37e7cb8c-f98e-4db9-a2d0-8963c5eb6c08.mp4

![image - 2022-07-05T131712 943](https://user-images.githubusercontent.com/93399543/177442046-00f2b565-ed05-4e22-aea8-3684e74b7065.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @daraksha-dk

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654366872160559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Similar issue https://github.com/Expensify/App/issues/9413

**Comment by puneetlath** [comment]
Upwork job is here: https://www.upwork.com/jobs/~01c019031511555a58

**Comment by eVoloshchak** [comment]
**Proposal:**
Highlighting emojis on keyboard press is handled in EmojiPickerMenu's [highlightAdjacentEmoji](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L216) method. This issue isn't reproducible if emojis are filtered (if there's at least one symbol in emoji picker's search input).

Let's start with the case when user presses arrow up expecting search input to gain focus.
_Expected result:_ [boundsCheck()](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L289) returns `true`, thus calling [onBoundReached()](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L290) and focusing the text input
_Actual result:_ `boundsCheck()` returns `false`

`boundsCheck()` for this case looks like this: `this.state.highlightedIndex - this.numColumns < firstNonHeaderIndex`,
this.numColumns = 8, firstNonHeaderIndex = 8, highlightedIndex = 16 when the first emoji is selected. So we end up with `16 - 8 < 8`, which is `false`. This works for filtered emojis, because in that case firstNonHeaderIndex is [always 0](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L217)
We can fix this by determining if emojis are actually filtered
```javascript
const emojisAreFiltered = this.state.filteredEmojis.length !== this.emojis.length;
```
And replacing this [line](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L289) with 
```javascript
if (emojisAreFiltered) {
    return this.state.highlightedIndex - this.numColumns < firstNonHeaderIndex;
}
return this.state.highlightedIndex - this.numColumns <= firstNonHeaderIndex;
```

Pressing arrow down also works only for filtered emojis, but the cause is a bit defferent. When search input is selected and user presses arrow down, [this](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L245) function is called. Notice how it returns early, never actually calling the [move()](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L251) function. This works ok when emojis are filtered, since in that case there is no header between search input and emojis and we just highlight the first emoji. But when emojis are not filtered, there is a header, and it get's focused instead of emoji. This wouldn't be a problem, since `move()` function iterates over elements until it finds first emoji and focuses it, but, as I said earlier, it is never called in this case.
We can fix this by removing the early return
```diff
  // If nothing is highlighted and an arrow key is pressed
  // select the first emoji
  if (this.state.highlightedIndex === -1) {
+      newIndex = firstNonHeaderIndex;
-      this.setState({highlightedIndex: firstNonHeaderIndex});
-      this.scrollToHighlightedIndex();
-      return;
  }
```
And editing [boundsCheck()](https://github.com/Expensify/App/blob/a0c4e83085f25492fabec48fee43f6ad4f9dc52e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L271) function for this case 

```diff
- this.state.highlightedIndex + this.numColumns > this.state.filteredEmojis.length - 1
+ (emojisAreFiltered && this.state.highlightedIndex === -1) || (this.state.highlightedIndex + this.numColumns > this.state.filteredEmojis.length - 1)
```

Result: 

https://user-images.githubusercontent.com/9059945/178109129-dc607b60-2014-43b3-b77c-f93b662249b3.mp4

**Comment by rushatgabhane** [comment]
@eVoloshchak the cause makes sense! Appreciate you explaining it in detail. We should try to improve the readability in the PR by making new functions :)

🎀 👀 🎀 C+ Reviewed
@puneetlath I like @eVoloshchak's [proposal](https://github.com/Expensify/App/issues/9728#issuecomment-1179550140) 

Welcome back btw 👋

**Comment by eVoloshchak** [comment]
> We should try to improve the readability in the PR by making new functions :)

Yeah, I'll try to make it more readable, it's kinda hard to comprehend right now indeed

> Welcome back btw 

Thanks :)

**Comment by eVoloshchak** [comment]
> We should try to improve the readability in the PR by making new functions :)

Yeah, I'll try to make it more readable, it's kinda hard to comprehend right now indeed

**Comment by puneetlath** [comment]
Sounds good to me too. Great explanation. Let's do it @eVoloshchak. 

Can you apply to the Upwork job as well so I can hire you there? Thanks!

**Comment by eVoloshchak** [comment]
> Can you apply to the Upwork job as well so I can hire you there? Thanks!

Applied on the Upwork
PR is up.
I also found more reliable and simple way to fix this issue, details are in the PR description.

**Comment by neil-marcellini** [comment]
There has been a regression. Please see the related issue.

**Comment by eVoloshchak** [comment]
https://github.com/Expensify/App/issues/10223 was present before this PR, I'm not sure this is a regression
I reverted https://github.com/Expensify/App/pull/9954, you can still see the https://github.com/Expensify/App/issues/10223

https://user-images.githubusercontent.com/9059945/183048734-287a0d65-c264-4ea6-8e4f-c4c700a08169.mp4

**Comment by neil-marcellini** [comment]
#10223 is not the regression. #10182 is the regression.

**Comment by puneetlath** [comment]
Is https://github.com/Expensify/App/issues/10223 related to this? I'm guessing not since it happens on both staging and production.

**Comment by puneetlath** [comment]
Paid @eVoloshchak and @daraksha-dk. 

Sent C+ offer to @rushatgabhane.

**Comment by puneetlath** [comment]
Ah got it, my bad! Updated the offer.

**Comment by puneetlath** [comment]
Everyone has been paid. Thanks for your contributions!
