### ISSUE TITLE
[$250] Pressing :x: takes you to the homepage - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any room > Tap on avatar > Settings
2. Press :x: (top right side)

## Expected Result:
You should be navigated to the chat

## Actual Result:
The chat will close.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.84-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/179663897-bd04f3ed-f0d4-4c8a-9302-3b0c21106cfa.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1656859447789029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal 

We are passing true in dismissModal  function and when it's true we call openDrawer  so removing true will fix it.
https://github.com/Expensify/App/blob/03a2422207ceecaf8ed6a8c24b77558df8f2a848/src/pages/ReportSettingsPage.js#L164

**Comment by robertjchen** [comment]
Proposed fix sounds good to me, let's proceed with the process 👍

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~01c67e3e6346cc3538

**Comment by eVoloshchak** [comment]
**Proposal:**
This happens because we pass `shouldOpenDrawer=true` to `Navigation.dismissModal` on [ReportSettingsPage](https://github.com/Expensify/App/blob/f71bb83a05d8333cc61f6e4e85e4bbbf4a13167a/src/pages/ReportSettingsPage.js#L177). While WorkspaceMembersPage [handles this correctly](https://github.com/Expensify/App/blob/f71bb83a05d8333cc61f6e4e85e4bbbf4a13167a/src/pages/workspace/WorkspaceMembersPage.js#L264). I don't think there's a reason we should pass `shouldOpenDrawer=true`, it doesn't break any of the platforms, I couldn't find an explanation in the original PR either. Maybe it was copied by mistake from another component, since it was present from the [creation](https://github.com/Expensify/App/commit/bddeb9ead4124d388830a44962c45d69b5370139) of this component?

So all we need to do is change this line 
https://github.com/Expensify/App/blob/f71bb83a05d8333cc61f6e4e85e4bbbf4a13167a/src/pages/ReportSettingsPage.js#L177
```javascript
onCloseButtonPress={() => Navigation.dismissModal()}
```

**Result:**

https://user-images.githubusercontent.com/9059945/181475973-7cac8266-a636-46e4-b922-e060f21d1849.mp4

**Comment by Santhosh-Sellavel** [comment]
@stitesExpensify or @robertjchen 

@thesahindia [proposal](https://github.com/Expensify/App/issues/9976#issuecomment-1188620216) looks good for me too!
🎀 👀 🎀  C+ Reviewed 

cc: @kevinksullivan 
Thanks!

**Comment by stitesExpensify** [comment]
LGTM. I agree, let's hire @thesahindia

**Comment by thesahindia** [comment]
PR is up.

cc: @Santhosh-Sellavel

**Comment by thesahindia** [comment]
Not sure but I think the fix was deployed to production but melvin didn't comment about it, I tested it on prod and it is not reproducible anymore.

**Comment by robertjchen** [comment]
Thanks for the confirmation! This should be complete for now 👍

**Comment by thesahindia** [comment]
@robertjchen, payment is pending.

cc: @kevinksullivan

**Comment by Santhosh-Sellavel** [comment]
@stitesExpensify 

@kevinksullivan is ⭕⭕⭕, can you helps get payment issued here, thanks!

**Comment by stitesExpensify** [comment]
Hi @laurenreidexpensify can you help get the payment issued?

**Comment by mallenexpensify** [comment]
Sorry for the delay @thesahindia and @Santhosh-Sellavel both of you are paid.  Santhosh = $250 for C+, Sahil = $500 for fix and reporting.
